Repository opensearch-project/sql, pull requests merged in 2021-06, with the labels that each got.

#123 Fix the aggregation filter missing in named aggregators
  core/src/main/java/org/opensearch/sql/expression/aggregation/NamedAggregator.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  integ-test/src/test/java/org/opensearch/sql/sql/AggregationIT.java
  integ-test/src/test/resources/correctness/queries/subqueries.txt
Labels: SQL, bug

#148 Level up README markdown
  README.md
Labels: documentation, v1.0.0

#146 Build against OpenSearch 1.0.0 and bump artifact version to 1.0.0.0
  .github/workflows/draft-release-notes-workflow.yml
  .github/workflows/sql-test-and-build-workflow.yml
  .github/workflows/sql-workbench-release-workflow.yml
  .github/workflows/sql-workbench-test-and-build-workflow.yml
  build.gradle
  sql-cli/src/opensearch_sql_cli/__init__.py
  sql-jdbc/build.gradle
  workbench/opensearch_dashboards.json
  workbench/package.json
Labels: v1.0.0
