Repository opensearch-project/sql, pull requests merged in 2022-12, with the labels that each got.

#1091 Improve pushdown optimization and logical to physical transformation
  core/src/main/java/org/opensearch/sql/planner/DefaultImplementor.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitor.java
  core/src/main/java/org/opensearch/sql/planner/optimizer/LogicalPlanOptimizer.java
  core/src/main/java/org/opensearch/sql/planner/optimizer/pattern/Patterns.java
  core/src/main/java/org/opensearch/sql/planner/optimizer/rule/read/CreateTableScanBuilder.java
  core/src/main/java/org/opensearch/sql/planner/optimizer/rule/read/TableScanPushDown.java
  core/src/main/java/org/opensearch/sql/storage/Table.java
  core/src/main/java/org/opensearch/sql/storage/read/TableScanBuilder.java
  core/src/test/java/org/opensearch/sql/planner/DefaultImplementorTest.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitorTest.java
  core/src/test/java/org/opensearch/sql/planner/optimizer/LogicalPlanOptimizerTest.java
  core/src/test/java/org/opensearch/sql/planner/optimizer/pattern/PatternsTest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/OpenSearchLogicalIndexAgg.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/OpenSearchLogicalIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/OpenSearchLogicalPlanOptimizerFactory.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/rule/MergeAggAndIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/rule/MergeAggAndRelation.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/rule/MergeFilterAndRelation.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/rule/MergeLimitAndIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/rule/MergeLimitAndRelation.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/rule/MergeSortAndIndexAgg.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/rule/MergeSortAndIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/rule/MergeSortAndRelation.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/rule/OptimizationRuleUtils.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/rule/PushProjectAndIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/logical/rule/PushProjectAndRelation.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/CompositeAggregationParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/FilterParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/MetricParserHelper.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/SingleValueParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/StatsParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/TopHitsParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanAggregationBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanQueryBuilder.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/planner/logical/OpenSearchLogicOptimizerTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/planner/logical/OpenSearchLogicalIndexScanTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchDefaultImplementorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanOptimizationTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/utils/Utils.java
Labels: maintenance

#1154 Add reverse() string function to V2
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/text/TextFunction.java
  core/src/test/java/org/opensearch/sql/expression/text/TextFunctionTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/string.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/TextFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/TextFunctionIT.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement

#1150 Update Jackson to 2.14.1 and fix dependency resolution issues
  build.gradle
  integ-test/build.gradle
  plugin/build.gradle
Labels: dependencies

#1161 Add release notes for 1.3.7 release
  release-notes/opensearch-sql.release-notes-1.3.7.0.md
Labels: release

#1160 Change LIKE operator case-insensitive match
  core/src/main/java/org/opensearch/sql/utils/OperatorUtils.java
  docs/user/dql/expressions.rst
  docs/user/ppl/functions/string.rst
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LikeQuery.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
Labels: v2.5.0

#1162 Add release note for 2.4.1 release
  release-notes/opensearch-sql.release-notes-2.4.1.0.md
Labels: release

#1094 Add table write operator and builder
  core/src/main/java/org/opensearch/sql/planner/DefaultImplementor.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalPlanDSL.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitor.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalWrite.java
  core/src/main/java/org/opensearch/sql/planner/optimizer/LogicalPlanOptimizer.java
  core/src/main/java/org/opensearch/sql/planner/optimizer/pattern/Patterns.java
  core/src/main/java/org/opensearch/sql/planner/optimizer/rule/write/CreateTableWriteBuilder.java
  core/src/main/java/org/opensearch/sql/planner/physical/PhysicalPlanNodeVisitor.java
  core/src/main/java/org/opensearch/sql/storage/Table.java
  core/src/main/java/org/opensearch/sql/storage/write/TableWriteBuilder.java
  core/src/main/java/org/opensearch/sql/storage/write/TableWriteOperator.java
  core/src/test/java/org/opensearch/sql/planner/DefaultImplementorTest.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitorTest.java
  core/src/test/java/org/opensearch/sql/planner/optimizer/LogicalPlanOptimizerTest.java
  core/src/test/java/org/opensearch/sql/planner/optimizer/pattern/PatternsTest.java
  core/src/test/java/org/opensearch/sql/storage/write/TableWriteOperatorTest.java
Labels: enhancement, backport main

#1169 Using jackson and jackson_databind version defined in OpenSearch
  build.gradle
  core/build.gradle
  integ-test/build.gradle
  opensearch/build.gradle
  plugin/build.gradle
  prometheus/build.gradle
  protocol/build.gradle
Labels: dependencies, backport 1.x, backport 1.3, backport 2.0, backport 2.1, backport 2.x, backport 2.2, backport 2.4

#1178 Using jackson and jackson_databind version defined in OpenSearch (#1169)
  build.gradle
  integ-test/build.gradle
  opensearch/build.gradle
  plugin/build.gradle
  protocol/build.gradle
Labels: infrastructure

#1179 Using jackson and jackson_databind version defined in OpenSearch (#1169)
  build.gradle
  core/build.gradle
  integ-test/build.gradle
  opensearch/build.gradle
  plugin/build.gradle
  prometheus/build.gradle
  protocol/build.gradle
Labels: infrastructure

#1163 Add BETWEEN expression in v2 engine
  core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
  core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
  core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
  core/src/main/java/org/opensearch/sql/ast/expression/Between.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
  docs/user/dql/expressions.rst
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: enhancement, legacy, backport main

#1172 Fix arithmetic operator precedence
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: bug, backport 2.x

#1185 Using jackson and jackson_databind version defined in OpenSearch
  build.gradle
  opensearch/build.gradle
  protocol/build.gradle
Labels: infrastructure

#1186 Using jackson and jackson_databind version defined in OpenSearch
  build.gradle
  opensearch/build.gradle
  protocol/build.gradle
Labels: infrastructure

#1184 Using jackson and jackson_databind version defined in OpenSearch
  build.gradle
  integ-test/build.gradle
  opensearch/build.gradle
  plugin/build.gradle
  protocol/build.gradle
Labels: infrastructure

#1193 Adding UTC_DATE, UTC_TIME, UTC_TIMESTAMP
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/NowLikeFunctionTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/datetime.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  ppl/src/test/java/org/opensearch/sql/ppl/antlr/NowLikeFunctionParserTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstNowLikeFunctionTest.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstNowLikeFunctionTest.java
Labels: enhancement, backport 2.x

#1067 Validate Field and Fields Parameters in Relevance Search Functions
  core/src/main/java/org/opensearch/sql/expression/function/OpenSearchFunctions.java
  core/src/main/java/org/opensearch/sql/expression/function/RelevanceFunctionResolver.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/config/TestConfig.java
  core/src/test/java/org/opensearch/sql/expression/function/RelevanceFunctionResolverTest.java
  integ-test/src/test/java/org/opensearch/sql/sql/MatchIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQuery.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchBoolPrefixQueryTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchPhrasePrefixQueryTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchPhraseQueryTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchQueryTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/WildcardQueryTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQueryTest.java
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: bug, backport 2.x

#1177 Deprecated Spring IoC and using Guice instead
  build.gradle
  core/build.gradle
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionReferenceOptimizerTest.java
  core/src/test/java/org/opensearch/sql/analysis/NamedExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/QualifierAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/SelectAnalyzeTest.java
  core/src/test/java/org/opensearch/sql/analysis/SelectExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/WindowExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/config/TestConfig.java
  core/src/test/java/org/opensearch/sql/executor/QueryServiceTest.java
  core/src/test/java/org/opensearch/sql/expression/ExpressionTestBase.java
  core/src/test/java/org/opensearch/sql/expression/function/FunctionPropertiesTestConfig.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalDedupeTest.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalEvalTest.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalSortTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/PhysicalPlanTestBase.java
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/StreamingQueryIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSQLQueryAction.java
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlAction.java
  legacy/src/test/java/org/opensearch/sql/legacy/plugin/RestSQLQueryActionTest.java
  plugin/build.gradle
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  plugin/src/main/java/org/opensearch/sql/plugin/config/OpenSearchPluginConfig.java
  plugin/src/main/java/org/opensearch/sql/plugin/config/OpenSearchPluginModule.java
  plugin/src/main/java/org/opensearch/sql/plugin/transport/TransportPPLQueryAction.java
  ppl/build.gradle
  ppl/src/main/java/org/opensearch/sql/ppl/config/PPLServiceConfig.java
  ppl/src/test/java/org/opensearch/sql/ppl/PPLServiceTest.java
  sql/build.gradle
  sql/src/main/java/org/opensearch/sql/sql/config/SQLServiceConfig.java
  sql/src/test/java/org/opensearch/sql/sql/SQLServiceTest.java
Labels: infrastructure, backport 2.x

#1189 Fix back quoted alias of FROM subquery
  docs/user/limitations/limitations.rst
  integ-test/src/test/resources/correctness/bugfixes/550.txt
  sql/src/main/java/org/opensearch/sql/sql/parser/AstBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
Labels: bug, SQL, backport 2.x
