Repository opensearch-project/sql, pull requests merged in 2022-10, with the labels that each got.

#827 Add Support for Highlight Wildcard in SQL
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
  core/src/main/java/org/opensearch/sql/analysis/HighlightAnalyzer.java
  core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
  core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
  core/src/main/java/org/opensearch/sql/ast/expression/HighlightFunction.java
  core/src/main/java/org/opensearch/sql/expression/HighlightExpression.java
  core/src/main/java/org/opensearch/sql/expression/function/OpenSearchFunctions.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalHighlight.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalPlanDSL.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/NamedExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/expression/HighlightExpressionTest.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitorTest.java
  integ-test/src/test/java/org/opensearch/sql/sql/HighlightFunctionIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchDefaultImplementorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexScanTest.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: enhancement, SQL, PPL

#906 add groupId to pluginzip publication
  plugin/build.gradle
Labels: backport 2.x

#911 Fix broken links
  release-notes/opendistro-for-elasticsearch-sql.release-notes-1.3.0.0.md
  release-notes/opensearch-sql.release-notes-1.2.0.0.md
Labels: backport 1.x, backport main

#918 Update SQL CLI to use AWS session token.
  sql-cli/src/opensearch_sql_cli/main.py
  sql-cli/src/opensearch_sql_cli/opensearch_connection.py
Labels: enhancement, CLI

#943 Update version of `jackson-databind` for `sql-jdbc` only
  sql-jdbc/build.gradle
Labels: JDBC, dependencies

#867 Add `typeof` function.
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/config/ExpressionConfig.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/system/SystemFunctions.java
  core/src/test/java/org/opensearch/sql/expression/system/SystemFunctionsTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/system.rst
  docs/user/ppl/index.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DataTypeIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/SystemFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/SystemFunctionIT.java
  integ-test/src/test/resources/datatypes.json
  integ-test/src/test/resources/indexDefinitions/datatypes_index_mapping.json
  opensearch/src/test/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataTypeRecognitionTest.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement, SQL, PPL

#941 Update JDBC driver version
  sql-jdbc/build.gradle
  sql-jdbc/src/main/java/org/opensearch/jdbc/ConnectionImpl.java
  sql-jdbc/src/main/java/org/opensearch/jdbc/internal/Version.java
  sql-jdbc/src/test/java/org/opensearch/jdbc/internal/VersionMatchTest.java
Labels: bug, JDBC

#934 Fix result order of parse with other run time fields
  core/src/main/java/org/opensearch/sql/planner/physical/ProjectOperator.java
  core/src/test/java/org/opensearch/sql/planner/physical/ProjectOperatorTest.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ParseCommandIT.java
Labels: bug, v2.4.0

#907 feat: enable ci for windows and macos
  .github/workflows/sql-test-and-build-workflow.yml
  .github/workflows/sql-workbench-test-and-build-workflow.yml
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/utils/PrettyFormatterTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/AggregationQueryBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/MetricAggregationBuilderTest.java
  protocol/src/test/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatterTest.java
  protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java
  workbench/package.json
Labels: backport main

#952 Add category_field to AD command in PPL
  core/src/main/java/org/opensearch/sql/utils/MLCommonsConstants.java
  docs/category.json
  docs/user/ppl/cmd/ad.rst
  doctest/test_data/nyc_taxi.json
  doctest/test_mapping/nyc_taxi.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/ADOperator.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperatorActions.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
Labels: v2.4.0

#919 AD timefield name issue
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/config/TestConfig.java
Labels: bug, v2.4.0, ml

#904 Fix manual CI workflow and add `name` option.
  .github/workflows/sql-test-workflow.yml
Labels: infrastructure, backport 1.x

#978 Removed json-smart in the JDBC driver
  sql-jdbc/build.gradle
Labels: JDBC, dependencies

#950 Add time window and window assigner
  core/src/main/java/org/opensearch/sql/planner/streaming/windowing/Window.java
  core/src/main/java/org/opensearch/sql/planner/streaming/windowing/assigner/SlidingWindowAssigner.java
  core/src/main/java/org/opensearch/sql/planner/streaming/windowing/assigner/TumblingWindowAssigner.java
  core/src/main/java/org/opensearch/sql/planner/streaming/windowing/assigner/WindowAssigner.java
  core/src/main/java/org/opensearch/sql/utils/DateTimeUtils.java
  core/src/test/java/org/opensearch/sql/planner/streaming/windowing/WindowTest.java
  core/src/test/java/org/opensearch/sql/planner/streaming/windowing/assigner/SlidingWindowAssignerTest.java
  core/src/test/java/org/opensearch/sql/planner/streaming/windowing/assigner/TumblingWindowAssignerTest.java
Labels: enhancement

#949 Add take() aggregation function in PPL
  core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
  core/src/main/java/org/opensearch/sql/ast/expression/AggregateFunction.java
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/aggregation/AggregatorFunction.java
  core/src/main/java/org/opensearch/sql/expression/aggregation/TakeAggregator.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/expression/aggregation/TakeAggregatorTest.java
  docs/user/ppl/cmd/stats.rst
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/TopHitsParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/MetricAggregationBuilder.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/response/AggregationResponseUtils.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchAggregationResponseParserTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/MetricAggregationBuilderTest.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
Labels: PPL, v2.4.0

#974 Add metadatalog interface and default in memory implementation
  core/src/main/java/org/opensearch/sql/executor/streaming/DefaultMetadataLog.java
  core/src/main/java/org/opensearch/sql/executor/streaming/MetadataLog.java
  core/src/test/java/org/opensearch/sql/executor/streaming/DefaultMetadataLogTest.java
Labels: enhancement

#933 Add functions `PERIOD_ADD` and `PERIOD_DIFF`.
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java
  core/src/test/java/org/opensearch/sql/expression/datetime/PeriodFunctionsTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/datetime.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement

#926 Enable ignored and disabled tests
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/SelectExpressionAnalyzerTest.java
  integ-test/src/test/java/org/opensearch/sql/legacy/AggregationIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/PrettyFormatResponseIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/QueryIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SubqueryIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/FieldsCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/MatchPhraseIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/QueryAnalysisIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/RenameCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/SortCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/QueryValidationIT.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/planner/logical/OpenSearchLogicOptimizerTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/serialization/DefaultExpressionSerializerTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstAggregationBuilderTest.java
Labels: infrastructure

#914 List tables/metrics using information_schema in source command.
  core/src/main/java/org/opensearch/sql/CatalogSchemaName.java
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/analysis/CatalogSchemaIdentifierNameResolver.java
  core/src/main/java/org/opensearch/sql/analysis/model/CatalogName.java
  core/src/main/java/org/opensearch/sql/analysis/model/CatalogSchemaIdentifierName.java
  core/src/main/java/org/opensearch/sql/analysis/model/SchemaName.java
  core/src/main/java/org/opensearch/sql/storage/StorageEngine.java
  core/src/main/java/org/opensearch/sql/utils/SystemIndexUtils.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/analysis/model/CatalogSchemaIdentifierNameResolverTest.java
  core/src/test/java/org/opensearch/sql/analysis/model/CatalogSchemaIdentifierNameTest.java
  core/src/test/java/org/opensearch/sql/config/TestConfig.java
  core/src/test/java/org/opensearch/sql/planner/PlannerTest.java
  core/src/test/java/org/opensearch/sql/storage/StorageEngineTest.java
  core/src/test/java/org/opensearch/sql/utils/SystemIndexUtilsTest.java
  docs/category.json
  docs/user/ppl/cmd/information_schema.rst
  docs/user/ppl/index.rst
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ShowCatalogsCommandIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchStorageEngine.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchStorageEngineTest.java
  plugin/src/main/java/org/opensearch/sql/plugin/catalog/CatalogServiceImpl.java
  plugin/src/test/java/org/opensearch/sql/plugin/catalog/CatalogServiceImplTest.java
  ppl/src/main/java/org/opensearch/sql/ppl/config/PPLServiceConfig.java
  ppl/src/test/java/org/opensearch/sql/ppl/PPLServiceTest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClient.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/data/constants/PrometheusFieldConstants.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/request/PrometheusDescribeMetricRequest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/request/system/PrometheusDescribeMetricRequest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/request/system/PrometheusListMetricsRequest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/request/system/PrometheusSystemRequest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/request/system/model/MetricMetadata.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/response/PrometheusResponse.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricDefaultSchema.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTable.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageEngine.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/implementor/PrometheusDefaultImplementor.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/system/PrometheusSystemTable.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/system/PrometheusSystemTableScan.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/system/PrometheusSystemTableSchema.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/client/PrometheusClientImplTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/request/PrometheusDescribeMetricRequestTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/request/PrometheusListMetricsRequestTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricScanTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTableTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageEngineTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/system/PrometheusSystemTableScanTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/system/PrometheusSystemTableTest.java
  prometheus/src/test/resources/all_metrics_response.json
Labels: enhancement, v2.4.0

#992 Update Jackson Databind version to 2.13.4.2
  build.gradle
  core/build.gradle
  integ-test/build.gradle
  opensearch/build.gradle
  plugin/build.gradle
  prometheus/build.gradle
  protocol/build.gradle
Labels: dependencies

#971 A Generic ML Command in PPL
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/analysis/TypeEnvironment.java
  core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
  core/src/main/java/org/opensearch/sql/ast/tree/ML.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalML.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitor.java
  core/src/main/java/org/opensearch/sql/planner/physical/PhysicalPlanNodeVisitor.java
  core/src/main/java/org/opensearch/sql/utils/MLCommonsConstants.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitorTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/PhysicalPlanNodeVisitorTest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtector.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperatorActions.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/MLOperator.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtectorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/planner/physical/MLOperatorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchDefaultImplementorTest.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
Labels: PPL, v2.4.0, ml
