Repository opensearch-project/sql, pull requests merged in 2022-08, with the labels that each got.

#730 Add release notes for 2.2.0.0
  release-notes/opensearch-sql.release-notes-2.2.0.0.md
Labels: backport 2.x, backport 2.2

#736 Bump workbench version to 2.2.0.0
  workbench/opensearch_dashboards.json
Labels: backport 2.2

#735 Bump JDBC driver's dependency version
  sql-jdbc/build.gradle
  sql-jdbc/src/test/java/org/opensearch/jdbc/transport/http/auth/aws/AWSRequestSigningApacheInterceptorTests.java
Labels: JDBC

#745 Bump Jackson dependency version
  build.gradle
  core/build.gradle
  integ-test/build.gradle
  opensearch/build.gradle
  plugin/build.gradle
  ppl/build.gradle
  protocol/build.gradle
  sql-jdbc/build.gradle
  sql/build.gradle
Labels: dependencies

#716 Extend query size limit using scroll
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalPlanDSL.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/ppl/HeadCommandIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchRestClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/system/OpenSearchDescribeIndexRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexScan.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngineTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtectorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchDefaultImplementorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexScanTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/utils/Utils.java
  opensearch/src/test/resources/mappings/accounts2.json
Labels: backport 2.x

#751 Bump Spring version in 1.3
  build.gradle
  core/build.gradle
  plugin/build.gradle
  ppl/build.gradle
  sql/build.gradle
Labels: dependencies, backport 1.3

#747 Replace 2x `LogUtils` by `QueryContext`
  common/src/main/java/org/opensearch/sql/common/utils/QueryContext.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/AsyncRestExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/cursor/CursorAsyncRestExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlAction.java
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlStatsAction.java
  legacy/src/main/java/org/opensearch/sql/legacy/utils/LogUtils.java
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/utils/QueryContextTest.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLStatsAction.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java
  plugin/src/main/java/org/opensearch/sql/plugin/transport/TransportPPLQueryAction.java
  ppl/src/main/java/org/opensearch/sql/ppl/PPLService.java
Labels: backport 1.x, backport 2.x

#756 Bump jackson-databind version 1.13.2.2
  build.gradle
  opensearch/build.gradle
  protocol/build.gradle
  sql-jdbc/build.gradle
Labels: dependencies, backport 1.x

#757 Backport Spring and jackson-databind version bump to 1.x
  build.gradle
  core/build.gradle
  opensearch/build.gradle
  plugin/build.gradle
  ppl/build.gradle
  protocol/build.gradle
  sql-jdbc/build.gradle
  sql/build.gradle
Labels: dependencies

#759 Backport Spring and jackson-databind version bump to 2.x
  .github/workflows/sql-test-and-build-workflow.yml
  build.gradle
  core/build.gradle
  integ-test/build.gradle
  opensearch/build.gradle
  plugin/build.gradle
  ppl/build.gradle
  protocol/build.gradle
  scripts/bwctest.sh
  sql-jdbc/build.gradle
  sql/build.gradle
Labels: dependencies

#748 Schedule request in worker thread
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlAction.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/executor/Scheduler.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/SchedulerTest.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLQueryAction.java
Labels: backport 2.x

#767 Bump Checkstyle version to latest
  build.gradle
  config/checkstyle/google_checks.xml
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitorTest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/core/ExpressionScript.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtectorTest.java
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/Format.java
Labels: dependencies, backport 2.x
