Repository opensearch-project/sql, pull requests merged in 2022-03, with the labels that each got.

#468 PPL integration with AD and ml-commons
  core/build.gradle
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
  core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
  core/src/main/java/org/opensearch/sql/ast/expression/DataType.java
  core/src/main/java/org/opensearch/sql/ast/tree/AD.java
  core/src/main/java/org/opensearch/sql/ast/tree/Kmeans.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalAD.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalMLCommons.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitor.java
  core/src/main/java/org/opensearch/sql/planner/physical/PhysicalPlanNodeVisitor.java
  core/src/main/java/org/opensearch/sql/utils/MLCommonsConstants.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitorTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/PhysicalPlanNodeVisitorTest.java
  opensearch/build.gradle
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/MLClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchRestClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtector.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/ADOperator.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperator.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperatorActions.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtectorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperatorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchDefaultImplementorTest.java
  plugin/src/main/plugin-metadata/plugin-security.policy
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/utils/ArgumentFactory.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
Labels: v1.3.0, backport 1.x

#479 Fix certificate validation for ODBC driver
  sql-odbc/scripts/build_aws-sdk-cpp.ps1
  sql-odbc/scripts/build_libcurl-vcpkg.ps1
  sql-odbc/scripts/build_windows.ps1
  sql-odbc/src/installer/CMakeLists.txt
  sql-odbc/src/sqlodbc/opensearch_communication.cpp
Labels: v1.3.0, backport 1.x

#486 Add parse docs to PPL commands index
  docs/user/ppl/index.rst
Labels: backport 1.3

#490 Add 1.3 release notes
  release-notes/opensearch-sql.release-notes-1.3.0.0.md
Labels: backport 1.3

#500 AD and Kmeans grammar edits
  docs/user/ppl/cmd/ad.rst
  docs/user/ppl/cmd/kmeans.rst
Labels: backport 1.x, backport 1.3

#512 Add JDK 17 support
  .github/workflows/sql-jdbc-test-and-build-workflow.yml
  .github/workflows/sql-test-and-build-workflow.yml
  DEVELOPER_GUIDE.rst
  build.gradle
  core/build.gradle
  legacy/build.gradle
  opensearch/build.gradle
  ppl/build.gradle
  protocol/build.gradle
  sql/build.gradle
Labels: SQL, v2.0.0

#520 Fix bwc build issue with jdk17
  integ-test/build.gradle
Labels: v2.0.0
