Repository opensearch-project/sql, pull requests merged in 2022-11, with the labels that each got.

#989 Describe Table with catalog name.
  docs/user/general/identifiers.rst
  docs/user/ppl/cmd/describe.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DescribeCommandIT.java
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/client/PrometheusClientImplTest.java
Labels: enhancement, v2.4.0, backport 2.4

#988 Catalog Enhancements
  core/src/main/java/org/opensearch/sql/catalog/model/AbstractAuthenticationData.java
  core/src/main/java/org/opensearch/sql/catalog/model/AuthenticationType.java
  core/src/main/java/org/opensearch/sql/catalog/model/BasicAuthenticationData.java
  core/src/main/java/org/opensearch/sql/catalog/model/CatalogMetadata.java
  core/src/main/java/org/opensearch/sql/catalog/model/auth/AuthenticationType.java
  core/src/main/java/org/opensearch/sql/storage/StorageEngineFactory.java
  docs/user/ppl/admin/catalog.rst
  docs/user/ppl/admin/prometheus_connector.rst
  docs/user/ppl/index.rst
  doctest/catalog/catalog.json
  integ-test/build.gradle
  integ-test/src/test/resources/catalog/catalog.json
  plugin/build.gradle
  plugin/src/main/java/org/opensearch/sql/plugin/catalog/CatalogServiceImpl.java
  plugin/src/main/plugin-metadata/plugin-security.policy
  plugin/src/test/java/org/opensearch/sql/plugin/catalog/CatalogServiceImplTest.java
  plugin/src/test/resources/catalog_missing_name.json
  plugin/src/test/resources/catalogs.json
  plugin/src/test/resources/duplicate_catalog_names.json
  plugin/src/test/resources/illegal_catalog_name.json
  plugin/src/test/resources/multiple_catalogs.json
  prometheus/build.gradle
  prometheus/src/main/java/org/opensearch/sql/prometheus/authinterceptors/AwsSigningInterceptor.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/authinterceptors/BasicAuthenticationInterceptor.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/request/PrometheusQueryRequest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/authinterceptors/AwsSigningInterceptorTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/authinterceptors/BasicAuthenticationInterceptorTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/client/PrometheusClientImplTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
Labels: enhancement, v2.4.0, backport 2.4

#839 Rework on error reporting to make it more verbose and human-friendly.
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  legacy/src/main/java/org/opensearch/sql/legacy/utils/QueryDataAnonymizer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/FunctionParameterRepository.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchBoolPrefixQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchPhrasePrefixQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchPhraseQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiFieldQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiMatchQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/QueryStringQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SimpleQueryStringQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQuery.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MultiMatchTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/QueryStringTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/SimpleQueryStringTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiFieldQueryTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQueryBuildTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQueryTest.java
Labels: enhancement

#959 Add watermark generator
  core/src/main/java/org/opensearch/sql/planner/streaming/watermark/BoundedOutOfOrderWatermarkGenerator.java
  core/src/main/java/org/opensearch/sql/planner/streaming/watermark/WatermarkGenerator.java
  core/src/test/java/org/opensearch/sql/planner/streaming/watermark/BoundedOutOfOrderWatermarkGeneratorTest.java
Labels: enhancement

#958 Add stream context and window trigger
  core/src/main/java/org/opensearch/sql/planner/streaming/StreamContext.java
  core/src/main/java/org/opensearch/sql/planner/streaming/windowing/trigger/AfterWatermarkWindowTrigger.java
  core/src/main/java/org/opensearch/sql/planner/streaming/windowing/trigger/TriggerResult.java
  core/src/main/java/org/opensearch/sql/planner/streaming/windowing/trigger/WindowTrigger.java
  core/src/test/java/org/opensearch/sql/planner/streaming/windowing/trigger/AfterWatermarkWindowTriggerTest.java
Labels: enhancement

#1008 [Backport 2.4] Merge pull request #839 from Bit-Quill/integ-improve-error-reporting
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  legacy/src/main/java/org/opensearch/sql/legacy/utils/QueryDataAnonymizer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/FunctionParameterRepository.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchBoolPrefixQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchPhrasePrefixQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchPhraseQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiFieldQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiMatchQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/QueryStringQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SimpleQueryStringQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQuery.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MultiMatchTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/QueryStringTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/SimpleQueryStringTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiFieldQueryTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQueryBuildTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQueryTest.java
Labels: enhancement

#1015 Add function name as identifier in antlr
  docs/user/dql/functions.rst
  docs/user/ppl/functions/datetime.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstNowLikeFunctionTest.java
  sql/src/main/antlr/OpenSearchSQLIdentifierParser.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstQualifiedNameBuilderTest.java
Labels: backport 2.4

#1011 Disable loading `ML-commons` plugin for doctests
  docs/user/ppl/cmd/ad.rst
  docs/user/ppl/cmd/kmeans.rst
  doctest/build.gradle
Labels: infrastructure

#956 Prometheus select metric and stats queries.
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  docs/user/ppl/admin/prometheus_connector.rst
  docs/user/ppl/cmd/describe.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DescribeCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusCatalogCommandsIT.java
  plugin/src/main/java/org/opensearch/sql/plugin/catalog/CatalogServiceImpl.java
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/functions/implementation/QueryRangeFunctionImplementation.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/planner/logical/PrometheusLogicalMetricAgg.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/planner/logical/PrometheusLogicalMetricScan.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/planner/logical/PrometheusLogicalPlanOptimizerFactory.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/planner/logical/rules/MergeAggAndIndexScan.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/planner/logical/rules/MergeAggAndRelation.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/planner/logical/rules/MergeFilterAndRelation.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/request/PrometheusQueryRequest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/response/PrometheusResponse.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricDefaultSchema.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricScan.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTable.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageEngine.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/implementor/PrometheusDefaultImplementor.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/model/PrometheusResponseFieldNames.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/model/QueryRangeParameters.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/AggregationQueryBuilder.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/SeriesSelectionQueryBuilder.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/StepParameterResolver.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/TimeRangeParametersResolver.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/functions/QueryRangeFunctionImplementationTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/functions/QueryRangeTableFunctionResolverTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/planner/logical/PrometheusLogicOptimizerTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/request/PrometheusDescribeMetricRequestTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricScanTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTableTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageEngineTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/querybuilders/StepParameterResolverTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/utils/LogicalPlanUtils.java
Labels: enhancement, v2.4.0, backport 2.4

#1000 Fix incorrect results returned by `min`, `max` and `avg`
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
  integ-test/src/test/java/org/opensearch/sql/sql/AggregationIT.java
  integ-test/src/test/resources/calcs.json
  integ-test/src/test/resources/indexDefinitions/calcs_index_mappings.json
  integ-test/src/test/resources/indexDefinitions/null_missing_index_mapping.json
  integ-test/src/test/resources/null_missing.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/SingleValueParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/StatsParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/Utils.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchAggregationResponseParserTest.java
Labels: bug, backport 2.4

#1023 Bump sql-cli version to 1.1.0
  sql-cli/src/opensearch_sql_cli/__init__.py
Labels: CLI, backport 2.4

#1033 Add 2.4 release note for SQL/PPL
  release-notes/opensearch-sql.release-notes-2.4.0.0.md
Labels: documentation, release, backport 2.x, backport main

#983 [Backport 1.x] Fix manual CI workflow and add name option. #904
  .github/workflows/sql-test-workflow.yml
Labels: infrastructure

#1025 Fix `FLOAT` -> `DOUBLE` cast.
  core/src/main/java/org/opensearch/sql/expression/operator/convert/TypeCastOperator.java
  core/src/test/java/org/opensearch/sql/expression/operator/convert/TypeCastOperatorTest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LuceneQuery.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
Labels: bug

#1010 Add Query Function As Alternate Syntax to Query_string Function
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/function/OpenSearchFunctions.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/expression/function/OpenSearchFunctionsTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/legacy/MethodQueryIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/QueryIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/NoFieldQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/QueryQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQuery.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/QueryTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/NoFieldQueryTest.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: enhancement

#990 Deprecate span collector
  core/src/main/java/org/opensearch/sql/expression/span/SpanExpression.java
  core/src/main/java/org/opensearch/sql/planner/physical/AggregationOperator.java
  core/src/main/java/org/opensearch/sql/planner/physical/collector/BucketCollector.java
  core/src/main/java/org/opensearch/sql/planner/physical/collector/Collector.java
  core/src/main/java/org/opensearch/sql/planner/physical/collector/Rounding.java
  core/src/main/java/org/opensearch/sql/planner/physical/collector/SpanCollector.java
  core/src/test/java/org/opensearch/sql/expression/span/SpanExpressionTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/AggregationOperatorTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/collector/RoundingTest.java
Labels: maintenance

#991 Update DATE and TIME functions to parse string input as datetime
  core/src/main/java/org/opensearch/sql/data/model/ExprDateValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprTimeValue.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/utils/DateTimeFormatters.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/datetime.rst
Labels: enhancement

#994 Add Streaming source impl
  .github/workflows/sql-test-and-build-workflow.yml
  core/src/main/java/org/opensearch/sql/executor/streaming/Batch.java
  core/src/main/java/org/opensearch/sql/executor/streaming/Offset.java
  core/src/main/java/org/opensearch/sql/executor/streaming/StreamingSource.java
  core/src/main/java/org/opensearch/sql/storage/split/Split.java
  doctest/build.gradle
  filesystem/build.gradle
  filesystem/src/main/java/org/opensearch/sql/filesystem/storage/split/FileSystemSplit.java
  filesystem/src/main/java/org/opensearch/sql/filesystem/streaming/FileMetaData.java
  filesystem/src/main/java/org/opensearch/sql/filesystem/streaming/FileSystemStreamSource.java
  filesystem/src/test/java/org/opensearch/sql/filesystem/streaming/FileSystemStreamSourceTest.java
  integ-test/build.gradle
  plugin/build.gradle
  settings.gradle
Labels: feature

#1041 Fix for errors in prometheus connector when backquotes are used for fieldnames in aggregations.
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusCatalogCommandsIT.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/response/PrometheusResponse.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/implementor/PrometheusDefaultImplementor.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/model/PrometheusResponseFieldNames.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/AggregationQueryBuilder.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricScanTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTableTest.java
Labels: bug, backport 2.x

#1058 [2.4] Bump jackson to 2.14.0
  build.gradle
Labels: backport 2.x

#1055 Add valueOf() to Expression
  core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/Expression.java
  core/src/main/java/org/opensearch/sql/expression/aggregation/TakeAggregator.java
  core/src/main/java/org/opensearch/sql/expression/parse/GrokExpression.java
  core/src/main/java/org/opensearch/sql/expression/parse/ParseExpression.java
  core/src/main/java/org/opensearch/sql/expression/parse/PatternsExpression.java
  core/src/main/java/org/opensearch/sql/expression/parse/RegexExpression.java
  core/src/main/java/org/opensearch/sql/planner/physical/ValuesOperator.java
  core/src/main/java/org/opensearch/sql/planner/physical/collector/Rounding.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/expression/NamedExpressionTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java
  core/src/test/java/org/opensearch/sql/expression/datetime/FromUnixTimeTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/NowLikeFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/PeriodFunctionsTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/UnixTimeStampTest.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/ArithmeticFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/operator/convert/TypeCastOperatorTest.java
  core/src/test/java/org/opensearch/sql/expression/system/SystemFunctionsTest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/MetricAggregationBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LuceneQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiFieldQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/NoFieldQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQuery.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataTypeRecognitionTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/functions/implementation/QueryRangeFunctionImplementation.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/TimeRangeParametersResolver.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/functions/QueryRangeFunctionImplementationTest.java
Labels: maintenance

#1044 Add micro batch streaming execution
  core/src/main/java/org/opensearch/sql/executor/QueryService.java
  core/src/main/java/org/opensearch/sql/executor/streaming/MicroBatchStreamingExecution.java
  core/src/main/java/org/opensearch/sql/planner/PlanContext.java
  core/src/test/java/org/opensearch/sql/executor/QueryServiceTest.java
  core/src/test/java/org/opensearch/sql/executor/streaming/MicroBatchStreamingExecutionTest.java
  core/src/test/java/org/opensearch/sql/planner/PlanContextTest.java
Labels: enhancement

#1069 Integ tests fix for arm64.[Failure in starting up prometheus server]
  build.gradle
  doctest/build.gradle
  integ-test/build.gradle
Labels: bug, backport 2.4

#1084 Move DataSourceServiceImpl to core module
  core/src/main/java/org/opensearch/sql/datasource/DataSourceService.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceServiceImpl.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSource.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
  core/src/main/java/org/opensearch/sql/storage/DataSourceFactory.java
  core/src/main/java/org/opensearch/sql/storage/StorageEngineFactory.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/datasource/DataSourceServiceImplTest.java
  core/src/test/java/org/opensearch/sql/datasource/model/auth/AuthenticationTypeTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScanTest.java
  integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchDataSourceFactory.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchDataSourceFactoryTest.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  plugin/src/main/java/org/opensearch/sql/plugin/datasource/DataSourceServiceImpl.java
  plugin/src/test/java/org/opensearch/sql/plugin/datasource/DataSourceMetaDataTest.java
  plugin/src/test/java/org/opensearch/sql/plugin/datasource/DataSourceServiceImplTest.java
  plugin/src/test/resources/datasource_missing_name.json
  plugin/src/test/resources/duplicate_datasource_names.json
  plugin/src/test/resources/empty_datasource.json
  plugin/src/test/resources/illegal_datasource_name.json
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
Labels: maintenance

#1081 Add CBRT to the V2 engine
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement

#1068 Add Streaming Plan Impl
  core/build.gradle
  core/src/main/java/org/opensearch/sql/ast/statement/Query.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
  core/src/main/java/org/opensearch/sql/executor/DefaultQueryManager.java
  core/src/main/java/org/opensearch/sql/executor/ExecutionContext.java
  core/src/main/java/org/opensearch/sql/executor/ExecutionEngine.java
  core/src/main/java/org/opensearch/sql/executor/QueryManager.java
  core/src/main/java/org/opensearch/sql/executor/QueryService.java
  core/src/main/java/org/opensearch/sql/executor/execution/QueryPlan.java
  core/src/main/java/org/opensearch/sql/executor/execution/StreamingQueryPlan.java
  core/src/main/java/org/opensearch/sql/executor/streaming/MicroBatchStreamingExecution.java
  core/src/main/java/org/opensearch/sql/planner/physical/PhysicalPlan.java
  core/src/main/java/org/opensearch/sql/storage/Table.java
  core/src/test/java/org/opensearch/sql/executor/DefaultQueryManagerTest.java
  core/src/test/java/org/opensearch/sql/executor/QueryManagerTest.java
  core/src/test/java/org/opensearch/sql/executor/QueryServiceTest.java
  core/src/test/java/org/opensearch/sql/executor/execution/IntervalTriggerExecutionTest.java
  core/src/test/java/org/opensearch/sql/executor/execution/StreamingQueryPlanTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/PhysicalPlanTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableTest.java
  core/src/testFixtures/java/org/opensearch/sql/executor/DefaultExecutionEngine.java
  core/src/testFixtures/java/org/opensearch/sql/executor/DefaultQueryManager.java
  filesystem/build.gradle
  filesystem/src/testFixtures/java/org/opensearch/sql/filesystem/storage/FSDataSourceFactory.java
  filesystem/src/testFixtures/java/org/opensearch/sql/filesystem/storage/FSStorageEngine.java
  filesystem/src/testFixtures/java/org/opensearch/sql/filesystem/storage/FSTable.java
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/StreamingQueryIT.java
  integ-test/src/test/java/org/opensearch/sql/util/ExecuteOnCallerThreadQueryManager.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngine.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngineTest.java
  ppl/build.gradle
  ppl/src/test/java/org/opensearch/sql/ppl/PPLServiceTest.java
  sql/build.gradle
  sql/src/test/java/org/opensearch/sql/sql/SQLServiceTest.java
Labels: enhancement

#1077 Fix history file usage in SQL CLI tool.
  sql-cli/src/opensearch_sql_cli/conf/clirc
  sql-cli/src/opensearch_sql_cli/opensearchsql_cli.py
Labels: CLI

#1076 Add timeout option to SQL CLI tool.
  sql-cli/src/opensearch_sql_cli/main.py
  sql-cli/src/opensearch_sql_cli/opensearch_connection.py
  sql-cli/src/opensearch_sql_cli/opensearchsql_cli.py
  sql-cli/tests/test_opensearchsql_cli.py
Labels: CLI

#1099 Support opensearch-sql:run and update developer_guide doc
  .gitignore
  DEVELOPER_GUIDE.rst
  plugin/build.gradle
Labels: maintenance

#1090 Add Support For Legacy Syntax For Match Function In New Engine
  core/src/main/java/org/opensearch/sql/expression/function/OpenSearchFunctions.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/MatchIT.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchQueryTest.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: enhancement, legacy
