Repository opensearch-project/sql, pull requests merged in 2022-04, with the labels that each got.

#535 2.0 build fix
  build.gradle
Labels: v2.0.0

#527 Version Bump: spring-beans-5.2.19 -> spring-beans-5.2.20
  core/build.gradle
  plugin/build.gradle
  ppl/build.gradle
  sql/build.gradle
Labels: v2.0.0, security fix

#538 Bug Fix, return default ID when log4j ThreadContext is empty
  integ-test/src/test/java/org/opensearch/sql/legacy/JdbcTestIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/utils/LogUtils.java
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/utils/LogUtilsTest.java
Labels: v2.0.0, backport 1.x

#515 Support more parameters for AD and KMEANS command, and update related documentation
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/ast/tree/Kmeans.java
  core/src/main/java/org/opensearch/sql/planner/logical/LogicalMLCommons.java
  core/src/main/java/org/opensearch/sql/utils/MLCommonsConstants.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitorTest.java
  docs/user/ppl/cmd/ad.rst
  docs/user/ppl/cmd/kmeans.rst
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/ADOperator.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperator.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtectorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperatorTest.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/utils/ArgumentFactory.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
Labels: v2.0.0

#551 Change master nomenclature
  .github/workflows/sql-cli-release-workflow.yml
  .github/workflows/sql-jdbc-release-workflow.yml
  .github/workflows/sql-release-workflow.yml
  DEVELOPER_GUIDE.rst
  docs/attributions.md
  docs/dev/Architecture.md
  docs/dev/Doctest.md
  docs/presentations/20201116-sql-demo.md
  plugin/build.gradle
  sql-cli/README.md
  sql-jdbc/docs/tableau.md
  sql-odbc/THIRD-PARTY
  sql-odbc/docs/dev/run_tests.md
  workbench/CONTRIBUTING.md
Labels: SQL, v2.0.0

#568 bump ml-client to 2.0
  build.gradle
  opensearch/build.gradle
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/ADOperator.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperator.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperatorActions.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperatorTest.java
Labels: backport 2.0

#582 2.0.0.0-rc1 release notes
  release-notes/opensearch-sql.release-notes-2.0.0.0-rc1.md
Labels: backport 2.0

#588 Remove explicit node version for workbench
  .github/workflows/sql-workbench-test-and-build-workflow.yml
  workbench/package.json
Labels: backport 2.0
