Repository opensearch-project/sql, pull requests merged in 2023-07, with the labels that each got.

#1785 Add Flint describe index SQL support
  flint/flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint/flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlAstBuilder.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlCommand.scala
  flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSqlSuite.scala
Labels: enhancement, Flint

#1778 Add spark applicationId
  spark-sql-application/README.md
  spark-sql-application/src/main/scala/org/opensearch/sql/SQLJob.scala
  spark-sql-application/src/test/scala/org/opensearch/sql/SQLJobTest.scala
Labels: Flint

#1780 Add spark connector
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
  plugin/build.gradle
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  settings.gradle
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/client/SparkClient.java
  spark/src/main/java/org/opensearch/sql/spark/functions/implementation/SparkSqlFunctionImplementation.java
  spark/src/main/java/org/opensearch/sql/spark/functions/resolver/SparkSqlTableFunctionResolver.java
  spark/src/main/java/org/opensearch/sql/spark/functions/scan/SparkSqlFunctionTableScanBuilder.java
  spark/src/main/java/org/opensearch/sql/spark/request/SparkQueryRequest.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkStorageEngine.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkStorageFactory.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkTable.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionImplementationTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanBuilderTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlTableFunctionResolverTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageEngineTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageFactoryTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkTableTest.java
Labels: backport 2.x, Flint

#1814 Disable CCS IT test
  integ-test/build.gradle
Labels: backport 2.x

#1815 Guarantee datasource read api is strong consistent read
  datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
Labels: backport 2.x

#1825 Filter datasource encryption master key from cluster settings GET API
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  integ-test/src/test/java/org/opensearch/sql/datasource/DatasourceClusterSettingsIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
Labels: bug, backport 2.x

#1821 Support user-defined and incomplete date formats (#273)
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFormatsIT.java
  integ-test/src/test/resources/date_formats.json
  integ-test/src/test/resources/indexDefinitions/date_formats_index_mapping.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchDateType.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/data/type/OpenSearchDateTypeTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
Labels: backport 2.x, v2.9.0

#1771 Add _routing to SQL includes list (#277)
  docs/user/dql/basics.rst
  integ-test/src/test/java/org/opensearch/sql/sql/IdentifierIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/OpenSearchResponse.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchResponseTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexTest.java
Labels: backport 2.x, v2.9.0

#1807 Added new datetime functions and aliases to PPL
  docs/user/ppl/functions/datetime.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
Labels: backport 2.x

#1826 Update docs to reflect recent changes. (#285)
  docs/user/dql/expressions.rst
  docs/user/general/datatypes.rst
Labels: backport 2.x

#1829 Bump guava version to 32.0.1
  common/build.gradle
  core/build.gradle
  legacy/build.gradle
  ppl/build.gradle
  protocol/build.gradle
  sql/build.gradle
Labels: dependencies, backport 2.x, backport 2.9

#1790 Add EMR client to spark connector
  DEVELOPER_GUIDE.rst
  docs/user/ppl/admin/spark_connector.rst
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/client/EmrClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/main/java/org/opensearch/sql/spark/functions/response/DefaultSparkSqlFunctionResponseHandle.java
  spark/src/main/java/org/opensearch/sql/spark/functions/response/SparkSqlFunctionResponseHandle.java
  spark/src/main/java/org/opensearch/sql/spark/functions/scan/SparkSqlFunctionTableScanBuilder.java
  spark/src/main/java/org/opensearch/sql/spark/functions/scan/SparkSqlFunctionTableScanOperator.java
  spark/src/main/java/org/opensearch/sql/spark/helper/FlintHelper.java
  spark/src/main/java/org/opensearch/sql/spark/response/SparkResponse.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkScan.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkStorageFactory.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkTable.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionImplementationTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanBuilderTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanOperatorTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlTableFunctionResolverTest.java
  spark/src/test/java/org/opensearch/sql/spark/response/SparkResponseTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkScanTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageEngineTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageFactoryTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkTableTest.java
  spark/src/test/java/org/opensearch/sql/spark/utils/TestUtils.java
  spark/src/test/resources/all_data_type.json
  spark/src/test/resources/invalid_data_type.json
  spark/src/test/resources/invalid_response.json
  spark/src/test/resources/select_query_response.json
Labels: backport 2.x, Flint, backport 2.9

#1811 Backport https://github.com/opensearch-project/sql/pull/1753 to 2.x
  datasources/src/main/java/org/opensearch/sql/datasources/exceptions/ErrorMessage.java
  datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
Labels: backport 2.9

#1848 Bump `log4j` version.
  common/build.gradle
  integ-test/build.gradle
  ppl/build.gradle
Labels: backport 2.x

#1819 Provide hybrid scan setting for consistency requirement
  flint/docs/index.md
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndex.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndex.scala
  flint/flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala
  flint/flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndexSuite.scala
  flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSuite.scala
Labels: enhancement, Flint

#1803 Generate doc ID in build index job for idempotency
  flint/build.sbt
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  flint/flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala
  flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
Labels: enhancement, Flint

#1851 Remove Default master encryption key from settings.
  datasources/src/main/java/org/opensearch/sql/datasources/encryptor/EncryptorImpl.java
  datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
  datasources/src/test/java/org/opensearch/sql/datasources/encryptor/EncryptorImplTest.java
  docs/user/ppl/admin/datasources.rst
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
Labels: bug, backport 2.x, backport 2.9

#1856 Restrict master key config only to integTest cluster
  integ-test/build.gradle
Labels: bug

#1800 Add Flint create and refresh index SQL support
  flint/docs/index.md
  flint/flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint/flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/minmax/MinMaxSkippingStrategy.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/partition/PartitionSkippingStrategy.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/valueset/ValueSetSkippingStrategy.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlAstBuilder.scala
  flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
  flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSqlITSuite.scala
  flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSqlSuite.scala
Labels: enhancement, Flint

#1852 Added new datetime functions and aliases to PPL [Part 2]
  docs/user/ppl/functions/datetime.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/antlr/PPLSyntaxParserTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
Labels: backport 2.x

#1885 Fixed missing underscores in day_of_week doctest
  docs/user/ppl/functions/datetime.rst
Labels: backport 2.x

#1867 Change query range response structure
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
  integ-test/src/test/resources/expectedOutput/ppl/explain_query_range.json
  prometheus/src/main/java/org/opensearch/sql/prometheus/functions/response/DefaultQueryRangeFunctionResponseHandle.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/response/PrometheusResponse.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricScan.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTable.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/implementor/PrometheusDefaultImplementor.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/functions/scan/QueryRangeFunctionTableScanOperatorTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricScanTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTableTest.java
Labels: backport 2.x

#1888 Adding Spotless support framework
  DEVELOPER_GUIDE.rst
  build.gradle
Labels: backport 2.x

#1897 Statically init `typeActionMap` in `OpenSearchExprValueFactory`.
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
Labels: backport 2.x

#1894 Added support of timestamp/date/time using curly brackets
  docs/user/dql/expressions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/common/antlr/SyntaxParserTestBase.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/BracketedTimestampTest.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLParserTest.java
Labels: backport 2.x
