Repository opensearch-project/sql, pull requests merged in 2023-10, with the labels that each got.

#2175 Increment version to 2.11
  build.gradle
Labels: v2.11.0

#2187 Enable PPL lang and add datasource to async query API
  docs/user/interfaces/asyncqueryinterface.rst
  spark/build.gradle
  spark/src/main/antlr/FlintSparkSqlExtensions.g4
  spark/src/main/antlr/SparkSqlBase.g4
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryRequest.java
  spark/src/main/java/org/opensearch/sql/spark/rest/model/CreateAsyncQueryRequest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/transport/TransportCreateAsyncQueryRequestActionTest.java
Labels: enhancement, backport 2.x, Flint

#2156 Fix response codes returned by JSON formatting them
  core/src/main/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScan.java
  core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScanTest.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportUpdateDataSourceAction.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportUpdateDataSourceActionTest.java
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ShowDataSourcesCommandIT.java
Labels: backport 2.x, Flint, v2.11.0

#2190 Refactor Flint Auth
  datasources/src/main/java/org/opensearch/sql/datasources/auth/AuthenticationType.java
  datasources/src/main/java/org/opensearch/sql/datasources/glue/GlueDataSourceFactory.java
  datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
  datasources/src/test/java/org/opensearch/sql/datasources/glue/GlueDataSourceFactoryTest.java
  docs/user/ppl/admin/connectors/s3glue_connector.rst
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/S3GlueSparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: backport 2.x, Flint, v2.11.0

#2198 Bug fix, datasource API should be case sensitive
  datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
Labels: backport 2.x, v2.11.0

#2193 Add conf for spark structured streaming job
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/S3GlueSparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImplEMR.java
  spark/src/main/java/org/opensearch/sql/spark/client/StartJobRequest.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/client/StartJobRequestTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: backport 2.x, Flint, v2.11.0

#2208 Submit long running job only when auto_refresh = false
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexDetails.java
  spark/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  spark/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
Labels: backport 2.x, v2.11.0

#2211 Bug Fix, handle DESC TABLE response
  spark/src/main/java/org/opensearch/sql/spark/functions/response/DefaultSparkSqlFunctionResponseHandle.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanOperatorTest.java
  spark/src/test/resources/issue2210.json
Labels: backport 2.x, v2.11.0

#2204 Drop Index Implementation
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryResponse.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexDetails.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReader.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImpl.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexType.java
  spark/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/OpensearchAsyncQueryAsyncQueryJobMetadataStorageServiceTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImplTest.java
  spark/src/test/resources/flint-index-mappings/flint_my_glue_default_http_logs_size_year_covering_index.json
Labels: enhancement, backport 2.x, Flint

#2212 Add customized result index in data source etc
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScanTest.java
  datasources/src/main/java/org/opensearch/sql/datasources/utils/XContentParserUtils.java
  datasources/src/main/resources/datasources-index-mapping.yml
  datasources/src/test/java/org/opensearch/sql/datasources/service/DataSourceServiceImplTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/utils/XContentParserUtilsTest.java
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ShowDataSourcesCommandIT.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryExecutionResponse.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryResult.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImplEMR.java
  spark/src/main/java/org/opensearch/sql/spark/client/StartJobRequest.java
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryResponse.java
  spark/src/main/java/org/opensearch/sql/spark/response/JobExecutionResponseReader.java
  spark/src/main/java/org/opensearch/sql/spark/transport/TransportGetAsyncQueryResultAction.java
  spark/src/main/java/org/opensearch/sql/spark/transport/format/AsyncQueryResultResponseFormatter.java
  spark/src/main/resources/job-metadata-index-mapping.yml
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/OpensearchAsyncQueryAsyncQueryJobMetadataStorageServiceTest.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/client/StartJobRequestTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/response/AsyncQueryExecutionResponseReaderTest.java
  spark/src/test/java/org/opensearch/sql/spark/transport/TransportGetAsyncQueryResultActionTest.java
  spark/src/test/java/org/opensearch/sql/spark/transport/format/AsyncQueryResultResponseFormatterTest.java
Labels: backport 2.x, v2.11.0

#2215 Enable PPL Queries
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: enhancement, backport 2.x, Flint

#2226 Minor fix in dropping covering index
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClient.java
  spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImpl.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexType.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
Labels: bug, backport 2.x, Flint, v2.11.0

#2227 Correctly Set query status
  docs/user/ppl/admin/connectors/s3glue_connector.rst
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/response/JobExecutionResponseReader.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/response/AsyncQueryExecutionResponseReaderTest.java
Labels: bug, backport 2.x, Flint, v2.11.0

#2229 Add documentation for S3GlueConnector.
  docs/user/interfaces/asyncqueryinterface.rst
  docs/user/ppl/admin/connectors/s3glue_connector.rst
Labels: documentation, backport 2.x, Flint, v2.11.0, backport 2.11

#2219 Read extra Spark submit parameters from cluster settings
  opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfig.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryRequest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParametersTest.java
  spark/src/test/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: enhancement, backport 2.x, backport 2.11

#2238 Fix Unit tests for FlintIndexReader
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImpl.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexType.java
  spark/src/test/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImplTest.java
  spark/src/test/resources/flint-index-mappings/flint_my_glue_default_http_logs_size_year_covering_index.json
  spark/src/test/resources/flint-index-mappings/flint_mys3_default_http_logs_cv1_index.json
  spark/src/test/resources/flint-index-mappings/flint_mys3_default_http_logs_skipping_index.json
  spark/src/test/resources/flint-index-mappings/npe_mapping.json
Labels: bug, backport 2.x, Flint, backport 2.11

#2250 Bug Fix , delete OpenSearch index when DROP INDEX
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/OpensearchAsyncQueryJobMetadataStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexDetails.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReader.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImpl.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/DropIndexResultTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/FlintIndexMetadataTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/IndexDetailsTest.java
Labels: backport 2.x, backport 2.11

#2249 Spark Execution Engine Config Refactor
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfig.java
  spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSetting.java
  spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigSupplier.java
  spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigSupplierImpl.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSettingTest.java
  spark/src/test/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigSupplierImplTest.java
Labels: backport 2.x, maintenance, Flint, backport 2.11

#2276 Provide auth.type and auth.role_arn paramters in GET Datasource API response.
  datasources/src/main/java/org/opensearch/sql/datasources/service/DataSourceServiceImpl.java
  datasources/src/test/java/org/opensearch/sql/datasources/service/DataSourceServiceImplTest.java
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
Labels: bug, backport 2.x, Flint

#2284 release-notes-2.11
  release-notes/opensearch-sql.release-notes-2.11.0.0.md
Labels: backport 2.x, backport 2.11

#2290 add InteractiveSession and SessionManager
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/execution/session/CreateSessionRequest.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/Session.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionId.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionState.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionType.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/SessionStateStore.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionStateTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionTypeTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statestore/SessionStateStoreTest.java
Labels: backport 2.x

#2307 Upgrade JSON to 20231013 to fix CVE-2023-5072
  legacy/build.gradle
  opensearch/build.gradle
  ppl/build.gradle
  prometheus/build.gradle
  spark/build.gradle
  sql/build.gradle
Labels: backport 2.x, backport 2.11

#2308 Refactoring in Unit Tests
  spark/src/main/antlr/SqlBaseParser.g4
  spark/src/main/java/org/opensearch/sql/spark/client/StartJobRequest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: backport 2.x, maintenance, backport 2.11

#2294 Add Statement
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/Session.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionState.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/QueryRequest.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementId.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementState.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/SessionStateStore.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementStateTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statestore/SessionStateStoreTest.java
Labels: backport 2.x, Flint

#2312 Add sessionId parameters for create async query API
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  docs/user/admin/settings.rst
  docs/user/interfaces/asyncqueryinterface.rst
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryExecutionResponse.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryRequest.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryResponse.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionId.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementId.java
  spark/src/main/java/org/opensearch/sql/spark/rest/model/CreateAsyncQueryRequest.java
  spark/src/main/java/org/opensearch/sql/spark/rest/model/CreateAsyncQueryResponse.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
  spark/src/test/java/org/opensearch/sql/spark/rest/model/CreateAsyncQueryRequestTest.java
  spark/src/test/java/org/opensearch/sql/spark/transport/TransportCreateAsyncQueryRequestActionTest.java
  spark/src/test/java/org/opensearch/sql/spark/transport/TransportGetAsyncQueryResultActionTest.java
Labels: backport 2.x

#2273 Implement patch API for datasources
  core/src/main/java/org/opensearch/sql/datasource/DataSourceService.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  datasources/src/main/java/org/opensearch/sql/datasources/model/transport/PatchDataSourceActionRequest.java
  datasources/src/main/java/org/opensearch/sql/datasources/model/transport/PatchDataSourceActionResponse.java
  datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/service/DataSourceServiceImpl.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportPatchDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/utils/XContentParserUtils.java
  datasources/src/test/java/org/opensearch/sql/datasources/service/DataSourceServiceImplTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportPatchDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/utils/XContentParserUtilsTest.java
  docs/user/ppl/admin/datasources.rst
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
Labels: enhancement, backport 2.x, backport 2.11

#2327 Integration with REPL Spark job
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/CreateSessionRequest.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionId.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionState.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionType.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementState.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  spark/src/main/java/org/opensearch/sql/spark/response/JobExecutionResponseReader.java
  spark/src/main/resources/query_execution_request_mapping.yml
  spark/src/main/resources/query_execution_request_settings.yml
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
Labels: backport 2.x, Flint

#2339 deprecated job-metadata-index
  common/build.gradle
  integ-test/build.gradle
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  ppl/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/OpensearchAsyncQueryJobMetadataStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryId.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/AsyncQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryResponse.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionId.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/QueryRequest.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementId.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  spark/src/main/java/org/opensearch/sql/spark/utils/IDUtils.java
  spark/src/main/resources/job-metadata-index-mapping.yml
  spark/src/main/resources/job-metadata-index-settings.yml
  spark/src/main/resources/query_execution_request_mapping.yml
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/OpensearchAsyncQueryAsyncQueryJobMetadataStorageServiceTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
Labels: backport 2.x, backport 2.11

#2336 Add missing tags and MV support
  common/build.gradle
  integ-test/build.gradle
  ppl/build.gradle
  spark/src/main/antlr/FlintSparkSqlExtensions.g4
  spark/src/main/antlr/SparkSqlBase.g4
  spark/src/main/antlr/SqlBaseLexer.g4
  spark/src/main/antlr/SqlBaseParser.g4
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexDetails.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/JobType.java
  spark/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/IndexDetailsTest.java
  spark/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
Labels: backport 2.x, backport 2.11

#2357 Handle Describe,Refresh and Show Queries Properly
  spark/src/main/antlr/FlintSparkSqlExtensions.g4
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryActionType.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryDetails.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReader.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImpl.java
  spark/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/IndexQueryDetailsTest.java
  spark/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
Labels: bug, backport 2.x, backport 2.11

#2373 Enable session by default
  docs/user/admin/settings.rst
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
Labels: backport 2.x, backport 2.11

#2383 Refactoring for tags usage in test files.
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: bug, backport 2.x, backport 2.11

#2372 Add Flint Index Purging Logic
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScanTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/service/DataSourceServiceImplTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/utils/XContentParserUtilsTest.java
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ShowDataSourcesCommandIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/client/EmrClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/cluster/ClusterManagerEventListener.java
  spark/src/main/java/org/opensearch/sql/spark/cluster/FlintIndexRetention.java
  spark/src/main/java/org/opensearch/sql/spark/cluster/IndexCleanup.java
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/main/java/org/opensearch/sql/spark/response/JobExecutionResponseReader.java
  spark/src/main/java/org/opensearch/sql/spark/response/SparkResponse.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/response/AsyncQueryExecutionResponseReaderTest.java
  spark/src/test/java/org/opensearch/sql/spark/response/SparkResponseTest.java
Labels: enhancement, backport 2.x, backport 2.11

#2390 add concurrent limit on datasource and sessions
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  datasources/build.gradle
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceAction.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceActionTest.java
  docs/user/admin/settings.rst
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/AsyncQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryContext.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  spark/src/main/java/org/opensearch/sql/spark/leasemanager/ConcurrencyLimitExceededException.java
  spark/src/main/java/org/opensearch/sql/spark/leasemanager/DefaultLeaseManager.java
  spark/src/main/java/org/opensearch/sql/spark/leasemanager/LeaseManager.java
  spark/src/main/java/org/opensearch/sql/spark/leasemanager/model/LeaseRequest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/leasemanager/DefaultLeaseManagerTest.java
Labels: backport 2.x, backport 2.11

#2386 Redefine Drop Index as logical delete
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  docs/user/admin/settings.rst
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/AsyncQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryResponse.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexDMLResult.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexState.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexStateModel.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpCancel.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpDelete.java
  spark/src/main/java/org/opensearch/sql/spark/functions/response/DefaultSparkSqlFunctionResponseHandle.java
  spark/src/main/java/org/opensearch/sql/spark/leasemanager/DefaultLeaseManager.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/OpensearchAsyncQueryAsyncQueryJobMetadataStorageServiceTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/DropIndexResultTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/FlintIndexStateTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpTest.java
  spark/src/test/java/org/opensearch/sql/spark/leasemanager/DefaultLeaseManagerTest.java
  spark/src/test/resources/flint-index-mappings/0.1.1/flint_covering_index.json
  spark/src/test/resources/flint-index-mappings/0.1.1/flint_mv.json
  spark/src/test/resources/flint-index-mappings/0.1.1/flint_skipping_index.json
  spark/src/test/resources/flint-index-mappings/flint_covering_index.json
  spark/src/test/resources/flint-index-mappings/flint_mv.json
  spark/src/test/resources/flint-index-mappings/flint_skipping_index.json
  spark/src/test/resources/query_execution_result_mapping.json
Labels: backport 2.x, backport 2.11

#2398 Added session, statement, emrjob metrics to sql stats api
  datasources/build.gradle
  datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportDeleteDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportPatchDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportUpdateDataSourceAction.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportDeleteDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportPatchDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportUpdateDataSourceActionTest.java
  legacy/src/main/java/org/opensearch/sql/legacy/metrics/MetricFactory.java
  legacy/src/main/java/org/opensearch/sql/legacy/metrics/MetricName.java
  legacy/src/main/java/org/opensearch/sql/legacy/utils/MetricUtils.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
Labels: backport 2.x, backport 2.11
