Repository opensearch-project/sql, pull requests merged in 2023-09, with the labels that each got.

#2043 bump okhttp to 4.10.0
  integ-test/build.gradle
  plugin/build.gradle
Labels: backport 2.x

#2051 add 2.10 release notes
  release-notes/opensearch-sql.release-notes-2.10.0.0.md
Labels: backport 2.x, backport main

#2056 bump aws-encryption-sdk-java to 1.71
  datasources/build.gradle
Labels: backport 2.x

#2042 Changed allowlist config to denylist ip config for datasource uri hosts
  common/build.gradle
  common/src/main/java/org/opensearch/sql/common/interceptors/AwsSigningInterceptor.java
  common/src/main/java/org/opensearch/sql/common/interceptors/BasicAuthenticationInterceptor.java
  common/src/main/java/org/opensearch/sql/common/interceptors/URIValidatorInterceptor.java
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  common/src/main/java/org/opensearch/sql/common/utils/URIValidationUtils.java
  common/src/test/java/org/opensearch/sql/common/interceptors/AwsSigningInterceptorTest.java
  common/src/test/java/org/opensearch/sql/common/interceptors/BasicAuthenticationInterceptorTest.java
  datasources/build.gradle
  datasources/src/main/java/org/opensearch/sql/datasources/utils/DatasourceValidationUtils.java
  datasources/src/test/java/org/opensearch/sql/datasources/utils/DatasourceValidationUtilsTest.java
  docs/user/ppl/admin/datasources.rst
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  prometheus/build.gradle
  prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/client/PrometheusClientImplTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
Labels: bug, backport 2.x

#2060 Always use snapshot version for security plugin download
  build.gradle
  integ-test/build.gradle
Labels: bug, backport 2.x, backport 2.10

#2065 Check for existence of security plugin
  integ-test/build.gradle
Labels: bug, infrastructure, backport 2.x

#2050 Initial commit of new job APIs
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/rest/RestJobManagementAction.java
  spark/src/main/java/org/opensearch/sql/spark/rest/model/CreateJobRequest.java
  spark/src/main/java/org/opensearch/sql/spark/transport/TransportCreateJobRequestAction.java
  spark/src/main/java/org/opensearch/sql/spark/transport/TransportDeleteJobRequestAction.java
  spark/src/main/java/org/opensearch/sql/spark/transport/TransportGetJobRequestAction.java
  spark/src/main/java/org/opensearch/sql/spark/transport/TransportGetQueryResultRequestAction.java
  spark/src/main/java/org/opensearch/sql/spark/transport/model/CreateJobActionRequest.java
  spark/src/main/java/org/opensearch/sql/spark/transport/model/CreateJobActionResponse.java
  spark/src/main/java/org/opensearch/sql/spark/transport/model/DeleteJobActionRequest.java
  spark/src/main/java/org/opensearch/sql/spark/transport/model/DeleteJobActionResponse.java
  spark/src/main/java/org/opensearch/sql/spark/transport/model/GetJobActionRequest.java
  spark/src/main/java/org/opensearch/sql/spark/transport/model/GetJobActionResponse.java
  spark/src/main/java/org/opensearch/sql/spark/transport/model/GetJobQueryResultActionRequest.java
  spark/src/main/java/org/opensearch/sql/spark/transport/model/GetJobQueryResultActionResponse.java
  spark/src/test/java/org/opensearch/sql/spark/transport/TransportCreateJobRequestActionTest.java
  spark/src/test/java/org/opensearch/sql/spark/transport/TransportDeleteJobRequestActionTest.java
  spark/src/test/java/org/opensearch/sql/spark/transport/TransportGetJobRequestActionTest.java
  spark/src/test/java/org/opensearch/sql/spark/transport/TransportGetQueryResultRequestActionTest.java
  spark/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: enhancement

#2128 Fix mockito core conflict.
  plugin/build.gradle
Labels: maintenance

#2130 Removed Domain Validation
  datasources/src/main/java/org/opensearch/sql/datasources/utils/DatasourceValidationUtils.java
  datasources/src/test/java/org/opensearch/sql/datasources/utils/DatasourceValidationUtilsTest.java
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
Labels: bug, backport 2.x

#2150 Add tags to the emr jobs created based on the query.
  docs/user/interfaces/asyncqueryinterface.rst
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/build.gradle
  spark/src/main/antlr/FlintSparkSqlExtensions.g4
  spark/src/main/antlr/SparkSqlBase.g4
  spark/src/main/antlr/SqlBaseLexer.g4
  spark/src/main/antlr/SqlBaseParser.g4
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClient.java
  spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImplEMR.java
  spark/src/main/java/org/opensearch/sql/spark/client/SparkJobClient.java
  spark/src/main/java/org/opensearch/sql/spark/client/StartJobRequest.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryRequest.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/FullyQualifiedTableName.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexDetails.java
  spark/src/main/java/org/opensearch/sql/spark/rest/model/CreateAsyncQueryRequest.java
  spark/src/main/java/org/opensearch/sql/spark/rest/model/LangType.java
  spark/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/transport/TransportCreateAsyncQueryRequestActionTest.java
  spark/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
Labels: enhancement, Flint, v2.11.0
