Repository opensearch-project/sql, pull requests merged in 2023-11, with the labels that each got.

#2404 Onboard jenkins prod docker images in github actions
  .github/workflows/dco.yml
  .github/workflows/integ-tests-with-security.yml
  .github/workflows/sql-pitest.yml
  .github/workflows/sql-test-and-build-workflow.yml
  .github/workflows/sql-test-workflow.yml
Labels: enhancement, backport 2.x

#2406 [Backport 2.x] Onboard jenkins prod docker images to github actions
  .github/workflows/dco.yml
  .github/workflows/integ-tests-with-security.yml
  .github/workflows/sql-test-and-build-workflow.yml
Labels: enhancement

#2407 Block execution engine settings in sql query settings API and add more unit tests
  docs/user/admin/settings.rst
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java
Labels: backport 2.x, backport 2.11

#2405 upgrade okhttp to 4.12.0
  build.gradle
  common/build.gradle
  integ-test/build.gradle
  plugin/build.gradle
  prometheus/build.gradle
Labels: backport 2.x

#2422 Add more metrics and handle emr exception message
  datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportDeleteDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportPatchDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportUpdateDataSourceAction.java
  legacy/src/main/java/org/opensearch/sql/legacy/metrics/MetricName.java
  spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/rest/RestAsyncQueryManagementAction.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
Labels: backport 2.x, backport 2.11

#2428 Return 429 for ConcurrencyLimitExceededException
  datasources/src/main/java/org/opensearch/sql/datasources/exceptions/ErrorMessage.java
  datasources/src/test/java/org/opensearch/sql/datasources/exceptions/ErrorMessageTest.java
  spark/src/main/java/org/opensearch/sql/spark/rest/RestAsyncQueryManagementAction.java
Labels: backport 2.x
