Repository opensearch-project/sql, pull requests merged in 2023-02, with the labels that each got.

#1298 Added Correctness Tests For Date And Time Functions
  integ-test/src/test/resources/correctness/expressions/date_and_time_functions.txt
Labels: infrastructure, backport 2.x

#1320 Fix ArgumentCaptor can't capture varargs
  integ-test/build.gradle
  plugin/src/test/java/org/opensearch/sql/plugin/datasource/DataSourceMetaDataTest.java
Labels: infrastructure, backport 2.x

#1319 Add more keywords as identifier in PPL
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
Labels: enhancement, backport 2.x, backport 2.5

#1182 Update `DATE_ADD`/`ADDDATE` and `DATE_SUB`/`SUBDATE` functions. (#122)
  core/src/main/java/org/opensearch/sql/data/model/ExprValueUtils.java
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/datetime/IntervalClause.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateAddAndAddDateTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateSubAndSubDateTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java
  core/src/test/java/org/opensearch/sql/expression/datetime/IntervalClauseTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/datetime.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
Labels: enhancement, backport 2.x

#1206 Escape character support for string literals
  common/src/main/java/org/opensearch/sql/common/utils/StringUtils.java
  core/src/test/java/org/opensearch/sql/common/utils/StringUtilsTest.java
  docs/user/dql/expressions.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/MultiMatchIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/QueryStringIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/SimpleQueryStringIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/MultiMatchIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/QueryStringIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/SimpleQueryStringIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/StringLiteralIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/WildcardQueryIT.java
Labels: enhancement, breaking, v3.0.0

#1330 Create custom integ test file for sql plugin.
  scripts/integtest.sh
Labels: infrastructure, backport 2.x, backport 2.5

#1254 Update `TIMESTAMP` function implementation and signatures.
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java
  core/src/test/java/org/opensearch/sql/expression/datetime/TimestampTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/datetime.rst
Labels: enhancement, backport 2.x

#1338 Added untriaged issue workflow.
  .github/workflows/add-untriaged.yml
Labels: infrastructure

#1299 Add `GET_FORMAT` Function To OpenSearch SQL Plugin
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: enhancement, backport 2.x

#1341 Modified returning NaN to NULL
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
Labels: backport 2.x

#1301 Add `TIME_FORMAT()` Function To SQL Plugin
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFormatterUtil.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/datetime.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement, backport 2.x

#1343 Support More Formats For `GET_FORMAT` Function
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
Labels: enhancement

#1344 Add `last_day` Function To OpenSearch SQL Plugin
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement, backport 2.x

#1345 Add WeekOfYear Function To OpenSearch
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement, backport 2.x

#1353 Fix index not found reported as server error bug
  integ-test/src/test/java/org/opensearch/sql/ppl/PPLPluginIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
Labels: bug, backport 2.x, backport 2.5

#1347 [Backport 2.x] Modified returning NaN to NULL
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
Labels: bug

#1359 Add publish snapshots to maven via GHA
  .github/workflows/link-checker.yml
  .github/workflows/maven-publish.yml
  plugin/build.gradle
Labels: infrastructure, backport 2.x

#1367 Add release notes for 2.6.0
  release-notes/opensearch-sql.release-notes-2.6.0.0.md
Labels: release, backport 2.x, backport 2.6

#1380 Exclude OpenSearch system index when IT cleanup
  integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java
Labels: bug, infrastructure, backport 2.x, backport main
