Repository opensearch-project/sql, pull requests merged in 2023-08, with the labels that each got.

#1919 Fixed refactored imports
  opensearch/src/main/java/org/opensearch/sql/opensearch/monitor/OpenSearchResourceMonitor.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/LegacyOpenDistroSettings.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/monitor/OpenSearchResourceMonitorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
Labels: backport 2.x

#1896 [Spotless] Adds new line at end of java files
  build.gradle
  common/src/main/java/org/opensearch/sql/common/grok/Converter.java
  core/src/main/java/org/opensearch/sql/ast/tree/RareTopN.java
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/ArithmeticFunction.java
  core/src/main/java/org/opensearch/sql/expression/text/TextFunction.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalRelationTest.java
  core/src/test/java/org/opensearch/sql/planner/streaming/watermark/BoundedOutOfOrderWatermarkGeneratorTest.java
  core/src/test/java/org/opensearch/sql/planner/streaming/windowing/WindowTest.java
  core/src/test/java/org/opensearch/sql/planner/streaming/windowing/assigner/SlidingWindowAssignerTest.java
  core/src/test/java/org/opensearch/sql/planner/streaming/windowing/assigner/TumblingWindowAssignerTest.java
  core/src/test/java/org/opensearch/sql/planner/streaming/windowing/trigger/AfterWatermarkWindowTriggerTest.java
  core/src/test/java/org/opensearch/sql/storage/write/TableWriteOperatorTest.java
  datasources/src/main/java/org/opensearch/sql/datasources/encryptor/Encryptor.java
  datasources/src/main/java/org/opensearch/sql/datasources/encryptor/EncryptorImpl.java
  datasources/src/main/java/org/opensearch/sql/datasources/model/transport/CreateDataSourceActionRequest.java
  datasources/src/main/java/org/opensearch/sql/datasources/model/transport/CreateDataSourceActionResponse.java
  datasources/src/main/java/org/opensearch/sql/datasources/model/transport/DeleteDataSourceActionRequest.java
  datasources/src/main/java/org/opensearch/sql/datasources/model/transport/DeleteDataSourceActionResponse.java
  datasources/src/main/java/org/opensearch/sql/datasources/model/transport/GetDataSourceActionRequest.java
  datasources/src/main/java/org/opensearch/sql/datasources/model/transport/GetDataSourceActionResponse.java
  datasources/src/main/java/org/opensearch/sql/datasources/model/transport/UpdateDataSourceActionRequest.java
  datasources/src/main/java/org/opensearch/sql/datasources/model/transport/UpdateDataSourceActionResponse.java
  datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/service/DataSourceMetadataStorage.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportDeleteDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportUpdateDataSourceAction.java
  datasources/src/main/java/org/opensearch/sql/datasources/utils/Scheduler.java
  datasources/src/test/java/org/opensearch/sql/datasources/encryptor/EncryptorImplTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportDeleteDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportUpdateDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/utils/SchedulerTest.java
  legacy/src/main/java/org/opensearch/sql/legacy/domain/Select.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/format/BindingTupleResultSet.java
  legacy/src/main/java/org/opensearch/sql/legacy/parser/SQLOdbcExpr.java
  legacy/src/main/java/org/opensearch/sql/legacy/rewriter/nestedfield/NestedFieldRewriter.java
  legacy/src/main/java/org/opensearch/sql/legacy/spatial/CellFilterParams.java
  legacy/src/test/java/org/opensearch/sql/legacy/antlr/semantic/SemanticAnalyzerBasicTest.java
  legacy/src/test/java/org/opensearch/sql/legacy/query/planner/physical/node/scroll/SearchHitRowTest.java
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/HavingTest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperator.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/MLOperator.java
  ppl/src/test/java/org/opensearch/sql/ppl/antlr/NowLikeFunctionParserTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/antlr/PPLSyntaxParserTest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTable.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/implementor/PrometheusDefaultImplementor.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/StepParameterResolver.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/functions/implementation/QueryExemplarsFunctionImplementationTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/functions/resolver/QueryExemplarsTableFunctionResolverTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/functions/scan/QueryExemplarsFunctionTableScanOperatorTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/QueryExemplarsTableTest.java
  spark/src/test/java/org/opensearch/sql/spark/utils/TestUtils.java
Labels: backport 2.x

#1928 Fix CVE
  integ-test/build.gradle
Labels: backport 2.x

#1937 (#1536) Refactor OpenSearchQueryRequest and move includes to builder
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequestTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequestTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanTest.java
Labels: backport 2.x

#1947 Add release notes for 1.3.12
  release-notes/opensearch-sql.release-notes-1.3.12.0.md
Labels: backport 2.x, backport main

#1952 Update backport CI, add PR merged condition
  .github/workflows/backport.yml
Labels: backport 2.x

#1957 Okio upgrade to 3.5.0
  build.gradle
Labels: backport 2.x

#1936 (#1506) Remove reservedSymbolTable and replace with HIDDEN_FIELD_NAME
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
  core/src/main/java/org/opensearch/sql/analysis/TypeEnvironment.java
  core/src/main/java/org/opensearch/sql/analysis/symbol/Namespace.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
Labels: backport 2.x

#1902 Fix doctest data
  doctest/test_data/nested_objects.json
  doctest/test_data/wildcard.json
Labels: backport 2.x

#1976 Add support for `date_nanos` and tests. (#337)
  integ-test/src/test/java/org/opensearch/sql/ppl/DataTypeIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/SystemFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFormatsIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/SystemFunctionIT.java
  integ-test/src/test/resources/datatypes.json
  integ-test/src/test/resources/date_formats.json
  integ-test/src/test/resources/indexDefinitions/datatypes_index_mapping.json
  integ-test/src/test/resources/indexDefinitions/date_formats_index_mapping.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataType.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataTypeTest.java
Labels: backport 2.x

#1986 Run IT tests with security plugin (#335)
  .github/workflows/integ-tests-with-security.yml
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java
  integ-test/src/test/java/org/opensearch/sql/security/CrossClusterSearchIT.java
Labels: backport 2.x

#2000 Developer guide update with Spotless details
  DEVELOPER_GUIDE.rst
Labels: backport 2.x

#2006 Fixed exception when datasource is updated with existing configuration.
  datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
  datasources/src/test/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorageTest.java
Labels: bug, backport 2.x, backport 2.9

#2021 [Spotless] Exclude generated files from spotless
  build.gradle
Labels: backport 2.x

#2013 Revert "Guarantee datasource read api is strong consistent read (#1815)"
  datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
Labels: backport 2.x

#2033 Fixed response codes For Requests With security exception.
  datasources/src/main/java/org/opensearch/sql/datasources/exceptions/DataSourceClientException.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLQueryAction.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/exceptions/PrometheusClientException.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/request/system/PrometheusDescribeMetricRequest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/client/PrometheusClientImplTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
  prometheus/src/test/resources/non_json_response.json
Labels: bug, backport 2.x, backport 2.9
