Repository opensearch-project/sql, pull requests merged in 2023-06, with the labels that each got.

#1690 Query rewrite for partition skipping index
  flint/docs/index.md
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkExtensions.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkOptimizer.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndex.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndex.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/partition/PartitionSkippingStrategy.scala
  flint/flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala
  flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSuite.scala
  flint/project/Dependencies.scala
Labels: enhancement, Flint

#1699 add flint date type support
  flint/docs/index.md
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionReader.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionReaderFactory.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionWriter.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintTable.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintWrite.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintWriteBuilder.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonParser.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/storage/FlintQueryCompiler.scala
  flint/flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
  flint/integ-test/src/test/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala
Labels: Flint

#1703 Moved auth interceptors to common module
  build.gradle
  common/build.gradle
  common/src/main/java/org/opensearch/sql/common/authinterceptors/AwsSigningInterceptor.java
  common/src/main/java/org/opensearch/sql/common/authinterceptors/BasicAuthenticationInterceptor.java
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  common/src/test/java/org/opensearch/sql/common/authinterceptors/AwsSigningInterceptorTest.java
  common/src/test/java/org/opensearch/sql/common/authinterceptors/BasicAuthenticationInterceptorTest.java
  datasources/src/main/java/org/opensearch/sql/datasources/settings/DataSourceSettings.java
  docs/user/ppl/admin/datasources.rst
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  legacy/src/test/java/org/opensearch/sql/legacy/executor/AsyncRestExecutorTest.java
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/LocalClusterStateTest.java
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/planner/QueryPlannerTest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
  plugin/build.gradle
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  prometheus/build.gradle
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
Labels: backport 2.x

#1708 Add value set skipping index
  flint/docs/index.md
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndex.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/partition/PartitionSkippingStrategy.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/valueset/ValueSetSkippingStrategy.scala
  flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSuite.scala
Labels: enhancement, Flint

#1716 Fixed bug of byte/short not handling 0 denominator in divide/modulus equations
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/ArithmeticFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/ArithmeticFunctionTest.java
Labels: backport 2.x

#1500 Pagination Phase 2: Support `WHERE` clause, column list in `SELECT` clause and for functions and expressions in the query.
  core/src/main/java/org/opensearch/sql/ast/expression/Cast.java
  core/src/main/java/org/opensearch/sql/executor/pagination/CanPaginateVisitor.java
  core/src/test/java/org/opensearch/sql/executor/pagination/CanPaginateVisitorTest.java
  integ-test/src/test/java/org/opensearch/sql/legacy/CursorIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/LegacyAPICompatibilityIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/PaginationFallbackIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/PaginationFilterIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/PaginationIT.java
  integ-test/src/test/java/org/opensearch/sql/util/TestUtils.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequestTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchDefaultImplementorTest.java
Labels: backport 2.x, pagination

#1738 Simplify OpenSearchIndexScanBuilder (#275)
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanBuilder.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanOptimizationTest.java
Labels: backport 2.x

#1719 Enable Table Function and PromQL function
  docs/user/ppl/admin/prometheus_connector.rst
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/functions/response/DefaultQueryRangeFunctionResponseHandle.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/functions/response/QueryRangeFunctionResponseHandle.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/functions/scan/QueryRangeFunctionTableScanBuilder.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/functions/scan/QueryRangeFunctionTableScanOperator.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/response/PrometheusResponse.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTable.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/functions/scan/QueryRangeFunctionTableScanBuilderTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/functions/scan/QueryRangeFunctionTableScanOperatorTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTableTest.java
Labels: backport 2.x

#1599 Pagination Phase 2: Support `ORDER BY` clauses and queries without `FROM`.
  core/src/main/java/org/opensearch/sql/executor/pagination/CanPaginateVisitor.java
  core/src/main/java/org/opensearch/sql/planner/DefaultImplementor.java
  core/src/test/java/org/opensearch/sql/executor/pagination/CanPaginateVisitorTest.java
  core/src/test/java/org/opensearch/sql/planner/DefaultImplementorTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/PhysicalPlanTestBase.java
  integ-test/src/test/java/org/opensearch/sql/legacy/CursorIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/PaginationFallbackIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/PaginationIT.java
Labels: pagination

#1727 enhance flint spark configuration
  flint/docs/index.md
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionReader.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionWriter.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintConfig.scala
  flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkOptimizer.scala
  flint/flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala
  flint/flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
  flint/integ-test/src/test/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala
  flint/integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
Labels: enhancement, Flint

#1753 Improved error codes in case of security exception
  datasources/src/main/java/org/opensearch/sql/datasources/exceptions/ErrorMessage.java
  datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
Labels: backport 2.x

#1730 Add Flint drop index SQL support
  flint/build.sbt
  flint/flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
  flint/flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkExtensions.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlAstBuilder.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlCommand.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlParser.scala
  flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSqlSuite.scala
  flint/project/plugins.sbt
Labels: enhancement, Flint

#1747 Stop prometheus in doctest build.gradle now runs upon project failure in startOpenSearch
  doctest/build.gradle
Labels: backport 2.x

#1760 Fix CI
  plugin/build.gradle
Labels: backport 2.x

#1768 Fixing CVE 1767
  build.gradle
  integ-test/build.gradle
  plugin/build.gradle
Labels: backport 2.x

#1725 Updated documentation of round function return type
  docs/user/dql/functions.rst
Labels: backport 2.x

#1723 Add Spark application
  spark-sql-application/.gitignore
  spark-sql-application/README.md
  spark-sql-application/build.sbt
  spark-sql-application/project/build.properties
  spark-sql-application/project/plugins.sbt
  spark-sql-application/scalastyle-config.xml
  spark-sql-application/src/main/scala/org/opensearch/sql/SQLJob.scala
  spark-sql-application/src/test/scala/org/opensearch/sql/SQLJobTest.scala
Labels: enhancement, Flint

#1667 Update sqlite-jdbc to 3.41.2.2 to address CVE-2023-32697
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/correctness/runner/resultset/DBResult.java
Labels: backport 1.3, backport 2.x

#1737 Support Array and ExprValue Parsing With Inner Hits
  integ-test/src/test/java/org/opensearch/sql/legacy/ObjectFieldSelectIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/NestedIT.java
  integ-test/src/test/resources/indexDefinitions/nested_simple_index_mapping.json
  integ-test/src/test/resources/nested_simple.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/Content.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/ObjectContent.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContent.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/OpenSearchResponse.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/core/ExpressionScript.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchResponseTest.java
Labels: backport 2.x

#1789 Add Support for Nested Function in Order By Clause
  core/src/main/java/org/opensearch/sql/analysis/NestedAnalyzer.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/NestedIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LuceneQuery.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/sort/SortQueryBuilder.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanOptimizationTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/sort/SortQueryBuilderTest.java
  sql/src/main/java/org/opensearch/sql/sql/parser/AstSortBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
Labels: backport 2.x

#1779 Fix CSV/RAW output header being application/json rather than plain/text
  integ-test/src/test/java/org/opensearch/sql/sql/CsvFormatIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/RawFormatIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/SimpleQueryStringIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSQLQueryAction.java
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseFormatter.java
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/JsonResponseFormatter.java
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/ResponseFormatter.java
  protocol/src/test/java/org/opensearch/sql/protocol/response/format/CommandResponseFormatterTest.java
  protocol/src/test/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatterTest.java
  protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java
  protocol/src/test/java/org/opensearch/sql/protocol/response/format/VisualizationResponseFormatterTest.java
Labels: backport 2.x

#1773 Add Support for Field Star in Nested Function
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
  core/src/main/java/org/opensearch/sql/analysis/NestedAnalyzer.java
  core/src/main/java/org/opensearch/sql/analysis/SelectExpressionAnalyzer.java
  core/src/main/java/org/opensearch/sql/analysis/TypeEnvironment.java
  core/src/main/java/org/opensearch/sql/analysis/symbol/SymbolTable.java
  core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
  core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
  core/src/main/java/org/opensearch/sql/ast/expression/NestedAllTupleFields.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/legacy/PrettyFormatResponseIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/NestedIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
Labels: backport 2.x
