Repository opensearch-project/sql, pull requests merged in 2023-03, with the labels that each got.

#1383 Integ Test Refactoring
  .github/workflows/sql-test-and-build-workflow.yml
  .gitignore
  build-tools/sqlplugin-coverage.gradle
  buildSrc/src/main/groovy/com/wiredforcode/spawn/KillProcessTask.groovy
  buildSrc/src/main/groovy/com/wiredforcode/spawn/SpawnProcessTask.groovy
  doctest/build.gradle
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/ppl/CsvFormatIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/DescribeCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/CsvFormatIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/RawFormatIT.java
  scripts/integtest.sh
Labels: infrastructure, backport main, backport 2.6

#1389 Refactor AWSSigV4 auth to support different AWSCredentialProviders
  plugin/build.gradle
  prometheus/build.gradle
  prometheus/src/main/java/org/opensearch/sql/prometheus/authinterceptors/AwsSigningInterceptor.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/authinterceptors/AwsSigningInterceptorTest.java
Labels: backport main, maintenance

#1366 Address build failures
  build.gradle
  integ-test/src/test/java/org/opensearch/sql/legacy/DateFunctionsIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/JSONRequestIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/MathFunctionsIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/NestedFieldQueryIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/QueryFunctionsIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/RestIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLFunctionsIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SourceFieldIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/ConditionalIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/domain/Paramer.java
  legacy/src/main/java/org/opensearch/sql/legacy/domain/hints/HintFactory.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/GetIndexRequestRestListener.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/join/ElasticJoinExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/join/ElasticUtils.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/QueryAction.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/join/JoinRequestBuilder.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/join/NestedLoopsElasticRequestBuilder.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/maker/AggMaker.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/maker/Maker.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/multi/MultiQueryRequestBuilder.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/scroll/Scroll.java
  legacy/src/main/java/org/opensearch/sql/legacy/request/SqlRequest.java
  legacy/src/main/java/org/opensearch/sql/legacy/utils/JsonPrettyFormatter.java
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/executor/DeleteResultSetTest.java
  legacy/src/test/java/org/opensearch/sql/legacy/util/AggregationUtils.java
  legacy/src/test/java/org/opensearch/sql/legacy/util/CheckScriptContents.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/response/AggregationResponseUtils.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilderTest.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java
Labels: backport 2.x

#1387 Typo fix and minor improvement in `maven-publish` GHA workflow.
  .github/workflows/maven-publish.yml
Labels: backport 2.x

#1410 [Backport 2.x] Deprecated Spring IoC and using Guice instead (#1177)
  build.gradle
  core/build.gradle
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionReferenceOptimizerTest.java
  core/src/test/java/org/opensearch/sql/analysis/NamedExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/QualifierAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/SelectAnalyzeTest.java
  core/src/test/java/org/opensearch/sql/analysis/SelectExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/WindowExpressionAnalyzerTest.java
  core/src/test/java/org/opensearch/sql/config/TestConfig.java
  core/src/test/java/org/opensearch/sql/executor/QueryServiceTest.java
  core/src/test/java/org/opensearch/sql/expression/ExpressionTestBase.java
  core/src/test/java/org/opensearch/sql/expression/function/FunctionPropertiesTestConfig.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalDedupeTest.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalEvalTest.java
  core/src/test/java/org/opensearch/sql/planner/logical/LogicalSortTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/PhysicalPlanTestBase.java
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSQLQueryAction.java
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlAction.java
  legacy/src/test/java/org/opensearch/sql/legacy/plugin/RestSQLQueryActionTest.java
  plugin/build.gradle
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  plugin/src/main/java/org/opensearch/sql/plugin/config/OpenSearchPluginConfig.java
  plugin/src/main/java/org/opensearch/sql/plugin/config/OpenSearchPluginModule.java
  plugin/src/main/java/org/opensearch/sql/plugin/transport/TransportPPLQueryAction.java
  ppl/build.gradle
  ppl/src/main/java/org/opensearch/sql/ppl/config/PPLServiceConfig.java
  ppl/src/test/java/org/opensearch/sql/ppl/PPLServiceTest.java
  sql/build.gradle
  sql/src/main/java/org/opensearch/sql/sql/config/SQLServiceConfig.java
  sql/src/test/java/org/opensearch/sql/sql/SQLServiceTest.java
Labels: maintenance

#1408 [main]Changes in DataSourceService and DataSourceMetadataStorage interface
  .gitignore
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceMetadataStorage.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceService.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceServiceImpl.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
  core/src/main/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScan.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/datasource/DataSourceServiceImplTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScanTest.java
  integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  plugin/src/test/java/org/opensearch/sql/plugin/datasource/DataSourceMetaDataTest.java
Labels: enhancement, backport 2.x

#1354 Resolve table function based on StorageEngine provided function resolver
  core/build.gradle
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionRepository.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/analysis/model/DataSourceSchemaIdentifierNameResolverTest.java
  core/src/test/java/org/opensearch/sql/expression/function/BuiltinFunctionRepositoryTest.java
Labels: backport 2.x, maintenance, spark integration

#1009 Bump backport version.
  .github/workflows/backport.yml
Labels: infrastructure, backport main

#1434 Added SINH function to V2 engine
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement, backport 2.x, v2.7.0

#1378 Add `sec_to_time` Function To OpenSearch SQL
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement, backport 2.x, v2.7.0

#1428 Added COSH to V2 engine
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement, SQL, new-engine-gap, backport 2.x, v2.7.0

#1433 Added RINT function to V2 engine
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement, backport 2.x, v2.7.0

#1429 Added SIGNUM function to V2 engine
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement, SQL, new-engine-gap, backport 2.x, v2.7.0

#1417 Add `YEARWEEK` Function To OpenSearch SQL
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/YearweekTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement, SQL, backport 2.x, v2.7.0

#1421 Add `EXTRACT` Function To OpenSearch SQL Plugin
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/ExtractTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: enhancement, SQL, backport 2.x, v2.7.0

#1420 Add `STR_TO_DATE` Function To The SQL Plugin
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFormatterUtil.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/StrToDateTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement, SQL, backport 2.x, v2.7.0

#1419 Add The `TO_SECONDS` Function To The SQL Plugin
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/utils/DateTimeFormatters.java
  core/src/test/java/org/opensearch/sql/expression/datetime/ToSecondsTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement, SQL, backport 2.x, v2.7.0

#1445 [Backport 2.x] Add `YEARWEEK` Function To OpenSearch SQL
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/YearweekTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement

#1431 [Backport main] Exclude OpenSearch system index when IT cleanup
  integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java
Labels: infrastructure

#1443 [Backport 2.x] Add `EXTRACT` Function To OpenSearch SQL Plugin
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/ExtractTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: enhancement

#1444 [Backport 2.x] Add `STR_TO_DATE` Function To The SQL Plugin
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFormatterUtil.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/StrToDateTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement

#1447 [Backport 2.x] Add The `TO_SECONDS` Function To The SQL Plugin
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/utils/DateTimeFormatters.java
  core/src/test/java/org/opensearch/sql/expression/datetime/ToSecondsTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement

#1451 Add `TIMESTAMPADD` Function To OpenSearch SQL Plugin
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/function/FunctionDSL.java
  core/src/main/java/org/opensearch/sql/expression/function/SerializableQuadFunction.java
  core/src/test/java/org/opensearch/sql/expression/datetime/TimeStampAddTest.java
  core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLTestBase.java
  core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLimplFourArgTest.java
  core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLimplWithPropertiesThreeArgsTest.java
  core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLnullMissingHandlingTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: enhancement, SQL, backport 2.x, v2.7.0

#1426 Fix line endings.
  .github/workflows/add-untriaged.yml
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: maintenance

#1457 Fix null response from pow/power and added missing integration testing
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
Labels: enhancement, backport 2.x, v2.7.0

#1467 Add `Timestampdiff` Function To OpenSearch SQL
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/TimeStampDiffTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: enhancement, backport 2.x, v2.7.0

#1458 [Main ]Create datasource API
  .gitignore
  build.gradle
  common/build.gradle
  common/src/main/java/org/opensearch/sql/common/encryptor/Encryptor.java
  common/src/main/java/org/opensearch/sql/common/encryptor/EncryptorImpl.java
  core/build.gradle
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/analysis/DataSourceSchemaIdentifierNameResolver.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceService.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceServiceImpl.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceUserAuthorizationHelper.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/analysis/model/DataSourceSchemaIdentifierNameResolverTest.java
  core/src/test/java/org/opensearch/sql/datasource/DataSourceServiceImplTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScanTest.java
  docs/user/dql/metadata.rst
  docs/user/ppl/admin/datasources.rst
  doctest/test_data/datasources.json
  doctest/test_docs.py
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
  integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ShowDataSourcesCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java
  integ-test/src/test/resources/datasources.json
  integ-test/src/test/resources/indexDefinitions/datasources_index_mappings.json
  legacy/build.gradle
  legacy/src/main/java/org/opensearch/sql/legacy/metrics/MetricName.java
  plugin/build.gradle
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  plugin/src/main/java/org/opensearch/sql/plugin/datasource/DataSourceSettings.java
  plugin/src/main/java/org/opensearch/sql/plugin/datasource/DataSourceUserAuthorizationHelperImpl.java
  plugin/src/main/java/org/opensearch/sql/plugin/datasource/OpenSearchDataSourceMetadataStorage.java
  plugin/src/main/java/org/opensearch/sql/plugin/model/CreateDataSourceActionRequest.java
  plugin/src/main/java/org/opensearch/sql/plugin/model/CreateDataSourceActionResponse.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestDataSourceQueryAction.java
  plugin/src/main/java/org/opensearch/sql/plugin/transport/datasource/TransportCreateDataSourceAction.java
  plugin/src/main/java/org/opensearch/sql/plugin/utils/Scheduler.java
  plugin/src/main/java/org/opensearch/sql/plugin/utils/XContentParserUtils.java
  plugin/src/main/resources/datasources-index-mapping.yml
  plugin/src/main/resources/datasources-index-settings.yml
  plugin/src/test/java/org/opensearch/sql/plugin/datasource/DataSourceMetaDataTest.java
  plugin/src/test/java/org/opensearch/sql/plugin/datasource/DataSourceUserAuthorizationHelperImplTest.java
  plugin/src/test/java/org/opensearch/sql/plugin/datasource/OpenSearchDataSourceMetadataStorageTest.java
  plugin/src/test/java/org/opensearch/sql/plugin/utils/SchedulerTest.java
  plugin/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
Labels: feature, backport 2.x

#1479 [Backport 2.x] Create datasource API (#1458)
  .gitignore
  build.gradle
  common/build.gradle
  common/src/main/java/org/opensearch/sql/common/encryptor/Encryptor.java
  common/src/main/java/org/opensearch/sql/common/encryptor/EncryptorImpl.java
  core/build.gradle
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/analysis/DataSourceSchemaIdentifierNameResolver.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceService.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceServiceImpl.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceUserAuthorizationHelper.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/analysis/model/DataSourceSchemaIdentifierNameResolverTest.java
  core/src/test/java/org/opensearch/sql/datasource/DataSourceServiceImplTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScanTest.java
  docs/user/dql/metadata.rst
  docs/user/ppl/admin/datasources.rst
  doctest/test_data/datasources.json
  doctest/test_docs.py
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
  integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ShowDataSourcesCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java
  integ-test/src/test/resources/datasources.json
  integ-test/src/test/resources/indexDefinitions/datasources_index_mappings.json
  legacy/build.gradle
  legacy/src/main/java/org/opensearch/sql/legacy/metrics/MetricName.java
  plugin/build.gradle
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  plugin/src/main/java/org/opensearch/sql/plugin/datasource/DataSourceSettings.java
  plugin/src/main/java/org/opensearch/sql/plugin/datasource/DataSourceUserAuthorizationHelperImpl.java
  plugin/src/main/java/org/opensearch/sql/plugin/datasource/OpenSearchDataSourceMetadataStorage.java
  plugin/src/main/java/org/opensearch/sql/plugin/model/CreateDataSourceActionRequest.java
  plugin/src/main/java/org/opensearch/sql/plugin/model/CreateDataSourceActionResponse.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestDataSourceQueryAction.java
  plugin/src/main/java/org/opensearch/sql/plugin/transport/datasource/TransportCreateDataSourceAction.java
  plugin/src/main/java/org/opensearch/sql/plugin/utils/Scheduler.java
  plugin/src/main/java/org/opensearch/sql/plugin/utils/XContentParserUtils.java
  plugin/src/main/resources/datasources-index-mapping.yml
  plugin/src/main/resources/datasources-index-settings.yml
  plugin/src/test/java/org/opensearch/sql/plugin/datasource/DataSourceMetaDataTest.java
  plugin/src/test/java/org/opensearch/sql/plugin/datasource/DataSourceUserAuthorizationHelperImplTest.java
  plugin/src/test/java/org/opensearch/sql/plugin/datasource/OpenSearchDataSourceMetadataStorageTest.java
  plugin/src/test/java/org/opensearch/sql/plugin/utils/SchedulerTest.java
  plugin/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
Labels: feature

#1365 Replace non-ASCII characters in code and docs.
  common/src/test/java/org/opensearch/sql/common/grok/BasicTest.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/datetime.rst
  integ-test/src/test/java/org/opensearch/sql/legacy/MethodQueryIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/domain/Condition.java
  legacy/src/main/java/org/opensearch/sql/legacy/domain/Field.java
  legacy/src/main/java/org/opensearch/sql/legacy/domain/MethodField.java
  legacy/src/main/java/org/opensearch/sql/legacy/domain/Order.java
  legacy/src/main/java/org/opensearch/sql/legacy/domain/SearchResult.java
  legacy/src/main/java/org/opensearch/sql/legacy/domain/Select.java
  legacy/src/main/java/org/opensearch/sql/legacy/esdomain/mapping/FieldMappings.java
  legacy/src/main/java/org/opensearch/sql/legacy/parser/FieldMaker.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/maker/AggMaker.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/maker/Maker.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/maker/QueryMaker.java
Labels: maintenance
