Repository opensearch-project/sql, pull requests merged in 2023-01, with the labels that each got.

#1191 Allow common keywords and scalar function name used as identifier
  integ-test/src/test/java/org/opensearch/sql/legacy/AggregationExpressionIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/JdbcTestIT.java
  integ-test/src/test/resources/correctness/queries/aggregation.txt
  sql/src/main/antlr/OpenSearchSQLIdentifierParser.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/parser/AstQualifiedNameBuilderTest.java
Labels: bug, SQL, backport 2.x

#1197 Fix truncate() function
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
Labels: bug, backport 2.x, data-correctness

#1180 Suppress CI failures not related to testing/building
  .github/workflows/sql-test-and-build-workflow.yml
Labels: infrastructure

#1181 Disallow unquoted literals in `LIKE` clause in `DESCRIBE` statement
  docs/category.json
  docs/user/dql/metadata.rst
  docs/user/img/rdd/showFilter.png
  docs/user/img/rdd/showStatement.png
  integ-test/src/test/java/org/opensearch/sql/sql/AdminIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
Labels: SQL, breaking, v3.0.0, legacy

#1224 Updated MAINTAINERS.md format.
  MAINTAINERS.md
  sql-cli/MAINTAINERS.md
  sql-jdbc/MAINTAINERS.md
  sql-odbc/MAINTAINERS.md
Labels: backport 1.x, backport 2.x

#1195 Add `TIMEDIFF` and `DATEDIFF` functions. (#131)
  core/src/main/java/org/opensearch/sql/data/model/ExprDateValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprDatetimeValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprTimeValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprTimestampValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprValueUtils.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/function/FunctionDSL.java
  core/src/main/java/org/opensearch/sql/utils/DateTimeUtils.java
  core/src/test/java/org/opensearch/sql/data/model/DateTimeValueTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateDiffTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java
  core/src/test/java/org/opensearch/sql/expression/datetime/TimeDiffTest.java
  core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLTestBase.java
  core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLimplWithPropertiesTwoArgTest.java
  core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLnullMissingHandlingTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/datetime.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement, backport 2.x

#1166 Add Alternate Syntax For Match_Query And Other Functions
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/legacy/MethodQueryIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/MatchIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/MatchPhraseIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/MultiMatchIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: enhancement, backport 2.x

#1231 Add Second_Of_Minute Function As An Alias Of The Second Function
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement, SQL, backport 2.x

#1230 Add Minute_Of_Hour Function As An Alias Of Minute Function (#196)
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement, SQL, backport 2.x

#1228 Add Day_Of_Week Function As An Alias Of DayOfWeek
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement, SQL, backport 2.x

#1209 Add BWC tests for running against distribution bundle.
  integ-test/build.gradle
  integ-test/src/test/resources/security/esnode-key.pem
  integ-test/src/test/resources/security/esnode.pem
  integ-test/src/test/resources/security/kirk-key.pem
  integ-test/src/test/resources/security/kirk.pem
  integ-test/src/test/resources/security/root-ca.pem
  integ-test/src/test/resources/security/sample.pem
Labels: infrastructure

#1241 Hot Fix For CI Build
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: infrastructure

#1244 Fixed error with single timestamp filter query on prometheus datasource
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/SeriesSelectionQueryBuilder.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTableTest.java
Labels: backport 2.x, backport 2.4

#1229 Support JOIN query on object field with unexpanded name
  integ-test/src/test/java/org/opensearch/sql/legacy/HashJoinIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
  integ-test/src/test/resources/indexDefinitions/unexpanded_object_index_mapping.json
  integ-test/src/test/resources/unexpanded_objects.json
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/scroll/SearchHitRow.java
  legacy/src/test/java/org/opensearch/sql/legacy/query/planner/physical/node/scroll/SearchHitRowTest.java
Labels: bug, SQL, backport 2.x, backport 2.5

#1194 Add functions `ADDTIME` and `SUBTIME`. (#132)
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/utils/DateTimeUtils.java
  core/src/test/java/org/opensearch/sql/expression/datetime/AddTimeAndSubTimeTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/datetime.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement, backport 2.x

#1205 Add support for long value return for CEIL, CEILING and FLOOR math functions
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/math.rst
  integ-test/src/test/java/org/opensearch/sql/legacy/TypeInformationIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/MathematicalFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
  integ-test/src/test/resources/correctness/expressions/mathematical_functions.txt
Labels: enhancement, backport 2.x

#1253 [Backport 2.x] Add Minute_Of_Hour Function As An Alias Of Minute Function
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement

#1256 Remove unnecessary scripts after repo split
  build.gradle
  scripts/build.sh
Labels: backport 2.5

#1223 Add Support For `TIME` Type in "*_OF_YEAR" Functions
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/FunctionDSL.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLimplWithPropertiesTwoArgsTest.java
  docs/user/dql/functions.rst
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement, backport 2.x

#1227 Add Day_Of_Month Function As An Alias Of DayOfMonth
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement, SQL, backport 2.x

#1226 Add Hour_Of_Day Function As An Alias Of Hour
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: enhancement, SQL, backport 2.x, backport 2.5

#1267 [Prometheus]Bug fix for less than and greater than operators on @time…
  docs/user/ppl/admin/prometheus_connector.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/SeriesSelectionQueryBuilder.java
  prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/TimeRangeParametersResolver.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTableTest.java
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/querybuilders/TimeRangeParametersResolverTest.java
Labels: bug, backport 2.x, backport 2.4, backport 2.5

#1268 add 2.5 release notes
  release-notes/opensearch-sql.release-notes-2.5.0.0.md
Labels: release, backport 2.x, backport main

#1204 Adding mutation testing to build gradle with PiTest
  .github/workflows/sql-test-and-build-workflow.yml
  DEVELOPER_GUIDE.rst
  core/build.gradle
  opensearch/build.gradle
Labels: infrastructure

#1283 Upgrade sqlite to 3.32.3.3
  integ-test/build.gradle
Labels: dependencies

#1284 Remove in development filesystem support
  DEVELOPER_GUIDE.rst
  filesystem/build.gradle
  filesystem/src/main/java/org/opensearch/sql/filesystem/storage/split/FileSystemSplit.java
  filesystem/src/main/java/org/opensearch/sql/filesystem/streaming/FileMetaData.java
  filesystem/src/main/java/org/opensearch/sql/filesystem/streaming/FileSystemStreamSource.java
  filesystem/src/test/java/org/opensearch/sql/filesystem/streaming/FileSystemStreamSourceTest.java
  filesystem/src/testFixtures/java/org/opensearch/sql/filesystem/storage/FSDataSourceFactory.java
  filesystem/src/testFixtures/java/org/opensearch/sql/filesystem/storage/FSStorageEngine.java
  filesystem/src/testFixtures/java/org/opensearch/sql/filesystem/storage/FSTable.java
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/ppl/StreamingQueryIT.java
  plugin/build.gradle
  settings.gradle
Labels: backport 2.x, backport 2.5

#1285 Move PiTest to a new workflow.
  .github/workflows/sql-pitest.yml
  .github/workflows/sql-test-and-build-workflow.yml
  .github/workflows/sql-test-workflow.yml
Labels: infrastructure

#1278 Add micro benchmark by JMH
  benchmarks/README.md
  benchmarks/build.gradle
  benchmarks/src/jmh/java/org/opensearch/sql/expression/operator/predicate/ComparisonOperatorBenchmark.java
  settings.gradle
Labels: infrastructure

#1288 Allow literal in aggregation (#203)
  integ-test/src/test/java/org/opensearch/sql/legacy/AggregationExpressionIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/AggregationBuilderHelper.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilderTest.java
Labels: bug, backport 2.x

#1200 Reorganize development docs
  README.md
  docs/dev/datasource-prometheus.md
  docs/dev/datasource-query-s3.md
  docs/dev/index.md
  docs/dev/intro-architecture.md
  docs/dev/intro-v2-engine.md
  docs/dev/opensearch-nested-field-subquery.md
  docs/dev/opensearch-pagination.md
  docs/dev/opensearch-relevancy-search.md
  docs/dev/query-automatic-acceleration.md
  docs/dev/query-manager.md
  docs/dev/query-null-missing-value.md
  docs/dev/query-optimizier-improvement.md
  docs/dev/query-semantic-analysis.md
  docs/dev/query-type-conversion.md
  docs/dev/sql-aggregate-window-function.md
  docs/dev/testing-comparison-test.md
  docs/dev/testing-doctest.md
Labels: documentation

#1196 Extend comparison methods to accept different datetime types. (#129)
  core/src/main/java/org/opensearch/sql/data/model/AbstractExprValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprDateValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprDatetimeValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprTimeValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprTimestampValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprValue.java
  core/src/main/java/org/opensearch/sql/data/type/ExprCoreType.java
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/operator/convert/TypeCastOperator.java
  core/src/test/java/org/opensearch/sql/data/model/ExprBooleanValueTest.java
  core/src/test/java/org/opensearch/sql/data/model/ExprStringValueTest.java
  core/src/test/java/org/opensearch/sql/data/model/ExprValueCompareTest.java
  core/src/test/java/org/opensearch/sql/expression/function/WideningTypeRuleTest.java
  core/src/test/java/org/opensearch/sql/expression/operator/predicate/BinaryPredicateOperatorTest.java
  core/src/test/java/org/opensearch/sql/utils/ComparisonUtil.java
  docs/user/dql/expressions.rst
  docs/user/ppl/functions/expressions.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeComparisonIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeComparisonIT.java
Labels: enhancement, backport 2.x

#1279 Enable `concat()` string function to support multiple string arguments
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionRepository.java
  core/src/main/java/org/opensearch/sql/expression/function/DefaultFunctionResolver.java
  core/src/main/java/org/opensearch/sql/expression/function/FunctionSignature.java
  core/src/main/java/org/opensearch/sql/expression/text/TextFunction.java
  core/src/test/java/org/opensearch/sql/expression/function/DefaultFunctionResolverTest.java
  core/src/test/java/org/opensearch/sql/expression/text/TextFunctionTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/string.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/TextFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/TextFunctionIT.java
  integ-test/src/test/resources/correctness/expressions/text_functions.txt
Labels: enhancement, backport 2.x

#1303 Remove obsolete links from README.
  README.md
Labels: documentation, backport 2.x

#1304 Update link checker CI workflow.
  .github/workflows/link-checker.yml
Labels: infrastructure

#1311 add docker compose for testing spark connector
  docker/docker-compose.yml
  docker/spark/Dockerfile
  docker/spark/jars/opensearch-spark-30_2.12-3.0.0-SNAPSHOT.jar
  docker/spark/log4j.properties
  docker/spark/spark-defaults.conf
  docker/spark/start-spark.sh
  docker/spark/supervisord.conf
Labels: spark integration

#1061 Datetime aggregation fixes.
  core/src/main/java/org/opensearch/sql/data/model/ExprValueUtils.java
  core/src/main/java/org/opensearch/sql/expression/aggregation/AggregatorFunction.java
  core/src/main/java/org/opensearch/sql/expression/aggregation/AvgAggregator.java
  core/src/test/java/org/opensearch/sql/expression/aggregation/AvgAggregatorTest.java
  docs/user/dql/aggregations.rst
  integ-test/src/test/java/org/opensearch/sql/sql/AggregationIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/ExpressionAggregationScript.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilder.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/ExpressionAggregationScriptTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilderTest.java
Labels: bug, SQL, backport 2.x
