Repository opensearch-project/sql, pull requests merged in 2023-04, with the labels that each got.

#1496 [Backport 2.x] Add publish snapshots to maven via GHA
  .github/workflows/link-checker.yml
  .github/workflows/maven-publish.yml
  plugin/build.gradle
Labels: infrastructure

#1456 #639: allow metadata fields and score opensearch function (#228)
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
  core/src/main/java/org/opensearch/sql/analysis/ExpressionReferenceOptimizer.java
  core/src/main/java/org/opensearch/sql/analysis/TypeEnvironment.java
  core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
  core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
  core/src/main/java/org/opensearch/sql/ast/expression/ScoreFunction.java
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/function/OpenSearchFunctions.java
  core/src/main/java/org/opensearch/sql/storage/Table.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
  docs/user/dql/basics.rst
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/legacy/CsvFormatResponseIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/MethodQueryIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/PrettyFormatResponseIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/IdentifierIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/MatchIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/ScoreQueryIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/OpenSearchResponse.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanQueryBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/sort/SortQueryBuilder.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequestTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequestTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchResponseTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanOptimizationTest.java
  sql/src/main/antlr/OpenSearchSQLLexer.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
  sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Labels: enhancement, new-engine-gap, backport 2.x, backport 2.7

#1530 Documentation and other papercuts for datasource api launch
  datasources/src/main/java/org/opensearch/sql/datasources/settings/DataSourceSettings.java
  datasources/src/main/resources/datasources-index-mapping.yml
  datasources/src/main/resources/datasources-index-settings.yml
  docs/user/ppl/admin/datasources.rst
  doctest/build.gradle
  integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ShowDataSourcesCommandIT.java
  scripts/integtest.sh
Labels: enhancement, backport 2.x, v2.7.0, backport 2.7

#1537 Release Notes for 2.7.0
  release-notes/opensearch-sql.release-notes-2.7.0.0.md
Labels: documentation, backport 2.x, backport 2.7

#1541 Datasources Integ Test Fix
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ShowDataSourcesCommandIT.java
Labels: bug, backport 2.x, backport 2.7

#1549 Ensure Nested Function Falls Back to Legacy Engine Where Not Supported
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  integ-test/src/test/java/org/opensearch/sql/sql/NestedIT.java
  sql/src/main/java/org/opensearch/sql/sql/parser/AstSortBuilder.java
  sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
Labels: bug, backport 2.x, backport 2.7

#1553 release notes for 2.7.0 PATCH
  release-notes/opensearch-sql.release-notes-2.7.0.0.md
Labels: documentation, backport 2.x, backport 2.7

#1561 adding reflections as a dependency
  ppl/build.gradle
Labels: bug

#1562 updating release notes 2.7.0.0
  release-notes/opensearch-sql.release-notes-2.7.0.0.md
Labels: documentation, release

#1310 Minor clean up of datetime and other classes (#198)
  core/src/main/java/org/opensearch/sql/ast/statement/Explain.java
  core/src/main/java/org/opensearch/sql/ast/tree/Limit.java
  core/src/main/java/org/opensearch/sql/data/model/ExprDateValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprDatetimeValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprTimeValue.java
  core/src/main/java/org/opensearch/sql/data/model/ExprTimestampValue.java
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/ArithmeticFunction.java
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/main/java/org/opensearch/sql/expression/operator/predicate/BinaryPredicateOperator.java
  core/src/main/java/org/opensearch/sql/expression/parse/ParseExpression.java
  core/src/main/java/org/opensearch/sql/planner/physical/collector/Rounding.java
  core/src/main/java/org/opensearch/sql/utils/DateTimeFormatters.java
  core/src/main/java/org/opensearch/sql/utils/DateTimeUtils.java
  core/src/test/java/org/opensearch/sql/data/model/DateTimeValueTest.java
  core/src/test/java/org/opensearch/sql/data/model/ExprValueUtilsTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/ConvertTZTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java
  core/src/test/java/org/opensearch/sql/expression/datetime/MakeDateTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/MakeTimeTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/NowLikeFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/TimestampTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/UnixTwoWayConversionTest.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/ArithmeticFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/UnaryFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/operator/predicate/BinaryPredicateOperatorTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/FilterOperatorTest.java
  docs/user/dql/functions.rst
  docs/user/ppl/functions/datetime.rst
  docs/user/ppl/functions/math.rst
  docs/user/ppl/functions/relevance.rst
  docs/user/ppl/functions/string.rst
  doctest/build.gradle
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/NowLikeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/NowLikeFunctionIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/executor/protector/ResourceMonitorPlan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQuery.java
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: maintenance

#1565 [Backport 2.x] Added COSH to V2 engine
  core/src/main/java/org/opensearch/sql/expression/DSL.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
  core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
  docs/user/dql/functions.rst
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
  sql/src/main/antlr/OpenSearchSQLParser.g4
Labels: enhancement

#1573 Create Flint project folder
  flint/.gitignore
  flint/README.md
  flint/build.sbt
  flint/flint-core/src/main/scala/org/opensearch/flint/core/FlintIndex.scala
  flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkExtensions.scala
  flint/project/build.properties
Labels: Flint

#1586 Bump org.json dependency version
  integ-test/src/test/java/org/opensearch/sql/legacy/AggregationIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/NestedFieldQueryIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SubqueryIT.java
  integ-test/src/test/java/org/opensearch/sql/util/MatcherUtils.java
  legacy/build.gradle
  legacy/src/main/java/org/opensearch/sql/legacy/expression/model/ExprValueFactory.java
  opensearch/build.gradle
  ppl/build.gradle
  prometheus/build.gradle
  sql/build.gradle
Labels: dependencies
