Repository opensearch-project/sql, pull requests merged in 2023-12, with the labels that each got.

#2443 Async query get result bug fix
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/AsyncQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java
Labels: bug, backport 2.x

#2448 Validate session with flint datasource passed in async job request
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  docs/user/admin/settings.rst
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  spark/src/main/antlr/FlintSparkSqlExtensions.g4
  spark/src/main/antlr/SparkSqlBase.g4
  spark/src/main/antlr/SqlBaseLexer.g4
  spark/src/main/antlr/SqlBaseParser.g4
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/Session.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/utils/RealTimeProvider.java
  spark/src/main/java/org/opensearch/sql/spark/utils/TimeProvider.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
  spark/src/test/java/org/opensearch/sql/spark/utils/MockTimeProvider.java
Labels: backport 2.x

#2452 Add seder to TransportPPLQueryResponse
  plugin/src/main/java/org/opensearch/sql/plugin/transport/TransportPPLQueryResponse.java
  plugin/src/test/java/org/opensearch/sql/plugin/transport/TransportPPLQueryResponseTest.java
Labels: enhancement, backport 2.x

#2454 Upgrade JSON to 20231013 to fix CVE-2023-5072
  legacy/build.gradle
  opensearch/build.gradle
  ppl/build.gradle
  prometheus/build.gradle
  spark/build.gradle
  sql/build.gradle
Labels: security fix

#2451 Move pplenabled to transport
  docs/user/ppl/admin/settings.rst
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLQueryAction.java
  plugin/src/main/java/org/opensearch/sql/plugin/transport/TransportPPLQueryAction.java
Labels: enhancement, backport 2.x
