Repository opensearch-project/sql, pull requests merged in 2024-02, with the labels that each got.

#2492 Add SparkDataType as wrapper for unmapped spark data type
  spark/src/main/java/org/opensearch/sql/spark/data/type/SparkDataType.java
  spark/src/main/java/org/opensearch/sql/spark/data/value/SparkExprValue.java
  spark/src/main/java/org/opensearch/sql/spark/functions/response/DefaultSparkSqlFunctionResponseHandle.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/data/value/SparkExprValueTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanOperatorTest.java
  spark/src/test/resources/invalid_data_type.json
  spark/src/test/resources/spark_data_type.json
Labels: backport 2.x, Flint

#2488 Async Executor Service Depedencies Refactor
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlStatsAction.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLStatsAction.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactory.java
  spark/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImpl.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
  spark/src/test/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModuleTest.java
Labels: bug, backport 2.x

#2503 Bump aws-java-sdk-core version to 1.12.651
  build.gradle
  common/build.gradle
  integ-test/build.gradle
  spark/build.gradle
Labels: backport 2.x

#2504 [DOC] Configure the Spark metrics properties while creating a s3 Glue Connector
  docs/user/interfaces/asyncqueryinterface.rst
Labels: documentation, backport 2.x, v2.12.0

#2481 Add JDK-21 to GA worklflows
  .github/workflows/integ-tests-with-security.yml
  .github/workflows/sql-test-and-build-workflow.yml
  docs/user/dql/functions.rst
  docs/user/ppl/functions/relevance.rst
Labels: backport 2.x, v2.12.0

#2510 Add setting plugins.query.executionengine.async_query.enabled
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  docs/user/admin/settings.rst
  integ-test/src/test/java/org/opensearch/sql/asyncquery/AsyncQueryIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  spark/src/main/java/org/opensearch/sql/spark/rest/RestAsyncQueryManagementAction.java
  spark/src/main/java/org/opensearch/sql/spark/transport/TransportCreateAsyncQueryRequestAction.java
  spark/src/test/java/org/opensearch/sql/spark/transport/TransportCreateAsyncQueryRequestActionTest.java
Labels: enhancement, backport 2.x

#2513 Add release notes for 2.12.0.0
  release-notes/opensearch-sql.release-notes-2.12.0.0.md
Labels: documentation, backport 2.x, backport 2.12

#2522 Fix issue in testSourceMetricCommandWithTimestamp integ test with different timezones and locales.
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
Labels: bug, backport 2.x, backport 2.12
