Repository opensearch-project/sql, pull requests merged in 2024-08, with the labels that each got.

#2801 Support common format geo point
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
  integ-test/src/test/java/org/opensearch/sql/sql/GeopointFormatsIT.java
  integ-test/src/test/resources/geopoints.json
  integ-test/src/test/resources/indexDefinitions/geopoint_index_mapping.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContent.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContentTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
Labels: backport 2.x

#2879 Add AsyncQueryRequestContext to FlintIndexMetadataService/FlintIndexS…
  async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorService.java
  async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/AsyncQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataService.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/FlintIndexStateModelService.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpAlter.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpCancel.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpDrop.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuum.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuumTest.java
  async-query/src/main/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTask.java
  async-query/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataServiceImpl.java
  async-query/src/main/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexStateModelService.java
  async-query/src/main/java/org/opensearch/sql/spark/transport/TransportCancelAsyncQueryRequestAction.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/model/MockFlintSparkJob.java
  async-query/src/test/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTaskTest.java
  async-query/src/test/java/org/opensearch/sql/spark/flint/FlintIndexMetadataServiceImplTest.java
  async-query/src/test/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexStateModelServiceTest.java
  async-query/src/test/java/org/opensearch/sql/spark/transport/TransportCancelAsyncQueryRequestActionTest.java
Labels: backport 2.x, maintenance

#2890 [2.x] Update SqlBaseParser
  async-query-core/src/main/antlr/SqlBaseParser.g4
Labels: bug

#2836 Correct regular expression range
  common/src/main/java/org/opensearch/sql/common/grok/GrokCompiler.java
  common/src/main/java/org/opensearch/sql/common/grok/GrokUtils.java
Labels: backport 2.x

#2876 Push down limit through eval
  core/src/main/java/org/opensearch/sql/planner/optimizer/LogicalPlanOptimizer.java
  core/src/main/java/org/opensearch/sql/planner/optimizer/pattern/Patterns.java
  core/src/main/java/org/opensearch/sql/planner/optimizer/rule/EvalPushDown.java
  core/src/test/java/org/opensearch/sql/planner/optimizer/LogicalPlanOptimizerTest.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ExplainIT.java
  integ-test/src/test/resources/expectedOutput/ppl/explain_limit_push.json
Labels: enhancement

#2902 [Tests] IT tests and test utils update to fix failing tests for serverless
  integ-test/src/test/java/org/opensearch/sql/legacy/CsvFormatResponseIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/CsvFormatIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/DedupCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ParseCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/SortCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/ConditionalIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/CsvFormatIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/NestedIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/RawFormatIT.java
  integ-test/src/test/java/org/opensearch/sql/util/TestUtils.java
Labels: backport 2.x, maintenance

#2936 Merge feature/pit branch to main
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  docs/dev/opensearch-pagination.md
  docs/user/admin/settings.rst
  integ-test/src/test/java/org/opensearch/sql/legacy/JoinIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/ElasticHitsExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/join/ElasticJoinExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/join/HashJoinElasticExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/join/NestedLoopsElasticExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/join/QueryPlanElasticExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/multi/MinusExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/multi/UnionExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/pit/PointInTimeHandler.java
  legacy/src/main/java/org/opensearch/sql/legacy/pit/PointInTimeHandlerImpl.java
  legacy/src/test/java/org/opensearch/sql/legacy/pit/PointInTimeHandlerImplTest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
Labels: feature, backport 2.x

#2940 Add pit for pagination query
  legacy/src/main/java/org/opensearch/sql/legacy/cursor/DefaultCursor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/cursor/CursorCloseExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/cursor/CursorResultExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/format/PrettyFormatRestExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/format/SelectResultSet.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/join/ElasticJoinExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/multi/MinusExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/pit/PointInTimeHandlerImpl.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/DefaultQueryAction.java
  legacy/src/test/java/org/opensearch/sql/legacy/pit/PointInTimeHandlerImplTest.java
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/cursor/DefaultCursorTest.java
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/query/DefaultQueryActionTest.java
Labels: feature

#2946 Add mvQuery attribute in IndexQueryDetails
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryDetails.java
  async-query-core/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
Labels: backport 2.x, maintenance

#2943 Add AsyncQueryRequestContext to update/get in StatementStorageService
  async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorService.java
  async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/AsyncQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/Session.java
  async-query-core/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
  async-query-core/src/main/java/org/opensearch/sql/spark/execution/statestore/StatementStorageService.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  async-query/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStatementStorageService.java
  async-query/src/main/java/org/opensearch/sql/spark/transport/TransportGetAsyncQueryResultAction.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecAlterTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
  async-query/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
  async-query/src/test/java/org/opensearch/sql/spark/transport/TransportGetAsyncQueryResultActionTest.java
Labels: backport 2.x, maintenance

#2944 Extract validation logic from FlintIndexMetadataServiceImpl
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataValidator.java
  async-query-core/src/test/java/org/opensearch/sql/spark/flint/FlintIndexMetadataValidatorTest.java
  async-query/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataServiceImpl.java
Labels: backport 2.x, maintenance
