Repository opensearch-project/sql, pull requests merged in 2024-09, with the labels that each got.

#2955 Fix jobType for Batch and IndexDML query
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
Labels: bug, backport 2.x

#2952 Add queryId Spark parameter to batch query
  async-query-core/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/parameter/SparkSubmitParametersBuilder.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: enhancement, backport 2.x

#2966 Fix SparkExecutionEngineConfigClusterSetting deserialize issue
  async-query/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSetting.java
Labels: bug, backport 2.x, backport 2.17

#2961 Flint query scheduler part 2
  async-query-core/src/main/antlr/FlintSparkSqlExtensions.g4
  async-query-core/src/main/antlr/SparkSqlBase.g4
  async-query-core/src/main/antlr/SqlBaseLexer.g4
  async-query-core/src/main/antlr/SqlBaseParser.g4
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/model/FlintIndexOptions.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpAlter.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpDrop.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpFactory.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuum.java
  async-query-core/src/main/java/org/opensearch/sql/spark/scheduler/AsyncQueryScheduler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/scheduler/model/AsyncQuerySchedulerRequest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpFactoryTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuumTest.java
  async-query/build.gradle
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/OpenSearchAsyncQueryScheduler.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/job/OpenSearchRefreshIndexJob.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/job/ScheduledAsyncQueryJobRunner.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/model/OpenSearchRefreshIndexJobRequest.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/model/ScheduledAsyncQueryJobRequest.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/parser/IntervalScheduleParser.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/parser/OpenSearchScheduleQueryJobRequestParser.java
  async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  async-query/src/main/resources/async-query-scheduler-index-mapping.yml
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/OpenSearchAsyncQuerySchedulerTest.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/job/OpenSearchRefreshIndexJobTest.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/job/ScheduledAsyncQueryJobRunnerTest.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/model/OpenSearchRefreshIndexJobRequestTest.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/model/ScheduledAsyncQueryJobRequestTest.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/parser/IntervalScheduleParserTest.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
Labels: enhancement, backport 2.x, v2.17.0, backport 2.17

#2959 Adds validation to allow only flint queries and sql SELECT queries to security lake type datasource
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  async-query-core/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
Labels: backport 2.x, backport 2.17

#2968 Fix handler for existing query
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/model/JobType.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: bug, backport 2.x, backport 2.17

#2973 Add feature flag for async query scheduler
  async-query-core/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query/src/main/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposer.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/parser/IntervalScheduleParser.java
  async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  async-query/src/test/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposerTest.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/parser/IntervalScheduleParserTest.java
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  docs/user/admin/settings.rst
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
Labels: backport 2.x, v2.17.0, backport 2.17

#2990 Fix type mismatch
  async-query/src/main/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposer.java
  async-query/src/test/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposerTest.java
Labels: backport 2.x

#2985 Delegate Flint index vacuum operation to Spark
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpFactory.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuum.java
  async-query-core/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpFactoryTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuumTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
  async-query/src/test/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexClientTest.java
Labels: enhancement, backport 2.x, backport 2.17

#2992 Add release notes for v2.17.0
  release-notes/opensearch-sql.release-notes-2.17.0.0.md
Labels: release, backport 2.x, v2.17.0, backport 2.17

#2956 Populate indexName for BatchQuery
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryDetails.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
Labels: bug, backport 2.x, maintenance

#2958 Add query, langType, status, error in AsyncQueryJobMetadata
  async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
  async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/model/QueryState.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryResponse.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/model/QueryStateTest.java
Labels: backport 2.x, maintenance

#2988 Throw exception for RECOVER INDEX JOB query
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryActionType.java
  async-query-core/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
Labels: backport 2.x, maintenance

#2986 Throw IllegalArgumentException when cancelJob failed with ValidationException
  async-query-core/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
  async-query-core/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
Labels: backport 2.x, maintenance

#3007 Bump BWC version to 2.17
  integ-test/build.gradle
Labels: maintenance

#3004 Upgrade org.bouncycastle:bcprov-jdk18on to 1.78.1
  datasources/build.gradle
Labels: security fix, backport 2.x, backport 2.17

#3014 Extend scheduler interface for Multitenancy
  .github/workflows/integ-tests-with-security.yml
  .github/workflows/sql-pitest.yml
  .github/workflows/sql-test-and-build-workflow.yml
  .github/workflows/sql-test-workflow.yml
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpAlter.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpDrop.java
  async-query-core/src/main/java/org/opensearch/sql/spark/scheduler/AsyncQueryScheduler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/scheduler/model/AsyncQuerySchedulerRequest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/OpenSearchAsyncQueryScheduler.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/model/ScheduledAsyncQueryJobRequest.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/parser/OpenSearchScheduleQueryJobRequestParser.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/OpenSearchAsyncQuerySchedulerTest.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/job/ScheduledAsyncQueryJobRunnerTest.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/model/ScheduledAsyncQueryJobRequestTest.java
Labels: backport 2.x

#2981 Add missing refactoring of Scroll to PIT API calls for Joins and Pagination query
  integ-test/src/test/java/org/opensearch/sql/legacy/CursorIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/PaginationFilterIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/StandalonePaginationIT.java
  integ-test/src/test/resources/expectedOutput/ppl/explain_filter_agg_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_filter_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_limit_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_output.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_sort_push.json
  legacy/src/main/java/org/opensearch/sql/legacy/executor/format/SelectResultSet.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/logical/node/TableScan.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/Paginate.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/SearchHitRow.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/pointInTime/PointInTime.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/scroll/Scroll.java
  legacy/src/test/java/org/opensearch/sql/legacy/query/planner/physical/node/scroll/SearchHitRowTest.java
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/planner/QueryPlannerTest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchRestClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScan.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngineTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtectorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequestTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanPaginationTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanTest.java
Labels: feature

#3045 Bug Fixes for minor issues with SQL PIT refactor
  legacy/src/main/java/org/opensearch/sql/legacy/executor/format/PrettyFormatRestExecutor.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/join/ElasticJoinExecutor.java
  legacy/src/test/java/org/opensearch/sql/legacy/executor/format/PrettyFormatRestExecutorTest.java
Labels: bug

#3018 [2.x] Remove unneeded Dummy files
  async-query-core/src/main/java/org/opensearch/sql/asyncquery/Dummy.java
  async-query-core/src/test/java/org/opensearch/sql/asyncquery/DummyTest.java
  async-query/src/main/java/org/opensearch/sql/asyncquery/DummyConsumer.java
  async-query/src/test/java/org/opensearch/sql/asyncquery/DummyConsumerTest.java
Labels: maintenance
