Repository opensearch-project/sql, pull requests merged in 2024-06, with the labels that each got.

#2695 Abstract queryId generation
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/OpenSearchAsyncQueryJobMetadataStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/DatasourceEmbeddedQueryIdProvider.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/QueryIdProvider.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryContext.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryResponse.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexDMLResult.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/QueryRequest.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchSessionStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStatementStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/AsyncQueryJobMetadataXContentSerializer.java
  spark/src/main/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexStateModelService.java
  spark/src/main/java/org/opensearch/sql/spark/flint/OpenSearchIndexDMLResultStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/OpenSearchAsyncQueryJobMetadataStorageServiceTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/xcontent/AsyncQueryJobMetadataXContentSerializerTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexStateModelServiceTest.java
Labels: backport 2.x, maintenance

#2707 Introduce SessionConfigSupplier to abstract settings
  spark/src/main/java/org/opensearch/sql/spark/execution/session/OpenSearchSessionConfigSupplier.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionConfigSupplier.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
Labels: backport 2.x, maintenance

#2709 Add accountId to data models
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImpl.java
  spark/src/main/java/org/opensearch/sql/spark/client/StartJobRequest.java
  spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfig.java
  spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSetting.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryRequest.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/CreateSessionRequest.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/AsyncQueryJobMetadataXContentSerializer.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/FlintIndexStateModelXContentSerializer.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/SessionModelXContentSerializer.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/StatementModelXContentSerializer.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/XContentCommonAttributes.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexStateModel.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/client/StartJobRequestTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionTestUtil.java
  spark/src/test/java/org/opensearch/sql/spark/execution/xcontent/AsyncQueryJobMetadataXContentSerializerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/xcontent/FlintIndexStateModelXContentSerializerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/xcontent/SessionModelXContentSerializerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/xcontent/StatementModelXContentSerializerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/xcontent/XContentSerializerTestUtil.java
Labels: backport 2.x, maintenance

#2692 Revert "Delete Spark datasource (#2638)"
  docs/user/ppl/admin/connectors/spark_connector.rst
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/src/main/java/org/opensearch/sql/spark/client/EmrClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/client/SparkClient.java
  spark/src/main/java/org/opensearch/sql/spark/functions/implementation/SparkSqlFunctionImplementation.java
  spark/src/main/java/org/opensearch/sql/spark/functions/resolver/SparkSqlTableFunctionResolver.java
  spark/src/main/java/org/opensearch/sql/spark/functions/scan/SparkSqlFunctionTableScanBuilder.java
  spark/src/main/java/org/opensearch/sql/spark/functions/scan/SparkSqlFunctionTableScanOperator.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkScan.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkStorageEngine.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkStorageFactory.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkTable.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/data/value/SparkExprValueTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionImplementationTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanBuilderTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanOperatorTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlTableFunctionResolverTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/response/DefaultSparkSqlFunctionResponseHandleTest.java
  spark/src/test/java/org/opensearch/sql/spark/helper/FlintHelperTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkScanTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageEngineTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageFactoryTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkTableTest.java
  spark/src/test/resources/all_data_type.json
  spark/src/test/resources/issue2210.json
  spark/src/test/resources/spark_data_type.json
  spark/src/test/resources/spark_execution_result_test.json
Labels: backport 2.x, maintenance

#2715 Pass down request context to data accessors
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorService.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryJobMetadataStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/OpenSearchAsyncQueryJobMetadataStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryRequestContext.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/NullAsyncQueryRequestContext.java
  spark/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImpl.java
  spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigSupplier.java
  spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigSupplierImpl.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryContext.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/Session.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchSessionStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStatementStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/SessionStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StatementStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/flint/IndexDMLResultStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/flint/OpenSearchIndexDMLResultStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/transport/TransportCreateAsyncQueryRequestAction.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecAlterTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/OpenSearchAsyncQueryJobMetadataStorageServiceTest.java
  spark/src/test/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigSupplierImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
Labels: backport 2.x, maintenance

#2724 Add timeout StatementState
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementState.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
Labels: backport 2.x, maintenance

#2726 Abstract sessionId generation
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/DatasourceEmbeddedSessionIdProvider.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/Session.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionId.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionIdProvider.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/SessionModelXContentSerializer.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/StatementModelXContentSerializer.java
  spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/xcontent/SessionModelXContentSerializerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/xcontent/StatementModelXContentSerializerTest.java
Labels: backport 2.x, maintenance

#2733 Scaffold async-query-core and async-query module
  async-query-core/.gitignore
  async-query-core/build.gradle
  async-query-core/src/main/antlr/.gitkeep
  async-query-core/src/main/java/org/opensearch/sql/asyncquery/Dummy.java
  async-query-core/src/test/java/org/opensearch/sql/asyncquery/DummyTest.java
  async-query/.gitignore
  async-query/build.gradle
  async-query/src/main/java/org/opensearch/sql/asyncquery/DummyConsumer.java
  async-query/src/test/java/org/opensearch/sql/asyncquery/DummyConsumerTest.java
  settings.gradle
Labels: backport 2.x, maintenance

#2734 Handle create index with batch FlintJob
  release-notes/opensearch-sql.release-notes-2.15.0.0.md
  spark/src/main/antlr/SqlBaseLexer.g4
  spark/src/main/antlr/SqlBaseParser.g4
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: bug, backport 2.x

#2730 Change DataSourceType from enum to class
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
  core/src/main/java/org/opensearch/sql/utils/SerializeUtils.java
  core/src/test/java/org/opensearch/sql/datasource/model/DataSourceTypeTest.java
  core/src/test/java/org/opensearch/sql/utils/SerializeUtilsTest.java
  datasources/src/main/java/org/opensearch/sql/datasources/exceptions/ErrorMessage.java
  datasources/src/test/java/org/opensearch/sql/datasources/exceptions/ErrorMessageTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorageTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/utils/XContentParserUtilsTest.java
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/ErrorFormatter.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSetting.java
Labels: backport 2.x, maintenance

#2745 Fix code style issue
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
Labels: maintenance

#2744 Separate build and validateAndBuild method in DataSourceMetadata
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
  core/src/test/java/org/opensearch/sql/datasource/model/DataSourceMetadataTest.java
  datasources/src/main/java/org/opensearch/sql/datasources/service/DataSourceServiceImpl.java
  datasources/src/main/java/org/opensearch/sql/datasources/utils/XContentParserUtils.java
Labels: backport 2.x, maintenance

#2760 Exclude integ-test and download task when built offline
  async-query-core/build.gradle
  settings.gradle
Labels: backport 2.x, maintenance

#2747 Abstract metrics to reduce dependency to legacy
  async-query-core/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImpl.java
  async-query-core/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/QueryHandlerFactory.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/metrics/EmrMetrics.java
  async-query-core/src/main/java/org/opensearch/sql/spark/metrics/MetricsService.java
  async-query-core/src/test/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImplTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  async-query/src/main/java/org/opensearch/sql/spark/metrics/OpenSearchMetricsService.java
  async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
Labels: backport 2.x, maintenance

#2754 Remove AsyncQueryId
  async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryId.java
  async-query/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
Labels: backport 2.x, maintenance

#2766 Add README to async-query-core
  async-query-core/README.md
Labels: backport 2.x, maintenance

#2755 Abstract FlintIndex client
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/FlintIndexClient.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpFactory.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuum.java
  async-query-core/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpFactoryTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuumTest.java
  async-query/src/main/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexClient.java
  async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
Labels: backport 2.x, maintenance

#2777 Fix statement to store requested langType
  async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
Labels: backport 2.x, maintenance

#2778 Push down OpenSearch specific exception handling
  async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  async-query-core/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
  async-query/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchSessionStorageService.java
  async-query/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStatementStorageService.java
Labels: backport 2.x, maintenance

#2773 Implement integration test for async-query-core
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
Labels: backport 2.x, maintenance

#2784 Fix SQLQueryUtils to extract multiple tables
  async-query-core/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
Labels: backport 2.x, maintenance

#2786 Eliminate dependency from async-query-core to legacy
  async-query-core/build.gradle
  async-query-core/src/main/java/org/opensearch/sql/spark/rest/model/CreateAsyncQueryRequest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
  async-query/src/main/java/org/opensearch/sql/spark/rest/RestAsyncQueryManagementAction.java
  async-query/src/main/java/org/opensearch/sql/spark/transport/TransportGetAsyncQueryResultAction.java
  async-query/src/main/java/org/opensearch/sql/spark/transport/format/AsyncQueryResultResponseFormatter.java
  async-query/src/main/java/org/opensearch/sql/spark/transport/format/CreateAsyncQueryRequestConverter.java
  async-query/src/main/java/org/opensearch/sql/spark/transport/model/AsyncQueryResult.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  async-query/src/test/java/org/opensearch/sql/spark/transport/format/AsyncQueryResultResponseFormatterTest.java
  async-query/src/test/java/org/opensearch/sql/spark/transport/format/CreateAsyncQueryRequestConverterTest.java
Labels: backport 2.x, maintenance

#2783 Pass accountId to EMRServerlessClientFactory.getClient
  async-query-core/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactory.java
  async-query-core/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImpl.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/QueryHandlerFactory.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java
  async-query-core/src/test/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImplTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecAlterTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
  async-query/src/test/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTaskTest.java
  async-query/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  async-query/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
Labels: backport 2.x, maintenance
