Repository opensearch-project/sql, pull requests merged in 2024-05, with the labels that each got.

#2647 release notes for 2.14.0.0
  release-notes/opensearch-sql.release-notes-2.14.0.0.md
Labels: infrastructure, backport 2.x, backport 2.14

#2644 Refactor IndexDMLHandler and related classes
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/src/main/java/org/opensearch/sql/spark/cluster/ClusterManagerEventListener.java
  spark/src/main/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTask.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/QueryHandlerFactory.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/flint/IndexDMLResultStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/flint/OpenSearchIndexDMLResultStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpAlter.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpCancel.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpDrop.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpFactory.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuum.java
  spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTaskTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpTest.java
Labels: backport 2.x

#2657 Add comments to async query handlers
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/flint/IndexDMLResultStorageService.java
Labels: backport 2.x, maintenance

#2665 Extract SessionStorageService and StatementStorageService
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchSessionStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStatementStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/SessionStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StatementStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionTestUtil.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/TestEMRServerlessClient.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
Labels: backport 2.x, maintenance

#2683 Remove unneeded datasourceName parameters
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchSessionStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStatementStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/SessionStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StatementStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexStateModelService.java
  spark/src/main/java/org/opensearch/sql/spark/flint/IndexDMLResultStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexStateModelService.java
  spark/src/main/java/org/opensearch/sql/spark/flint/OpenSearchIndexDMLResultStorageService.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/MockFlintSparkJob.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexStateModelServiceTest.java
Labels: backport 2.x, maintenance

#2687 Refactor data models to be generic to data storage
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/OpensearchAsyncQueryJobMetadataStorageService.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexDMLResult.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/CopyBuilder.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateCopyBuilder.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateModel.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/AsyncQueryJobMetadataXContentSerializer.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/FlintIndexStateModelXContentSerializer.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/SessionModelXContentSerializer.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/StatementModelXContentSerializer.java
  spark/src/main/java/org/opensearch/sql/spark/execution/xcontent/XContentSerializerUtil.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexStateModel.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java
  spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/OpensearchAsyncQueryAsyncQueryJobMetadataStorageServiceTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/MockFlintSparkJob.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/statestore/StateModelTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/xcontent/AsyncQueryJobMetadataXContentSerializerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/xcontent/IndexDMLResultXContentSerializerTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/xcontent/XContentSerializerUtilTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpTest.java
Labels: backport 2.x, maintenance

#2693 Change JobExecutionResponseReader to an interface
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/response/JobExecutionResponseReader.java
  spark/src/main/java/org/opensearch/sql/spark/response/OpenSearchJobExecutionResponseReader.java
  spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/response/OpenSearchJobExecutionResponseReaderTest.java
Labels: backport 2.x, maintenance
