Repository opensearch-project/sql, pull requests merged in 2024-12, with the labels that each got.

#3177 Fix: CI Github Action
  .github/workflows/integ-tests-with-security.yml
  .github/workflows/sql-pitest.yml
  .github/workflows/sql-test-and-build-workflow.yml
  .github/workflows/sql-test-workflow.yml
Labels: infrastructure

#3187 chore: Update Spring to 5.3.39
  .github/workflows/bi-connectors.yml
  .github/workflows/sql-cli-test-and-build-workflow.yml
  .github/workflows/sql-jdbc-test-and-build-workflow.yml
  .github/workflows/sql-odbc-main.yml
  .github/workflows/sql-test-and-build-workflow.yml
  .github/workflows/sql-test-workflow.yml
  build.gradle
Labels: backport 1.3, maintenance

#3123 Fix FilterOperator to cache next element and avoid repeated consumption on hasNext() calls
  core/src/main/java/org/opensearch/sql/planner/physical/FilterOperator.java
  core/src/test/java/org/opensearch/sql/planner/physical/FilterOperatorTest.java
  integ-test/src/test/resources/correctness/bugfixes/3121.txt
Labels: backport 2.x

#3221 Add stalled PRs workflow
  .github/workflows/stalled.yml
Labels: infrastructure

#2841 Function `str_to_date` should work with two-digits year
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFormatterUtil.java
  core/src/test/java/org/opensearch/sql/expression/datetime/StrToDateTest.java
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
Labels: bug, stalled
