Repository opensearch-project/sql, pull requests merged in 2024-07, with the labels that each got.

#2720 Span in PPL statsByClause could be specified after fields
  docs/user/ppl/cmd/stats.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/StatsCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/util/MatcherUtils.java
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
Labels: backport 2.x

#2727 Well format the raw response when query parameter "pretty" enabled
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/sql/CsvFormatIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/RawFormatIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSQLQueryAction.java
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatter.java
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseFormatter.java
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseWithPrettifier.java
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseWithSanitizer.java
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/RawResponseFormatter.java
  protocol/src/test/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatterTest.java
  protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java
  sql/src/main/java/org/opensearch/sql/sql/domain/SQLQueryRequest.java
  sql/src/test/java/org/opensearch/sql/sql/SQLServiceTest.java
Labels: backport 2.x

#2815 Temp use of older nodejs version before moving to Almalinux8
  .github/workflows/integ-tests-with-security.yml
  .github/workflows/sql-pitest.yml
  .github/workflows/sql-test-and-build-workflow.yml
  .github/workflows/sql-test-workflow.yml
Labels: backport 2.x

#2774 Introduce SparkParameterComposerCollection
  async-query-core/README.md
  async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  async-query-core/src/main/java/org/opensearch/sql/spark/config/SparkSubmitParameterModifier.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/QueryHandlerFactory.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/CreateSessionRequest.java
  async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  async-query-core/src/main/java/org/opensearch/sql/spark/parameter/DataSourceSparkParameterComposer.java
  async-query-core/src/main/java/org/opensearch/sql/spark/parameter/GeneralSparkParameterComposer.java
  async-query-core/src/main/java/org/opensearch/sql/spark/parameter/SparkParameterComposerCollection.java
  async-query-core/src/main/java/org/opensearch/sql/spark/parameter/SparkSubmitParameters.java
  async-query-core/src/main/java/org/opensearch/sql/spark/parameter/SparkSubmitParametersBuilder.java
  async-query-core/src/main/java/org/opensearch/sql/spark/parameter/SparkSubmitParametersBuilderProvider.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParametersTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/parameter/SparkParameterComposerCollectionTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/parameter/SparkSubmitParametersBuilderTest.java
  async-query/src/main/java/org/opensearch/sql/spark/config/OpenSearchExtraParameterComposer.java
  async-query/src/main/java/org/opensearch/sql/spark/config/OpenSearchSparkSubmitParameterModifier.java
  async-query/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSetting.java
  async-query/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSettingLoader.java
  async-query/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigSupplierImpl.java
  async-query/src/main/java/org/opensearch/sql/spark/parameter/S3GlueDataSourceSparkParameterComposer.java
  async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  async-query/src/test/java/org/opensearch/sql/spark/config/OpenSearchExtraParameterComposerTest.java
  async-query/src/test/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSettingLoaderTest.java
  async-query/src/test/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigSupplierImplTest.java
  async-query/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java
  async-query/src/test/java/org/opensearch/sql/spark/execution/session/SessionTestUtil.java
  async-query/src/test/java/org/opensearch/sql/spark/parameter/S3GlueDataSourceSparkParameterComposerTest.java
Labels: backport 2.x, maintenance

#2820 Fix yaml errors causing checks not to be run
  .github/workflows/integ-tests-with-security.yml
  .github/workflows/sql-test-and-build-workflow.yml
Labels: bug, backport 2.x

#2759 SQL pagination should work with the `pretty` parameter
  integ-test/src/test/java/org/opensearch/sql/jdbc/CursorIT.java
  sql/src/main/java/org/opensearch/sql/sql/domain/SQLQueryRequest.java
  sql/src/test/java/org/opensearch/sql/sql/domain/SQLQueryRequestTest.java
Labels: bug, backport 2.x

#2831 Add MacOS workflows back and fix the artifact not found issue
  .github/workflows/integ-tests-with-security.yml
  .github/workflows/sql-test-and-build-workflow.yml
Labels: maintenance

#2835 Update to Gradle 8.9
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: maintenance

#2837 Fix SparkSubmitParameterModifier issue
  async-query-core/src/main/java/org/opensearch/sql/spark/parameter/SparkSubmitParametersBuilder.java
  async-query-core/src/test/java/org/opensearch/sql/spark/parameter/SparkSubmitParametersBuilderTest.java
Labels: bug, backport 2.x

#2790 Restrict UDF functions
  async-query-core/src/main/antlr/SqlBaseLexer.g4
  async-query-core/src/main/antlr/SqlBaseParser.g4
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  async-query-core/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
  docs/user/interfaces/asyncqueryinterface.rst
Labels: bug, backport 2.x

#2850 [Backport 2.x] Updating Grammer changes same as main branch
  async-query-core/src/main/antlr/FlintSparkSqlExtensions.g4
  async-query-core/src/main/antlr/SqlBaseLexer.g4
  async-query-core/src/main/antlr/SqlBaseParser.g4
Labels: v2.16.0

#2838 Fix SparkExecutionEngineConfigClusterSetting deserialize issue
  async-query/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSetting.java
Labels: bug, backport 2.x, v2.16.0

#2756 Support complex predicates for `IF` function in PPL
  docs/user/ppl/functions/condition.rst
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
  sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Labels: backport 2.x

#2854 Add release notes for v2.16.0
  release-notes/opensearch-sql.release-notes-2.16.0.0.md
Labels: release, backport 2.x, v2.16.0, backport 2.16

#2865 Fix Integ test for datasource enabled setting with security plugin
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceEnabledIT.java
Labels: backport 2.x, backport 2.16

#2866 Add RequestContext parameter to verifyDataSourceAccessAndGetRawMetada method
  async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryRequestContext.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceService.java
  core/src/main/java/org/opensearch/sql/datasource/RequestContext.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  datasources/src/main/java/org/opensearch/sql/datasources/service/DataSourceServiceImpl.java
  datasources/src/test/java/org/opensearch/sql/datasources/service/DataSourceServiceImplTest.java
Labels: backport 2.x, maintenance

#2871 Fixes for 2.16 integ test failures
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceEnabledIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java
Labels: backport 2.x, backport 2.16

#2860 Change the default value of plugins.query.size_limit to MAX_RESULT_WINDOW (10000)
  docs/user/admin/settings.rst
  docs/user/optimization/optimization.rst
  docs/user/ppl/admin/settings.rst
  docs/user/ppl/interfaces/endpoint.rst
  integ-test/src/test/java/org/opensearch/sql/legacy/ExplainIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
Labels: enhancement, backport 2.x

#2872 [Backport 2.x] Add RequestContext parameter to verifyDataSourceAccessAndGetRawMetada…
  async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryRequestContext.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  core/src/main/java/org/opensearch/sql/datasource/DataSourceService.java
  core/src/main/java/org/opensearch/sql/datasource/RequestContext.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  datasources/src/main/java/org/opensearch/sql/datasources/service/DataSourceServiceImpl.java
  datasources/src/test/java/org/opensearch/sql/datasources/service/DataSourceServiceImplTest.java
Labels: maintenance

#2870 Add AsyncQueryRequestContext to QueryIdProvider parameter
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/DatasourceEmbeddedQueryIdProvider.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/QueryIdProvider.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/DatasourceEmbeddedQueryIdProviderTest.java
Labels: backport 2.x, maintenance

#2878 Fixed integ test delete myindex issue and wipe All indices with security plugin.
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceEnabledIT.java
Labels: backport 2.x, backport 2.16

#2834 [Feature] Flint query scheduler part1 - integrate job scheduler plugin
  .gitignore
  async-query-core/src/main/antlr/SqlBaseParser.g4
  async-query/build.gradle
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/OpenSearchAsyncQueryScheduler.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/OpenSearchRefreshIndexJobRequestParser.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/job/OpenSearchRefreshIndexJob.java
  async-query/src/main/java/org/opensearch/sql/spark/scheduler/model/OpenSearchRefreshIndexJobRequest.java
  async-query/src/main/resources/async-query-scheduler-index-mapping.yml
  async-query/src/main/resources/async-query-scheduler-index-settings.yml
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/OpenSearchAsyncQuerySchedulerTest.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/job/OpenSearchRefreshIndexJobTest.java
  async-query/src/test/java/org/opensearch/sql/spark/scheduler/model/OpenSearchRefreshIndexJobRequestTest.java
  build.gradle
  common/build.gradle
  core/build.gradle
  doctest/build.gradle
  integ-test/build.gradle
  legacy/build.gradle
  plugin/build.gradle
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  plugin/src/main/resources/META-INF/services/org.opensearch.jobscheduler.spi.JobSchedulerExtension
  ppl/build.gradle
  protocol/build.gradle
  sql/build.gradle
Labels: feature, backport 2.x, v2.17.0
