Repository opensearch-project/sql, pull requests merged in 2024-11, with the labels that each got.

#3079 Fix a regression issue of parsing datetime string with custom time format in Span
  core/src/main/java/org/opensearch/sql/planner/physical/collector/Rounding.java
  core/src/test/java/org/opensearch/sql/planner/physical/collector/RoundingTest.java
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeImplementationIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
Labels: bug, backport 2.x, v2.18.0, backport 2.18

#3063 Fix: CSV and Raw output, escape quotes
  protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java
  protocol/src/test/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatterTest.java
  protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java
Labels: backport 2.x

#3153 Call LeaseManager for BatchQuery
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  async-query/src/main/java/org/opensearch/sql/spark/leasemanager/DefaultLeaseManager.java
  async-query/src/test/java/org/opensearch/sql/spark/leasemanager/DefaultLeaseManagerTest.java
Labels: backport 2.x, maintenance

#3161 Make GrammarElement public
  async-query-core/src/main/java/org/opensearch/sql/spark/validator/GrammarElement.java
Labels: backport 2.x, maintenance

#3165 Update grammar validation settings
  async-query-core/src/main/java/org/opensearch/sql/spark/validator/GrammarElement.java
  async-query-core/src/main/java/org/opensearch/sql/spark/validator/S3GlueGrammarElementValidator.java
  async-query-core/src/main/java/org/opensearch/sql/spark/validator/SQLQueryValidationVisitor.java
  async-query-core/src/test/java/org/opensearch/sql/spark/validator/SQLQueryValidatorTest.java
Labels: backport 2.x, maintenance

#3163 Fix: Misc typo and broken link fixes
  docs/dev/intro-architecture.md
  docs/user/general/datatypes.rst
  docs/user/general/identifiers.rst
Labels: documentation
