Repository opensearch-project/sql, pull requests merged in 2024-04, with the labels that each got.

#2602 Add iceberg support to EMR serverless jobs.
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: enhancement, backport 2.x

#2609 Update opensearch-sql.release-notes-2.13.0.0.md to conform with OpenSearch guidelines
  release-notes/opensearch-sql.release-notes-2.13.0.0.md
Labels: backport 2.x, backport 2.13

#2615 Refactoring of SparkQueryDispatcher
  spark/src/main/antlr/SqlBaseLexer.g4
  spark/src/main/antlr/SqlBaseParser.g4
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: backport 2.x, maintenance

#2612 Handle EMRS exception as 400
  spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
Labels: backport 2.x, backport 2.13

#2441 Fix pagination for many columns (#2440)
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScan.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanTest.java
Labels: bug, backport 2.x

#2631 Fix semicolon parsing for async query
  spark/src/main/antlr/SqlBaseLexer.g4
  spark/src/main/antlr/SqlBaseParser.g4
  spark/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  spark/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
Labels: bug, backport 2.x

#2616 Bump bwc version to 2.14
  integ-test/build.gradle
Labels: maintenance

#2632 Use EMR serverless bundled iceberg JAR.
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: backport 2.x, maintenance

#2624 Add option to use LakeFormation in S3Glue data source.
  datasources/src/main/java/org/opensearch/sql/datasources/glue/GlueDataSourceFactory.java
  docs/user/ppl/admin/connectors/s3glue_connector.rst
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: enhancement, backport 2.x

#2638 Delete Spark datasource
  docs/user/ppl/admin/connectors/spark_connector.rst
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/src/main/java/org/opensearch/sql/spark/client/EmrClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/client/SparkClient.java
  spark/src/main/java/org/opensearch/sql/spark/functions/implementation/SparkSqlFunctionImplementation.java
  spark/src/main/java/org/opensearch/sql/spark/functions/resolver/SparkSqlTableFunctionResolver.java
  spark/src/main/java/org/opensearch/sql/spark/functions/scan/SparkSqlFunctionTableScanBuilder.java
  spark/src/main/java/org/opensearch/sql/spark/functions/scan/SparkSqlFunctionTableScanOperator.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkScan.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkStorageEngine.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkStorageFactory.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkTable.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/data/value/SparkExprValueTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionImplementationTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanBuilderTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanOperatorTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlTableFunctionResolverTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/response/DefaultSparkSqlFunctionResponseHandleTest.java
  spark/src/test/java/org/opensearch/sql/spark/helper/FlintHelperTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkScanTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageEngineTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageFactoryTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkTableTest.java
  spark/src/test/resources/all_data_type.json
  spark/src/test/resources/issue2210.json
  spark/src/test/resources/spark_data_type.json
  spark/src/test/resources/spark_execution_result_test.json
Labels: backport 2.x, maintenance

#2636 Refactor SparkQueryDispatcher
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/QueryHandlerFactory.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: backport 2.x, maintenance
