Repository opensearch-project/sql, pull requests merged in 2024-03, with the labels that each got.

#2536 Add release notes for 1.3.15
  release-notes/opensearch-sql.release-notes-1.3.15.0.md
Labels: backport 2.x, backport main

#2544 bump ipaddress to 5.4.2
  common/build.gradle
  spark/src/main/antlr/FlintSparkSqlExtensions.g4
  spark/src/main/antlr/SparkSqlBase.g4
  spark/src/main/antlr/SqlBaseParser.g4
Labels: backport 2.x

#2546 bump bwc version
  integ-test/build.gradle
Labels: maintenance, v2.13.0

#2543 Change emr job names based on the query type
  spark/src/main/antlr/SqlBaseParser.g4
  spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/CreateSessionRequest.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
  spark/src/test/java/org/opensearch/sql/spark/rest/model/CreateAsyncQueryRequestTest.java
Labels: enhancement, backport 2.x, v2.13.0

#2539 Datasource disable feature
  core/build.gradle
  core/src/main/java/org/opensearch/sql/datasource/DataSourceService.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceStatus.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
  core/src/test/java/org/opensearch/sql/datasource/model/DataSourceMetadataTest.java
  core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScanTest.java
  datasources/src/main/java/org/opensearch/sql/datasources/exceptions/DataSourceNotFoundException.java
  datasources/src/main/java/org/opensearch/sql/datasources/exceptions/DatasourceDisabledException.java
  datasources/src/main/java/org/opensearch/sql/datasources/service/DataSourceServiceImpl.java
  datasources/src/main/java/org/opensearch/sql/datasources/utils/XContentParserUtils.java
  datasources/src/main/resources/datasources-index-mapping.yml
  datasources/src/test/java/org/opensearch/sql/datasources/auth/DataSourceUserAuthorizationHelperImplTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/glue/GlueDataSourceFactoryTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/service/DataSourceLoaderCacheImplTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/service/DataSourceServiceImplTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorageTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportUpdateDataSourceActionTest.java
  datasources/src/test/java/org/opensearch/sql/datasources/utils/XContentParserUtilsTest.java
  docs/user/ppl/admin/datasources.rst
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ShowDataSourcesCommandIT.java
  integ-test/src/test/resources/datasources.json
  prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/rest/RestAsyncQueryManagementAction.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageFactoryTest.java
Labels: feature, backport 2.x, v2.13.0

#2519 Refactor query param
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/client/StartJobRequest.java
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/CreateSessionRequest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParametersTest.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/client/StartJobRequestTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
Labels: backport 2.x

#2548 Restrict the scope of cancel API
  docs/user/interfaces/asyncqueryinterface.rst
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryResponse.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReader.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImpl.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
Labels: backport 2.x

#2557 Implement vacuum index operation
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryActionType.java
  spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexState.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuum.java
  spark/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/MockFlintSparkJob.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java
  spark/src/test/resources/flint-index-mappings/0.1.1/flint_covering_index.json
  spark/src/test/resources/flint-index-mappings/0.1.1/flint_mv.json
  spark/src/test/resources/flint-index-mappings/0.1.1/flint_skipping_index.json
Labels: enhancement, backport 2.x

#2561 Change async query default setting
  docs/user/admin/settings.rst
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
Labels: backport 2.x, v2.13.0

#2564 Percent encode opensearch index name
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryDetails.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
  spark/src/test/java/org/opensearch/sql/spark/flint/IndexQueryDetailsTest.java
  spark/src/test/resources/flint-index-mappings/0.1.1/flint_special_character_index.json
  spark/src/test/resources/flint-index-mappings/flint_special_character_index.json
Labels: enhancement, backport 2.x, v2.13.0

#2559 Stop Streaming Jobs When datasource is disabled/deleted.
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
  docs/user/admin/settings.rst
  legacy/src/main/java/org/opensearch/sql/legacy/metrics/MetricName.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  spark/src/main/java/org/opensearch/sql/spark/cluster/ClusterManagerEventListener.java
  spark/src/main/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTask.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadata.java
  spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataServiceImpl.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
  spark/src/test/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTaskTest.java
  spark/src/test/resources/flint-index-mappings/flint_my_glue_mydb_http_logs_covering_error_index_mapping.json
  spark/src/test/resources/flint-index-mappings/flint_skipping_index.json
Labels: enhancement, backport 2.x, v2.13.0

#2565 [Bugfix] Wrap the query with double quotes
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: bug, backport 2.x, v2.13.0

#2568 Upgrade opensearch-spark jars to 0.3.0
  docs/user/ppl/admin/connectors/spark_connector.rst
  spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
  spark/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Labels: backport 2.x, backport 2.13

#2574 FlintStreamingJobCleanerTask missing event listener
  spark/src/main/java/org/opensearch/sql/spark/cluster/ClusterManagerEventListener.java
Labels: bug, backport 2.x, v2.13.0, backport 2.13

#2578 Added release notes for 2.13.0.0
  release-notes/opensearch-sql.release-notes-2.13.0.0.md
Labels: documentation, backport 2.x, backport 2.13

#2582 Fix for dataSources Integ test issue.
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
Labels: bug, backport 2.x, v2.13.0, backport 2.13

#2587 Bug Fix: Escape query in spark submit parameter
  common/build.gradle
  core/build.gradle
  legacy/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParametersTest.java
Labels: bug, backport 2.x, v2.13.0, backport 2.13

#2577 Handle EMR Exceptions in FlintCancelJob Operation
  docs/user/admin/settings.rst
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
  spark/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClient.java
  spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
  spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecAlterTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
  spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/MockFlintIndex.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
Labels: bug, backport 2.x, v2.13.0, backport 2.13

#2594 Removing old datasources model integ test and added unit test.
  datasources/src/test/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorageTest.java
  integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
Labels: bug, backport 2.x, backport 2.13
