Repository opensearch-project/sql, pull requests merged in 2024-10, with the labels that each got.

#2893 Refer Antlr file using specific branch
  async-query-core/README.md
  async-query-core/build.gradle
  async-query-core/src/main/antlr/SqlBaseLexer.g4
  async-query-core/src/main/antlr/SqlBaseParser.g4
Labels: maintenance

#2960 Resolve Alias Issues in Legacy SQL with Filters
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/sql/PaginationIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/format/SelectResultSet.java
Labels: backport 2.x

#3056 Disable join types in validators
  async-query-core/src/main/java/org/opensearch/sql/spark/validator/S3GlueGrammarElementValidator.java
  async-query-core/src/main/java/org/opensearch/sql/spark/validator/SQLQueryValidationVisitor.java
  async-query-core/src/main/java/org/opensearch/sql/spark/validator/SecurityLakeGrammarElementValidator.java
  async-query-core/src/test/java/org/opensearch/sql/spark/validator/SQLQueryValidatorTest.java
Labels: backport 2.x, maintenance

#3066 Improve error handling for malformed query cursors
  integ-test/src/test/java/org/opensearch/sql/legacy/CursorIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/cursor/CursorResultExecutor.java
Labels: bug, v2.18.0

#3053 Update doctest code for more consistent runs
  docs/user/beyond/partiql.rst
  docs/user/dql/aggregations.rst
  docs/user/dql/basics.rst
  docs/user/dql/complex.rst
  docs/user/dql/expressions.rst
  docs/user/dql/functions.rst
  docs/user/dql/metadata.rst
  docs/user/dql/window.rst
  docs/user/general/comments.rst
  docs/user/general/datatypes.rst
  docs/user/general/identifiers.rst
  docs/user/general/values.rst
  docs/user/ppl/admin/connectors/prometheus_connector.rst
  docs/user/ppl/admin/cross_cluster_search.rst
  docs/user/ppl/cmd/ad.rst
  docs/user/ppl/cmd/dedup.rst
  docs/user/ppl/cmd/describe.rst
  docs/user/ppl/cmd/eval.rst
  docs/user/ppl/cmd/fields.rst
  docs/user/ppl/cmd/grok.rst
  docs/user/ppl/cmd/head.rst
  docs/user/ppl/cmd/information_schema.rst
  docs/user/ppl/cmd/ml.rst
  docs/user/ppl/cmd/parse.rst
  docs/user/ppl/cmd/patterns.rst
  docs/user/ppl/cmd/rare.rst
  docs/user/ppl/cmd/rename.rst
  docs/user/ppl/cmd/search.rst
  docs/user/ppl/cmd/showdatasources.rst
  docs/user/ppl/cmd/sort.rst
  docs/user/ppl/cmd/stats.rst
  docs/user/ppl/cmd/top.rst
  docs/user/ppl/cmd/where.rst
  docs/user/ppl/functions/condition.rst
  docs/user/ppl/functions/conversion.rst
  docs/user/ppl/functions/datetime.rst
  docs/user/ppl/functions/expressions.rst
  docs/user/ppl/functions/math.rst
  docs/user/ppl/functions/relevance.rst
  docs/user/ppl/functions/string.rst
  docs/user/ppl/functions/system.rst
  docs/user/ppl/general/datatypes.rst
  docs/user/ppl/general/identifiers.rst
  doctest/build.gradle
  doctest/test_docs.py
Labels: infrastructure, backport 2.x

#3068 Unify internal OpenSearch exceptions with returned status code
  integ-test/src/test/java/org/opensearch/sql/legacy/CursorIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/executor/format/OpenSearchErrorMessage.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/error/OpenSearchErrorMessage.java
Labels: bug, backport 2.x

#3062 Updating JobExecutionResponseReader interface to add RequestContext
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
  async-query-core/src/main/java/org/opensearch/sql/spark/response/JobExecutionResponseReader.java
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
  async-query/src/main/java/org/opensearch/sql/spark/response/OpenSearchJobExecutionResponseReader.java
  async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
  async-query/src/test/java/org/opensearch/sql/spark/response/OpenSearchJobExecutionResponseReaderTest.java
Labels: backport 2.x, maintenance

#3049 Optimize scheduler interval conf
  async-query/src/main/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposer.java
  async-query/src/test/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposerTest.java
Labels: backport 2.x, backport 2.17

#2928 Fix grammar in log warnings.
  integ-test/src/test/java/org/opensearch/sql/ppl/ResourceMonitorIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/executor/protector/ResourceMonitorPlan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/monitor/OpenSearchMemoryHealthy.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/ResourceMonitorPlanTest.java
Labels: backport 2.x

#3083 bump commons-io to 2.14.0
  async-query/build.gradle
  datasources/build.gradle
  spark/build.gradle
Labels: backport 2.x, maintenance

#3090 [Backport 2.17] Upgrade org.bouncycastle:bcprov-jdk18on to 1.78.1
  .github/workflows/integ-tests-with-security.yml
  .github/workflows/sql-test-and-build-workflow.yml
  datasources/build.gradle
Labels: infrastructure, security fix

#3092 Remove scheduler index from SystemIndexDescriptor
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
Labels: backport 2.x, backport 2.17

#3101 [Manual Backport] Backport #2981 to 2.x
  integ-test/src/test/java/org/opensearch/sql/legacy/CursorIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/PaginationFilterIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/StandalonePaginationIT.java
  integ-test/src/test/resources/expectedOutput/ppl/explain_filter_agg_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_filter_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_limit_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_output.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_sort_push.json
  legacy/src/main/java/org/opensearch/sql/legacy/executor/format/SelectResultSet.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/logical/node/TableScan.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/Paginate.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/SearchHitRow.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/pointInTime/PointInTime.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/scroll/Scroll.java
  legacy/src/test/java/org/opensearch/sql/legacy/query/planner/physical/node/scroll/SearchHitRowTest.java
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/planner/QueryPlannerTest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchRestClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScan.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngineTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtectorTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequestTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanPaginationTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanTest.java
Labels: feature, v2.18.0, backport 2.18

#3080 Improve error handling for some more edge cases
  integ-test/src/test/java/org/opensearch/sql/legacy/MalformedQueryIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/OpenSearchActionFactory.java
  legacy/src/main/java/org/opensearch/sql/legacy/rewriter/matchtoterm/TermFieldRewriter.java
Labels: bug, v2.18.0, backport 2.18

#3087 [Manual Backport] Backport doctest fix to 2.x
  docs/user/beyond/partiql.rst
  docs/user/dql/aggregations.rst
  docs/user/dql/basics.rst
  docs/user/dql/complex.rst
  docs/user/dql/expressions.rst
  docs/user/dql/functions.rst
  docs/user/dql/metadata.rst
  docs/user/dql/window.rst
  docs/user/general/comments.rst
  docs/user/general/datatypes.rst
  docs/user/general/identifiers.rst
  docs/user/general/values.rst
  docs/user/ppl/admin/connectors/prometheus_connector.rst
  docs/user/ppl/admin/cross_cluster_search.rst
  docs/user/ppl/cmd/ad.rst
  docs/user/ppl/cmd/dedup.rst
  docs/user/ppl/cmd/describe.rst
  docs/user/ppl/cmd/eval.rst
  docs/user/ppl/cmd/fields.rst
  docs/user/ppl/cmd/grok.rst
  docs/user/ppl/cmd/head.rst
  docs/user/ppl/cmd/information_schema.rst
  docs/user/ppl/cmd/ml.rst
  docs/user/ppl/cmd/parse.rst
  docs/user/ppl/cmd/patterns.rst
  docs/user/ppl/cmd/rare.rst
  docs/user/ppl/cmd/rename.rst
  docs/user/ppl/cmd/search.rst
  docs/user/ppl/cmd/showdatasources.rst
  docs/user/ppl/cmd/sort.rst
  docs/user/ppl/cmd/stats.rst
  docs/user/ppl/cmd/top.rst
  docs/user/ppl/cmd/where.rst
  docs/user/ppl/functions/condition.rst
  docs/user/ppl/functions/conversion.rst
  docs/user/ppl/functions/datetime.rst
  docs/user/ppl/functions/expressions.rst
  docs/user/ppl/functions/math.rst
  docs/user/ppl/functions/relevance.rst
  docs/user/ppl/functions/string.rst
  docs/user/ppl/functions/system.rst
  docs/user/ppl/general/datatypes.rst
  docs/user/ppl/general/identifiers.rst
  doctest/build.gradle
  doctest/test_docs.py
Labels: infrastructure

#3113 Fix tests on 2.18
  docs/user/beyond/partiql.rst
  docs/user/dql/aggregations.rst
  docs/user/dql/basics.rst
  docs/user/dql/complex.rst
  docs/user/dql/expressions.rst
  docs/user/dql/functions.rst
  docs/user/dql/metadata.rst
  docs/user/dql/window.rst
  docs/user/general/comments.rst
  docs/user/general/datatypes.rst
  docs/user/general/identifiers.rst
  docs/user/general/values.rst
  docs/user/ppl/admin/connectors/prometheus_connector.rst
  docs/user/ppl/admin/cross_cluster_search.rst
  docs/user/ppl/cmd/ad.rst
  docs/user/ppl/cmd/dedup.rst
  docs/user/ppl/cmd/describe.rst
  docs/user/ppl/cmd/eval.rst
  docs/user/ppl/cmd/fields.rst
  docs/user/ppl/cmd/grok.rst
  docs/user/ppl/cmd/head.rst
  docs/user/ppl/cmd/information_schema.rst
  docs/user/ppl/cmd/ml.rst
  docs/user/ppl/cmd/parse.rst
  docs/user/ppl/cmd/patterns.rst
  docs/user/ppl/cmd/rare.rst
  docs/user/ppl/cmd/rename.rst
  docs/user/ppl/cmd/search.rst
  docs/user/ppl/cmd/showdatasources.rst
  docs/user/ppl/cmd/sort.rst
  docs/user/ppl/cmd/stats.rst
  docs/user/ppl/cmd/top.rst
  docs/user/ppl/cmd/where.rst
  docs/user/ppl/functions/condition.rst
  docs/user/ppl/functions/conversion.rst
  docs/user/ppl/functions/datetime.rst
  docs/user/ppl/functions/expressions.rst
  docs/user/ppl/functions/math.rst
  docs/user/ppl/functions/relevance.rst
  docs/user/ppl/functions/string.rst
  docs/user/ppl/functions/system.rst
  docs/user/ppl/general/datatypes.rst
  docs/user/ppl/general/identifiers.rst
  doctest/build.gradle
  doctest/test_docs.py
  integ-test/src/test/java/org/opensearch/sql/legacy/MalformedQueryIT.java
Labels: maintenance

#3115 [Manual Backport] Improve error handling for some more edge cases (#3080)
  integ-test/src/test/java/org/opensearch/sql/legacy/MalformedQueryIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/query/OpenSearchActionFactory.java
  legacy/src/main/java/org/opensearch/sql/legacy/rewriter/matchtoterm/TermFieldRewriter.java
Labels: bug

#3125 Add release notes for v2.18.0
  release-notes/opensearch-sql.release-notes-2.18.0.0.md
Labels: release, backport 2.x, v2.18.0, backport 2.18

#3118 Added documentation for the plugins.query.field_type_tolerance setting (#1300)
  docs/user/admin/settings.rst
  docs/user/limitations/limitations.rst
  doctest/test_data/multi_value_long.json
Labels: documentation, backport 2.x
