Repository opensearch-project/sql, pull requests merged in 2025-01, with the labels that each got.

#3231 Incorporated vamsimanohar username change.
  MAINTAINERS.md
Labels: backport 2.x

#3223 Build subprojects in parallel
  .github/workflows/sql-test-and-build-workflow.yml
Labels: infrastructure, backport 2.x

#3225 Fix the flaky test testExtractDatePartWithTimeType()
  core/src/test/java/org/opensearch/sql/expression/datetime/ExtractTest.java
  docs/user/dql/functions.rst
Labels: backport 2.x, flaky-test

#2843 Dedup running workflows on push action with auto-backport
  .github/workflows/codeql-analysis.yml
  .github/workflows/integ-tests-with-security.yml
  .github/workflows/sql-test-and-build-workflow.yml
Labels: infrastructure

#3236 [Backport 2.x] Fix: CI Github Action
  .github/workflows/codeql-analysis.yml
  .github/workflows/integ-tests-with-security.yml
  .github/workflows/link-checker.yml
  .github/workflows/maven-publish.yml
  .github/workflows/sql-test-and-build-workflow.yml
Labels: infrastructure

#2789 Allow metadata fields in PPL query
  core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
  docs/user/ppl/general/identifiers.rst
  integ-test/src/test/java/org/opensearch/sql/ppl/FieldsCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/WhereCommandIT.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
Labels: backport 2.x

#3239 [2.x] Artifacts to upload should include the java version in its name to avoid conflicts
  .github/workflows/sql-test-and-build-workflow.yml
Labels: infrastructure

#3244 CI: Geo-Spatial Plugin integration test
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/ppl/GeoIpFunctionsIT.java
Labels: infrastructure, backport 2.x

#3246 Support for OpenSearch alias type
  core/src/main/java/org/opensearch/sql/data/type/ExprType.java
  core/src/main/java/org/opensearch/sql/expression/ReferenceExpression.java
  core/src/test/java/org/opensearch/sql/data/type/ExprTypeTest.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
  integ-test/src/test/java/org/opensearch/sql/ppl/DataTypeIT.java
  integ-test/src/test/resources/alias.json
  integ-test/src/test/resources/indexDefinitions/alias_index_mapping.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchAliasType.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataType.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataTypeTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
  opensearch/src/test/resources/mappings/accounts.json
Labels: enhancement, backport 2.x

#3227 [Backport 2.x] Function `str_to_date` should work with two-digits year
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFormatterUtil.java
  core/src/test/java/org/opensearch/sql/expression/datetime/StrToDateTest.java
  integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
Labels: bug
