Repository opensearch-project/sql, pull requests merged in 2025-09, with the labels that each got.

#4113 Add asc keyword to sort command
  docs/user/ppl/cmd/sort.rst
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLSortIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/SortCommandIT.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
Labels: enhancement, backport 2.19-dev

#4166 Pushdown earliest/latest aggregate functions
  integ-test/src/test/resources/expectedOutput/calcite/explain_earliest_latest.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_earliest_latest_custom_time.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/AggregateAnalyzer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/ArgMaxMinParser.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAbstractTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLEarliestLatestTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/OpenSearchSparkSqlDialect.java
Labels: enhancement, PPL, calcite, pushdown, backport 2.19-dev

#4214 Fix issue caused by merge in Analyzer.java
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
Labels: maintenance, backport 2.19-dev

#4222 Don't recreate indices on every doctest
  doctest/build.gradle
  doctest/test_docs.py
Labels: infrastructure

#4213 Enable pushdown optimization for filtered aggregation
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_eval_complex_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_eval_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_count_eval_complex_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_count_eval_push.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchAggregateIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/AggregateAnalyzer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/AggregateFilterAnalyzer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/AggregateAnalyzerTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/PredicateAnalyzerTest.java
Labels: enhancement, PPL, backport 2.19-dev

#4109 [Feature] Core Implementation of `rex` Command In PPL
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
  core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
  core/src/main/java/org/opensearch/sql/ast/tree/Rex.java
  core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
  core/src/main/java/org/opensearch/sql/calcite/utils/PPLOperandTypes.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLBuiltinOperators.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
  core/src/main/java/org/opensearch/sql/expression/function/udf/RexExtractFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/udf/RexExtractMultiFunction.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  core/src/test/java/org/opensearch/sql/expression/function/udf/RexExtractFunctionTest.java
  core/src/test/java/org/opensearch/sql/expression/function/udf/RexExtractMultiFunctionTest.java
  docs/category.json
  docs/user/ppl/cmd/rex.rst
  docs/user/ppl/index.rst
  integ-test/src/test/java/org/opensearch/sql/calcite/CalciteNoPushdownIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteRexCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/security/CalciteCrossClusterSearchIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_rex.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_rex.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLRexTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
Labels: PPL, feature, calcite, backport 2.19-dev

#3936 Publish datasources module for downstream reuse in unified-ppl-2.19-dev
  build.gradle
Labels: stalled

#3803 Support join field list and join options
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  core/src/main/java/org/opensearch/sql/ast/expression/Argument.java
  core/src/main/java/org/opensearch/sql/ast/expression/Literal.java
  core/src/main/java/org/opensearch/sql/ast/tree/Join.java
  core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
  docs/user/admin/settings.rst
  docs/user/ppl/admin/settings.rst
  docs/user/ppl/cmd/join.rst
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAppendCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLJoinIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/PPLIntegTestCase.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_join_with_criteria_max_option.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_join_with_fields.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_join_with_fields_max_option.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_join_with_criteria_max_option.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_join_with_fields.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_join_with_fields_max_option.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchIndexRules.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/utils/ArgumentFactory.java
  ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAbstractTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLJoinTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
Labels: enhancement, PPL, calcite, backport 2.19-dev

#4263 Fix gitignore to ignore symbolic link
  .gitignore
Labels: maintenance

#4228 Push down limit operator into aggregation bucket size
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/StatsCommandIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_with_script.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_with_sum_enhancement.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_append_command.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_earliest_latest.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_earliest_latest_custom_time.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_filter_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_10from1_10from2_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown2.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown3.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown4.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown5.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_offsets_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_patterns_simple_pattern_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_script_push_on_text.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_sort_then_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_stats_by_span.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_stats_by_timespan.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_stats_by_timespan2.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchLimitIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/AbstractCalciteIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteLogicalIndexScan.java
Labels: enhancement, calcite, pushdown

#4270 Fix the IT issue caused by merging conflict
  integ-test/src/test/resources/expectedOutput/calcite/explain_first_last.json
Labels: maintenance

#4217 `mvjoin` support in PPL Caclite
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
  docs/user/ppl/functions/collection.rst
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteArrayFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_mvjoin.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_mvjoin.json
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLArrayFunctionTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLFunctionTypeTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
Labels: enhancement, backport 2.19-dev

#4106 strftime function implementation
  core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
  core/src/main/java/org/opensearch/sql/expression/datetime/StrftimeFormatterUtil.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLBuiltinOperators.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
  core/src/main/java/org/opensearch/sql/expression/function/udf/datetime/StrftimeFunction.java
  core/src/test/java/org/opensearch/sql/expression/datetime/StrftimeFunctionTest.java
  docs/user/ppl/functions/datetime.rst
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteDateTimeFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/NewAddedCommandsIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_strftime_function.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_strftime_function.json
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLFunctionTypeTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
Labels: enhancement, backport 2.19-dev

#4281 Add non-numeric field support for max/min functions
  docs/user/ppl/cmd/stats.rst
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_max_string_field.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_min_string_field.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_max_string_field.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_min_string_field.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/AggregateAnalyzer.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAggregationTest.java
Labels: enhancement, PPL, calcite, backport 2.19-dev

#4276 Add `values` stats function with UDAF
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  core/src/main/java/org/opensearch/sql/calcite/udf/udaf/ListAggFunction.java
  core/src/main/java/org/opensearch/sql/calcite/udf/udaf/ValuesAggFunction.java
  core/src/main/java/org/opensearch/sql/calcite/utils/PPLOperandTypes.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLBuiltinOperators.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
  docs/user/ppl/admin/settings.rst
  docs/user/ppl/cmd/stats.rst
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteMultiValueStatsIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_values_aggregation.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_values_aggregation.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLEvalTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLFunctionTypeTest.java
Labels: enhancement, backport 2.19-dev

#4320 Spotless precommit: apply instead of check
  .pre-commit-config.yaml
Labels: infrastructure

#4301 Update grammar files and developer guide
  DEVELOPER_GUIDE.rst
  language-grammar/src/main/antlr4/OpenSearchPPLLexer.g4
  language-grammar/src/main/antlr4/OpenSearchPPLParser.g4
Labels: maintenance

#4325 Fix geopoint issue in complex data types
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteGeoPointFormatsIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
  integ-test/src/test/java/org/opensearch/sql/ppl/GeoPointFormatsIT.java
  integ-test/src/test/resources/complex_geo.json
  integ-test/src/test/resources/indexDefinitions/complex_geo_index_mapping.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/util/JdbcOpenSearchDataTypeConvertor.java
Labels: bug, backport 2.19-dev

#4321 [Doc] Correct the comparision table for rex doc
  docs/user/ppl/cmd/rex.rst
Labels: documentation, PPL, calcite, backport 2.19-dev

#3726 Add splunk to ppl cheat sheet
  docs/user/ppl/reference/splunk_to_ppl_cheat_sheet.md
Labels: documentation, PPL, v3.3.0

#4155 [Feature][Enhancement] Enhance patterns command with additional sample_logs output field
  core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
  core/src/main/java/org/opensearch/sql/calcite/udf/udaf/LogPatternAggFunction.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLPatternsIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_patterns_brain_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_patterns_simple_pattern_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_patterns_brain_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_patterns_simple_pattern_agg_push.json
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLPatternsTest.java
Labels: enhancement

#4337 Optimize count aggregation performance by utilizing native doc_count in v3
  core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
  core/src/main/java/org/opensearch/sql/calcite/utils/PlanUtils.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/StatsCommandIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_counts_by1.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_counts_by2.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_counts_by3.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_counts_by4.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_counts_by5.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_counts_by6.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_sort_on_metrics1.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_sort_on_metrics2.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_append_command.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_agg_push1.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_agg_push10.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_agg_push2.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_agg_push3.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_agg_push4.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_agg_push5.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_agg_push6.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_agg_push7.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_agg_push8.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_count_agg_push9.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown2.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown3.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown4.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown5.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown_bucket_nullable1.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_agg_pushdown_bucket_nullable2.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_script_push_on_text.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_stats_by_span.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_stats_by_span_non_bucket_nullable.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_stats_by_timespan.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_stats_by_timespan2.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchRestClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/AggregateAnalyzer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequest.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/OpenSearchResponse.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/BucketAggregationParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/CompositeAggregationParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/CountAsTotalHitsParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/MetricParserHelper.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/NoBucketAggregationParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/OpenSearchAggregationResponseParser.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/AbstractCalciteIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteEnumerableIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexEnumerator.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/AggregateAnalyzerTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchResponseTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAggregationTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLJoinTest.java
Labels: enhancement, calcite, pushdown

#4369 No index found with given index pattern should throw IndexNotFoundException
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/4342.yml
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchRestClient.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
Labels: bug, backport 2.19-dev

#4329 Push down stats with bins on time field into auto_date_histogram
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteBinCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_script_timestamp_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_script_udt_arg_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_stats_bins_on_time.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_stats_bins_on_time2.yaml
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchAggregateIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/AggregateAnalyzer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteLogicalIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilder.java
Labels: bug, PPL, feature, calcite, pushdown, backport 2.19-dev

#4367 Fix timezone dependent test failures
  core/src/test/java/org/opensearch/sql/data/model/ExprValueCompareTest.java
  core/src/test/java/org/opensearch/sql/expression/ExpressionTestBase.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateDiffTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java
  core/src/test/java/org/opensearch/sql/expression/datetime/StrToDateTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/TimeStampAddTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/TimeStampDiffTest.java
  core/src/test/java/org/opensearch/sql/expression/datetime/TimestampTest.java
Labels: maintenance

#4382 Update timechart in SPL/PPL cheat sheet
  docs/user/ppl/reference/splunk_to_ppl_cheat_sheet.md
Labels: documentation, PPL

#4377 Prevent limit pushdown before action building instead of in action executing
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_prevent_limit_push.yaml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3102.yml
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/AbstractCalciteIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteLogicalIndexScan.java
Labels: bug, pushdown, v3.3.0

#4388 Fix bug of missed analyzed node when pushdown filter for Search call
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_filter_with_search.yaml
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
Labels: bug, pushdown, backport 2.19-dev

#4360 Fix `ClassCastException` for value-storing aggregates on nested PPL fields
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
  integ-test/src/test/resources/indexDefinitions/telemetry_test_mapping.json
  integ-test/src/test/resources/telemetry_test_data.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
Labels: bug, backport 2.19-dev

#4381 Fix parse related functions return behavior in case of NULL input
  core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
  core/src/main/java/org/opensearch/sql/calcite/utils/PPLOperandTypes.java
  core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLBuiltinOperators.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
  core/src/main/java/org/opensearch/sql/expression/function/PatternParserFunctionImpl.java
  core/src/main/java/org/opensearch/sql/expression/function/udf/ParseFunction.java
  core/src/main/java/org/opensearch/sql/expression/parse/ParseExpression.java
  core/src/main/java/org/opensearch/sql/expression/parse/RegexExpression.java
  core/src/main/java/org/opensearch/sql/utils/ParseUtils.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLGrokIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLParseIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLPatternsIT.java
  integ-test/src/test/resources/expectedOutput/ppl/explain_patterns_simple_pattern_agg_push.json
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3996.yml
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLGrokTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLParseTest.java
Labels: bug

#4402 Fix numbered token bug and make it optional output in patterns command
  common/src/main/java/org/opensearch/sql/common/patterns/BrainLogParser.java
  common/src/main/java/org/opensearch/sql/common/patterns/PatternUtils.java
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  common/src/test/java/org/opensearch/sql/common/patterns/BrainLogParserTest.java
  core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
  core/src/main/java/org/opensearch/sql/ast/tree/Patterns.java
  core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
  core/src/main/java/org/opensearch/sql/calcite/udf/udaf/LogPatternAggFunction.java
  core/src/main/java/org/opensearch/sql/expression/function/PatternParserFunctionImpl.java
  core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
  docs/category.json
  docs/user/ppl/cmd/patterns.rst
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLPatternsIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ExplainIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_agg_on_window.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_patterns_brain_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_patterns_brain_agg_push.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_patterns_simple_pattern.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_patterns_simple_pattern.yaml
  integ-test/src/test/resources/expectedOutput/calcite/explain_patterns_simple_pattern_agg_push.yaml
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_patterns_brain_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_patterns_brain_agg_push.yaml
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_patterns_simple_pattern.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_patterns_simple_pattern.yaml
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_patterns_simple_pattern_agg_push.yaml
  integ-test/src/test/resources/expectedOutput/ppl/explain_patterns_brain_agg_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_patterns_brain_agg_push.yaml
  integ-test/src/test/resources/expectedOutput/ppl/explain_patterns_simple_pattern.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_patterns_simple_pattern.yaml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3570.yml
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLGrokTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLParseTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLPatternsTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
Labels: bug, backport 2.19-dev

#4417 Version bump: 3.3
  build.gradle
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchDateType.java
Labels: skip-changelog, v3.3.0
