Repository opensearch-project/sql, pull requests merged in 2025-07, with the labels that each got.

#3620 Support Sort pushdown
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLSortIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteSortCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLDateTimeBuiltinFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/SortCommandIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_limit_then_sort_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_multi_sort_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_output.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_sort_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_sort_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_sort_rename_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_sort_then_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_sort_then_limit_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_trendline_sort_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_limit_then_sort_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_multi_sort_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_sort_agg_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_sort_rename_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_sort_then_agg_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_sort_then_limit_push.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/EnumerableIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchIndexRules.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchSortIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/AbstractCalciteIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteEnumerableIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteLogicalIndexScan.java
Labels: enhancement, calcite, backport 2.19-dev

#3801 Update the limitation docs
  docs/dev/intro-v3-engine.md
  docs/user/limitations/limitations.rst
  docs/user/ppl/limitations/limitations.rst
Labels: documentation, calcite, v3.1.0, backport 3.1

#3851 [BugFix] Fix relevance query function over optimization issue in ReduceExpressionsRule
  core/src/main/java/org/opensearch/sql/calcite/CalciteRexNodeVisitor.java
  core/src/main/java/org/opensearch/sql/calcite/utils/PlanUtils.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLBuiltinOperators.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
  core/src/main/java/org/opensearch/sql/expression/function/UserDefinedFunctionBuilder.java
  core/src/main/java/org/opensearch/sql/expression/function/udf/RelevanceQueryFunction.java
  integ-test/src/test/java/org/opensearch/sql/ppl/RelevanceFunctionIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_multi_fields_relevance_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_single_field_relevance_push.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/PredicateAnalyzerTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAggregationTest.java
Labels: bug, calcite, backport 2.19-dev

#3829 Support struct field with dynamic disabled
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3343.yml
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/Content.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/ObjectContent.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContent.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
Labels: bug, backport 2.x, backport 2.19-dev

#3846 Allow warning header for yaml test
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/2489.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3102.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3312.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3477.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3570.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3595.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3607.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3635.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3646.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3655.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3810.yml
Labels: bug, flaky-test

#3853 Skipping codegen and compile for Scan only plan
  core/src/main/java/org/opensearch/sql/calcite/plan/Scannable.java
  core/src/main/java/org/opensearch/sql/calcite/utils/CalciteToolsHelper.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLExplainIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/EnumerableIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteEnumerableIndexScan.java
Labels: enhancement, performance, calcite, backport 2.19-dev

#3786 Add explain ITs with Calcite without pushdown
  integ-test/src/test/java/org/opensearch/sql/calcite/CalciteNoPushdownIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ExplainIT.java
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_fillnull_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_filter_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_filter_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_filter_push_compare_date_string.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_filter_push_compare_time_string.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_filter_push_compare_timestamp_string.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_filter_then_limit_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_limit_10_5_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_limit_10_filter_5_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_limit_10from1_10from2_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_limit_5_10_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_limit_offsets_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_limit_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_limit_then_filter_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_limit_then_sort_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_multi_sort_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_output.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_patterns_brain_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_patterns_simple_pattern.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_patterns_simple_pattern_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_sarg_filter_push_multi_range.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_sarg_filter_push_single_range.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_sarg_filter_push_time_range.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_sort_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_sort_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_sort_rename_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_sort_then_agg_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_sort_then_limit_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_stats_by_span.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_stats_by_timespan.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_stats_by_timespan2.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_trendline_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_trendline_sort_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_filter_agg_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_filter_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_output.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_sort_push.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_trendline_sort_push.json
Labels: maintenance, testing, calcite

#3868 Update ppl documentation index for new functions
  docs/user/ppl/index.rst
Labels: documentation, backport 2.19-dev

#3886 Update the maven snapshot publish endpoint and credential
  .github/get-sonatype-credentials.sh
  .github/workflows/link-checker.yml
  .github/workflows/maven-publish.yml
  .github/workflows/publish-async-query-core.yml
  .github/workflows/publish-grammar-files.yml
  integ-test/build.gradle
  plugin/build.gradle
Labels: infrastructure, ci, maintenance, backport 2.19, backport 2.19-dev

#3882 [BugFix] Fix incorrect push down for Sarg with nullAs is TRUE
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3477.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3570.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3881.yml
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
Labels: bug, calcite, pushdown, backport 2.19-dev

#3850 Support partial filter push down
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteRelevanceFunctionIT.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_partial_filter_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_partial_filter_push2.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchFilterIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/AbstractCalciteIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteLogicalIndexScan.java
Labels: enhancement, calcite, pushdown, backport 2.19-dev

#3849 Support full expression in WHERE clauses
  integ-test/src/test/java/org/opensearch/sql/ppl/WhereCommandIT.java
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstStatementBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/antlr/PPLSyntaxParserTest.java
  ppl/src/test/java/org/opensearch/sql/ppl/parser/AstWhereClauseTest.java
Labels: bug, backport 2.x, backport 2.19-dev

#3895 CVE-2025-48924: upgrade commons-lang3 to 3.18.0
  build.gradle
  core/build.gradle
Labels: enhancement, security fix, backport 2.x, backport 2.19-dev

#3901 Fix flaky tests in `RestHandlerClientYamlTestSuiteIT`
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3102.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3570.yml
  integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3881.yml
Labels: bug, flaky-test, testing, backport 2.19-dev

#3897 Add 'testing' and 'security fix' to enforce-label-action
  .github/workflows/enforce-labels.yml
Labels: infrastructure, skip-changelog

#3859 Filter script pushdown with RelJson serialization in Calcite
  benchmarks/src/jmh/java/org/opensearch/sql/expression/operator/predicate/ExpressionScriptSerdeBenchmark.java
  core/src/main/java/org/opensearch/sql/expression/function/PPLBuiltinOperators.java
  core/src/main/java/org/opensearch/sql/expression/function/udf/ip/CidrMatchFunction.java
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/tpch/CalcitePPLTpchIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/ExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/RelevanceFunctionIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/WhereCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/util/MatcherUtils.java
  integ-test/src/test/resources/expectedOutput/calcite/explain_filter_function_script_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_filter_script_push.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_filter_script_push_diff.json
  integ-test/src/test/resources/expectedOutput/calcite/explain_partial_filter_script_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_filter_function_script_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_filter_script_push.json
  integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_filter_script_push_diff.json
  integ-test/src/test/resources/expectedOutput/ppl/explain_patterns_simple_pattern_agg_push.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/AbstractCalciteIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteLogicalIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanAggregationBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanQueryBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/CalciteScriptEngine.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/CompoundedScriptEngine.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/ExpressionScriptEngine.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/AggregationQueryBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/AggregationBuilderHelper.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/MetricAggregationBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/core/CalciteScript.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/CalciteFilterScript.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/CalciteFilterScriptFactory.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/CalciteFilterScriptLeafFactory.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/serde/DefaultExpressionSerializer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/serde/ExpressionSerializer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/serde/OpenSearchRelInputTranslator.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/serde/RelJsonSerializer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/serde/SerializationWrapper.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/request/PredicateAnalyzerTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/ExpressionScriptEngineTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/AggregationQueryBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/MetricAggregationBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/serde/DefaultExpressionSerializerTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/serde/RelJsonSerializerTest.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/storage/serde/SerializationWrapperTest.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
Labels: enhancement, pushdown, backport 2.19-dev

#3928 Byte number should treated as Long in doc values
  integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/Content.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/ObjectContent.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContent.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/CalciteScriptEngine.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/serde/RelJsonSerializer.java
Labels: bug, calcite, backport 2.19-dev

#3921 Fix create PIT permissions issue
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/security/PPLPermissionsIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/pit/PointInTimeHandlerImpl.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchRestClient.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
Labels: bug, backport 2.19-dev

#3932 Update commons-lang exclude rule to exclude it everywhere
  ppl/build.gradle
Labels: maintenance, backport 2.19-dev
