Repository opensearch-project/sql, pull requests merged in 2025-02, with the labels that each got.

#3274 Update PPL parse command doc with limitation
  docs/user/ppl/cmd/parse.rst
Labels: documentation, backport 2.x

#3299 Fixed week of week based year handling
  core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunctions.java
  core/src/test/java/org/opensearch/sql/expression/datetime/ExtractTest.java
Labels: backport 2.x

#3300 [Release 2.19] Add release notes for 2.19
  release-notes/opensearch-sql.release-notes-2.19.0.0.md
Labels: backport 2.x, backport 2.19

#3258 [POC] Make PPL execute successfully on Calcite engine
  core/src/main/java/org/opensearch/sql/calcite/CalcitePlanContext.java
  core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
  core/src/main/java/org/opensearch/sql/calcite/OpenSearchSchema.java
  core/src/main/java/org/opensearch/sql/calcite/plan/OpenSearchTable.java
  core/src/main/java/org/opensearch/sql/executor/QueryService.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngine.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexEnumerator.java
Labels: calcite

#3304 Add other functions to SQL query validator
  async-query-core/src/main/java/org/opensearch/sql/spark/validator/FunctionType.java
  async-query-core/src/main/java/org/opensearch/sql/spark/validator/SQLGrammarElement.java
  async-query-core/src/main/java/org/opensearch/sql/spark/validator/SQLQueryValidationVisitor.java
  async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/validator/FunctionTypeTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/validator/SQLQueryValidatorTest.java
Labels: enhancement, backport 2.x

#3306 [v3.0.0] Remove SparkSQL support
  DEVELOPER_GUIDE.rst
  async-query-core/build.gradle
  async-query-core/src/main/java/org/opensearch/sql/spark/data/type/SparkDataType.java
  async-query-core/src/main/java/org/opensearch/sql/spark/data/value/SparkExprValue.java
  async-query-core/src/main/java/org/opensearch/sql/spark/functions/response/DefaultSparkSqlFunctionResponseHandle.java
  async-query-core/src/main/java/org/opensearch/sql/spark/functions/response/SparkSqlFunctionResponseHandle.java
  async-query-core/src/test/java/org/opensearch/sql/spark/data/type/SparkDataTypeTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/data/value/SparkExprValueTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/functions/response/DefaultSparkSqlFunctionResponseHandleTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/validator/PPLQueryValidatorTest.java
  async-query-core/src/test/java/org/opensearch/sql/spark/validator/SQLQueryValidatorTest.java
  async-query-core/src/test/resources/spark_execution_result_test.json
  async-query/src/main/resources/query_execution_request_mapping.yml
  async-query/src/main/resources/query_execution_request_settings.yml
  core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
  core/src/test/java/org/opensearch/sql/datasource/model/DataSourceTypeTest.java
  docs/user/ppl/admin/connectors/spark_connector.rst
  plugin/build.gradle
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  settings.gradle
  spark/build.gradle
  spark/src/main/java/org/opensearch/sql/spark/client/EmrClientImpl.java
  spark/src/main/java/org/opensearch/sql/spark/client/SparkClient.java
  spark/src/main/java/org/opensearch/sql/spark/functions/implementation/SparkSqlFunctionImplementation.java
  spark/src/main/java/org/opensearch/sql/spark/functions/resolver/SparkSqlTableFunctionResolver.java
  spark/src/main/java/org/opensearch/sql/spark/functions/scan/SparkSqlFunctionTableScanBuilder.java
  spark/src/main/java/org/opensearch/sql/spark/functions/scan/SparkSqlFunctionTableScanOperator.java
  spark/src/main/java/org/opensearch/sql/spark/helper/FlintHelper.java
  spark/src/main/java/org/opensearch/sql/spark/request/SparkQueryRequest.java
  spark/src/main/java/org/opensearch/sql/spark/response/SparkResponse.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkScan.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkStorageEngine.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkStorageFactory.java
  spark/src/main/java/org/opensearch/sql/spark/storage/SparkTable.java
  spark/src/test/java/org/opensearch/sql/spark/client/EmrClientImplTest.java
  spark/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java
  spark/src/test/java/org/opensearch/sql/spark/data/type/SparkDataTypeTest.java
  spark/src/test/java/org/opensearch/sql/spark/data/value/SparkExprValueTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionImplementationTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanBuilderTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanOperatorTest.java
  spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlTableFunctionResolverTest.java
  spark/src/test/java/org/opensearch/sql/spark/response/SparkResponseTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkScanTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageEngineTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageFactoryTest.java
  spark/src/test/java/org/opensearch/sql/spark/storage/SparkTableTest.java
  spark/src/test/java/org/opensearch/sql/spark/utils/TestUtils.java
  spark/src/test/resources/all_data_type.json
  spark/src/test/resources/issue2210.json
  spark/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  spark/src/test/resources/select_query_response.json
  spark/src/test/resources/spark_data_type.json
Labels: v3.0.0

#3318 Make basic aggregation working (part 1)
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  core/src/main/java/org/opensearch/sql/calcite/CalcitePlanContext.java
  core/src/main/java/org/opensearch/sql/calcite/plan/OpenSearchQueryable.java
  core/src/main/java/org/opensearch/sql/calcite/plan/OpenSearchTable.java
  core/src/main/java/org/opensearch/sql/calcite/utils/OpenSearchRelDataTypes.java
  core/src/main/java/org/opensearch/sql/executor/OpenSearchTypeSystem.java
  core/src/main/java/org/opensearch/sql/executor/QueryService.java
  integ-test/build.gradle
  integ-test/src/test/java/org/opensearch/sql/calcite/CalcitePPLAggregationIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/CalcitePPLBasicIT.java
  integ-test/src/test/java/org/opensearch/sql/calcite/CalcitePPLIntegTestCase.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngine.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexEnumerator.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/util/JdbcUtil.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/util/RestRequestUtil.java
  plugin/src/main/java/org/opensearch/sql/plugin/config/OpenSearchPluginModule.java
  plugin/src/main/plugin-metadata/plugin-security.policy
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLBasicTest.java
Labels: calcite

#2891 Remove dependency from async-query-core to datasources
  async-query-core/build.gradle
  async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
Labels: maintenance

#3326 Remove opendistro settings and endpoints
  common/src/main/java/org/opensearch/sql/common/setting/LegacySettings.java
  docs/user/admin/settings.rst
  integ-test/src/test/java/org/opensearch/sql/bwc/SQLBackwardsCompatibilityIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/ppl/LegacyAPICompatibilityIT.java
  integ-test/src/test/java/org/opensearch/sql/sql/LegacyAPICompatibilityIT.java
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlAction.java
  legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlStatsAction.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/LegacyOpenDistroSettings.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
  plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLQueryAction.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLStatsAction.java
  plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java
Labels: v3.0.0

#3327 [Calcite Engine] Push down project and filter operator into index scan
  core/src/main/java/org/opensearch/sql/calcite/CalcitePlanContext.java
  core/src/main/java/org/opensearch/sql/calcite/plan/OpenSearchTable.java
  core/src/main/java/org/opensearch/sql/calcite/plan/OpenSearchTableScan.java
  core/src/main/java/org/opensearch/sql/executor/QueryService.java
  opensearch/build.gradle
  opensearch/src/main/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngine.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchFilterIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchIndexRules.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchProjectIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteOpenSearchIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexEnumerator.java
Labels: calcite

#3337 [v3.0.0] Deprecate SQL Delete statement
  DEVELOPER_GUIDE.rst
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  docs/user/admin/settings.rst
  docs/user/dml/delete.rst
  docs/user/dql/basics.rst
  docs/user/index.rst
  integ-test/src/test/java/org/opensearch/sql/legacy/DeleteIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/ExplainIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/PluginIT.java
  integ-test/src/test/resources/expectedOutput/delete_explain.json
  legacy/src/main/antlr/OpenSearchLegacySqlLexer.g4
  legacy/src/main/antlr/OpenSearchLegacySqlParser.g4
  legacy/src/main/java/org/opensearch/sql/legacy/query/OpenSearchActionFactory.java
  legacy/src/test/java/org/opensearch/sql/legacy/antlr/semantic/SemanticAnalyzerConfigTest.java
  legacy/src/test/java/org/opensearch/sql/legacy/unittest/JSONRequestTest.java
  legacy/src/test/resources/expectedOutput/delete_explain.json
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
Labels: breaking, v3.0.0

#3278 Clean up syntax error reporting
  common/src/main/java/org/opensearch/sql/common/antlr/SyntaxAnalysisErrorListener.java
  docs/user/dql/troubleshooting.rst
  integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
  integ-test/src/test/java/org/opensearch/sql/ppl/DescribeCommandIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/QueryAnalysisIT.java
  integ-test/src/test/java/org/opensearch/sql/ppl/SearchCommandIT.java
  ppl/src/test/java/org/opensearch/sql/ppl/antlr/PPLSyntaxParserTest.java
Labels: enhancement

#3355 Make basic aggregation working (part 2) : adding tests
  core/src/main/java/org/opensearch/sql/calcite/CalcitePlanContext.java
  core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
  core/src/main/java/org/opensearch/sql/calcite/CalciteRexNodeVisitor.java
  core/src/main/java/org/opensearch/sql/calcite/ExtendedRexBuilder.java
  core/src/main/java/org/opensearch/sql/calcite/utils/DataTypeTransformer.java
  core/src/main/java/org/opensearch/sql/calcite/utils/OpenSearchTypeFactory.java
  core/src/main/java/org/opensearch/sql/executor/QueryService.java
  integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLAggregationIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexEnumerator.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAggregationTest.java
Labels: calcite

#3350 Fix execution errors caused by plan gap
  common/src/main/java/org/opensearch/sql/common/setting/Settings.java
  core/src/main/java/org/opensearch/sql/executor/QueryService.java
  integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLSortIT.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchFilterIndexScanRule.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteOpenSearchIndexScan.java
  opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexEnumerator.java
Labels: calcite

#3364 Implement ppl join command with Calcite
  integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLJoinIT.java
  integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
  integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
  integ-test/src/test/resources/hobbies.json
  integ-test/src/test/resources/indexDefinitions/hobbies_index_mapping.json
  integ-test/src/test/resources/indexDefinitions/occupation_index_mapping.json
  integ-test/src/test/resources/indexDefinitions/state_country_index_mapping.json
  integ-test/src/test/resources/occupation.json
  integ-test/src/test/resources/state_country.json
  ppl/src/main/antlr/OpenSearchPPLLexer.g4
  ppl/src/main/antlr/OpenSearchPPLParser.g4
  ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
  ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLJoinTest.java
Labels: calcite
